// GENERATED by design/tools/forge_rift.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "rift", maps: {
 "mythhub": {
  "rows": [
   "TTTTTTTTn.TTTTTTTTTn.TTTTTTT",
   "TTTT^TTT..TTTTTTTTT..gggT^TT",
   "TTTggggg..TTTTTgTgg..ggggTTT",
   "TTTTg*gg.............ggggTTT",
   "TTTTggg!.............ggggTTT",
   "TTTTgggWWWg^g..gggg!gg*gggTT",
   "TTTTgggggg^gg..TggggggggTgTT",
   "TTTTgggGGGggg..gggΩggggggTTT",
   "TTTgTgggggg**..gggggggg*gTTT",
   "TTggggggggggg..gggggggggTTTT",
   "TTgg!^^gggggg..TTgggggg!gTTT",
   "TTggggggggggg..ggggggggggTTT",
   "e..........................e",
   "............................",
   "TTTggg*ggg¦gg..g¦ggggggggTTT",
   "TTTg!ggg*gggg..gggggggg!gTTT",
   "TTggggggggggg..ggggggggggTTT",
   "e..........................e",
   "............................",
   "TTTggg¡gggggg..^g^ggggggg^TT",
   "TTTgggCgggRgg..Tgggg*ggggTTT",
   "TTTTggggggggg..gTTgggggggTTT",
   "TTTgggTTTTggg..TTTTTTTTgTTTT",
   "TTTT^TTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "7,4": "mythhub:4,1",
   "19,5": "mythhub:10,2",
   "4,10": "mythhub:4,3",
   "23,10": "mythhub:11,3",
   "4,15": "mythhub:4,7",
   "23,15": "mythhub:11,7",
   "10,20": "mythhub:9,9"
  },
  "marks": {
   "18,7": "lm_where_monsters_come_from"
  },
  "finds": {
   "24,21": {
    "id": "rift_hub_star",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "summit",
    "x": 7,
    "y": 2
   },
   "0,12": {
    "map": "rift1",
    "x": 26,
    "y": 12
   },
   "27,12": {
    "map": "rift2",
    "x": 1,
    "y": 12
   },
   "8,0": {
    "map": "rift5",
    "x": 13,
    "y": 22
   },
   "19,0": {
    "map": "rift6",
    "x": 13,
    "y": 22
   },
   "0,17": {
    "map": "rift3",
    "x": 26,
    "y": 12
   },
   "27,17": {
    "map": "rift4",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift1": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTgTgTTTTTTTTTTTTTgggTTTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggg^ggg..ggggggggTg^TT",
   "TTTTgTggggggg..ggggggggggTTT",
   "TTT*Tggg^gggG..GGggggggggTTT",
   "TTTgT*ggΩgggG..GGGGGGGgTgTTT",
   "TTTgggg**gggG..GGggTg^g^TTTT",
   "TTTgggggggggg..g!gggggTgTTTT",
   "TTTgggWWWgggg..ggTggggggTTTT",
   "TTTg*gggggggg..ggggTggggTTTT",
   "TTT........................e",
   "TTg.........................",
   "TTgggggT^gggg..¦ggggggggTTTT",
   "TTggTgggg^ggg..gggggggggTTTT",
   "TTTgggggRgggg..gggggggTgTTTT",
   "TTTgg*gTggggg..gGGGggggTgTTT",
   "TTTgT*ggggggg..ggggggggggTTT",
   "TT^gggggggggg..gggggggggg^TT",
   "TTTgggggggggg..ggggggggggTTT",
   "TT^gggggggggg..g^Tg*ggggg^TT",
   "TTTTTTTTTTTTTTT^TTT^TTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "16,9": "rift1:7,3",
   "8,16": "rift1:14,1"
  },
  "marks": {
   "8,7": "lm_cyclops"
  },
  "finds": {
   "4,3": {
    "id": "rift_r1",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "27,12": {
    "map": "mythhub",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   26,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift2": {
  "rows": [
   "TTTTTTTTn.TTTTTTTTTn.TTTTTTT",
   "TTTgTggT..gTTTTTTTT..TTTTTTT",
   "TTTggggg..gggTggg*g..Tggg^TT",
   "TTTggggg..ggg..ggg*..gggTTTT",
   "TTTggggg..ggg..gggg..gggg^TT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTT^gggTggGGG..^gggggggg*gTT",
   "TTTgggggggggg..^^^ΩggggTgTTT",
   "TTTgggTTggggg..ggggTggggTTTT",
   "TTTggggggg!gg..ggggggTgggTTT",
   "TT^gggggggggg..gggggTggggTTT",
   "TTTgTg^g^gggg..GGGgggggTgTTT",
   "e.........................TT",
   "..........................TT",
   "TTTgggggggggg..GggggggggTTTT",
   "TTggggggggggg..GgggggggggTTT",
   "TTTgggggggggg..GggRgggggTTTT",
   "TTTgTgggggggg..gggggggggTTTT",
   "TTTTggg*ggggg..gggggg*ggTTTT",
   "TTT^gTggggggg..ggggggggggTTT",
   "TTTT*g*gggggg..ggggggggggTTT",
   "TTTTggggg*ggg..gTTggggTTggTT",
   "TTTTTgT^TTgggg^TTTT^TTTTTTTT",
   "TTTTTTTTTTTTT^TTTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift2:7,3",
   "18,16": "rift2:13,2"
  },
  "marks": {
   "18,7": "lm_kraken"
  },
  "finds": {
   "24,21": {
    "id": "rift_r2",
    "item": "coins",
    "n": 540
   }
  },
  "exits": {
   "0,12": {
    "map": "mythhub",
    "x": 26,
    "y": 12
   },
   "8,0": {
    "map": "rift_north",
    "x": 13,
    "y": 22
   },
   "19,0": {
    "map": "rift_isles",
    "x": 13,
    "y": 22
   }
  },
  "beyond": {},
  "land": [
   1,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift3": {
  "rows": [
   "TTTTTTTTn.TTTTTTTTTn.TTTTTTT",
   "TTTTTTTT..TTTTTTTTT..TTTTTTT",
   "TTTggggg..TTgT^TggT..ggggTTT",
   "TT^ggggg..gg*..gggg..gggggTT",
   "TTTggggg..g*g..gggg..gggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..ggGGGGGggggTT",
   "TTTTggggΩgggG..GGGGGGGggggTT",
   "TTTTggggggggg..ggGGGGGggggTT",
   "TTTTggggggggg..^!gggggggggTT",
   "TTTTggggWWWgg..^gggggggggTTT",
   "TTT^gTggggggg..gg*gggggggTTT",
   "TTT........................e",
   "TTT.........................",
   "TTTTgggggTT^T..GGGggg^g^gTTT",
   "TTTTgTggTgg^g..GGGg*gggggTTT",
   "TTTTgTggggRgg..GGGgggggggTTT",
   "TTTTgggTgg*gg..ggg*ggggggTTT",
   "TTTTggggggggg..ggg*ggggggTTT",
   "TTTTggggggggg..ggggggggg*TTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTggTTTTTggg..TTTTTggggTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TT^TTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "16,9": "rift3:7,3",
   "10,16": "rift3:8,7"
  },
  "marks": {
   "8,7": "lm_sacred_ibis"
  },
  "finds": {
   "4,21": {
    "id": "rift_r3",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {
   "27,12": {
    "map": "mythhub",
    "x": 1,
    "y": 17
   },
   "8,0": {
    "map": "rift_africa",
    "x": 13,
    "y": 22
   },
   "19,0": {
    "map": "rift_neareast",
    "x": 13,
    "y": 22
   }
  },
  "beyond": {},
  "land": [
   26,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift4": {
  "rows": [
   "TTTTTT^TTTTTTn.TTTTTTTTTTTTT",
   "TTTTTTgTTTTTT..TTTTTTTTTTTTT",
   "TTTTTgg*ggggT..ggTTTgTgTTTTT",
   "TTTTgggg*gggg..gggggggggggTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTT^gTggggggg..g*ggggggggTTT",
   "TTTTggggggggg..gggggggggTTTT",
   "TTTgggggggggg..gggΩgggggTTTT",
   "TTTTggggg!ggg..ggWWWggggTTTT",
   "TTTTgggggGGGG..gggg^gggggTTT",
   "TTTgggggGGGGG..ggg^g*ggggTTT",
   "TTTTggggggggg..ggTgggggg^TTT",
   "e.........................TT",
   "..........................TT",
   "TTTTTTggggggg..gTTggggggTTTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTTTggggg*gg..^ggRggggggTTT",
   "TTTgTgggggggg..^ggg*gggggTTT",
   "TTTggggGGGGGg..ggggggggTgTTT",
   "TTTggggGGGGGg..gggggggggTTTT",
   "TTTggggGGGGGg..gg**gggggTTTT",
   "TTTggTggggggg..gggg^TTgg^TTT",
   "TT^TTTTTT^TTTTgTTT^TTT^ggTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "9,8": "rift4:7,3",
   "18,16": "rift4:8,1"
  },
  "marks": {
   "18,7": "lm_dragon_bones"
  },
  "finds": {
   "23,20": {
    "id": "rift_r4",
    "item": "antidote",
    "n": 1
   }
  },
  "exits": {
   "0,12": {
    "map": "mythhub",
    "x": 26,
    "y": 17
   },
   "13,0": {
    "map": "rift_eastasia",
    "x": 13,
    "y": 22
   }
  },
  "beyond": {},
  "land": [
   1,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift5": {
  "rows": [
   "TTTTTTTT^TTTTTTTTTTTTTTTTTTT",
   "TTTTTTgTgggg^TTTTTgTTTTTTTTT",
   "TTggggggggggggggggg*gTgggTTT",
   "TTggggggg*ggg..ggTgggggggTTT",
   "TTgg*gggggggg..ggggggggggTTT",
   "TTgggggWWWggg..TggTggggggTTT",
   "TTTgGGGGGgggg..ggggggggggTTT",
   "TTTgggggggggg..gggΩggggTgTTT",
   "TTT*Tgggggggg..ggggggggggTTT",
   "TTTggggggg!gg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTgggTggg*g..gg^^ggggggTTT",
   "e.........................TT",
   "..........................TT",
   "TTTgTgT^g^ggg..gggggg^gggTTT",
   "T^ggggggggggg..gggg^gggggTTT",
   "TTTgggggggggg..ggRggggggTTTT",
   "TTTg*gggggggg..gggggggggTTTT",
   "TTggggggggggg..GGGGGGGggTTTT",
   "TTTgggggggggg..GGGGGgggg^TTT",
   "TTTggggggg*gg..GGGGGggggTTTT",
   "TTTgggggggggg..gggggg*ggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTggggggggggs.ggggggggggTTT"
  ],
  "cast": {
   "10,9": "rift5:7,3",
   "17,16": "rift5:6,5"
  },
  "marks": {
   "18,7": "lm_komodo"
  },
  "finds": {
   "24,3": {
    "id": "rift_r5",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "mythhub",
    "x": 8,
    "y": 1
   },
   "0,12": {
    "map": "rift_oceania",
    "x": 26,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift_north": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTggT^gTggTTTTTTT",
   "TTTggggggggggggggggggg*ggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTgTgggg^gg..GGGgT^TgTgTTT",
   "TTT^ggggggggg..ggggggTgggTTT",
   "TTTggggggg^gg..gggΩ^ggTgTTTT",
   "TT^gggggggggg..ggggGGG^ggTTT",
   "TTTggggggg!gg..ggggGGGgggTTT",
   "TTTgggggggggg..GGggGGG^ggTTT",
   "TTT*gggg*gggg..gTggggggggTTT",
   "TTT.......................TT",
   "TTT.......................TT",
   "TTTgggggggggg..gTgg*gggg*TTT",
   "TTTgggggggggg..ggTgggggggTTT",
   "TTTgTgggggggg..gggggggggggTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTTgTgggg*gg..*ggggggggggTT",
   "TTTTgTggggggg..gggggggggggTT",
   "TTTggg*gggggg..ggggggggggTTT",
   "TTTTggggTTTgg..gggggggggg^TT",
   "TTTTTTTTTTTTT..ggTTTTTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTT^TT"
  ],
  "cast": {
   "10,9": "rift_north:7,3"
  },
  "marks": {
   "18,7": "lm_reindeer_eyes"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_north",
    "item": "coins",
    "n": 560
   }
  },
  "exits": {
   "13,23": {
    "map": "rift2",
    "x": 8,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift_isles": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTT^TTTTTTTTTTTTTTTTTTgTTTTT",
   "TTTggTTgTTTTTggTTTTggggggTTT",
   "TTTgggggggg^^..ggggggggggTTT",
   "TTTggggggggg^..gggggggggTTTT",
   "TTTggg*^ggggg..TgggggggTgTTT",
   "TTTTggg^ggg^g..ggTTgggggg^TT",
   "TTTgggggggggg..gggΩgggggTTTT",
   "TTTgggggggggg..gggggggggg^TT",
   "TTTggggggg!gg..gGGGGGggTgTTT",
   "TTggGGGGGgggg..gTggggggggTTT",
   "TTgTGGGGGgggg..gTggggggggTTT",
   "TTT.......................TT",
   "TTT.......................TT",
   "TT^gggggggggg..TgggggggggTTT",
   "TTTgTGGGGgggg..ggggggggggTTT",
   "TTggggggggggg..gggggg*gggTTT",
   "TTggggggggggg..g*g*ggggggTTT",
   "TTg*ggggggggg..ggggggggggTTT",
   "TTTgTgggggg*g..ggggggggTg^TT",
   "TTTgggggggggg..gggggggg*TTTT",
   "TTTgggggggg*g..ggTgTggg^TTTT",
   "TTTTTTTTTTTTT..TTTTTTTTTT^TT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift_isles:7,3"
  },
  "marks": {
   "18,7": "lm_wild_hunt"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_isles",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "rift2",
    "x": 19,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift_africa": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTT^TTTTTTTT",
   "TTT^TggTTTgggTTgTTTgTTTTgTTT",
   "TTTgggggggggggggTgggggggggTT",
   "TTTgggggggggg..ggggGGGGGgg^T",
   "TTTgggggggggg..ggggGGGGGggTT",
   "TT^gggggggggg..gTgTGGGGTgTTT",
   "TTTgggggggg^^..ggggggggggTTT",
   "TTggggggggggg..gggΩg***ggTTT",
   "TTT*ggggggggg..ggggggggggTTT",
   "TTTggggggg!gg..ggggggggggTTT",
   "TTTgggggggggg..gggg*gggggTTT",
   "TTgggggGGGGGg..gggggggggggTT",
   "TTg.......................TT",
   "TTT.......................TT",
   "TTTgggggGGGGG..gggggggggggTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTgggggggggg..gggg*gggggTTT",
   "TTTgggg^^gggg..ggggggggggTTT",
   "TTTTgg^^ggTgg..ggggggggggTTT",
   "TT^TTggggg*gg..ggggggggggTTT",
   "TTTTggTgggggg..ggggggggggTTT",
   "TTTT*ggggTTgg..^TggggggggTTT",
   "TTTTTTTTTTTTT..TTTTgTTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift_africa:7,3"
  },
  "marks": {
   "18,7": "lm_aye_aye"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_africa",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "rift3",
    "x": 8,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift_neareast": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTgTTTTTTTgggTTTTTTTgTTTT",
   "TTggggg*gTTggggggggggggggTTT",
   "TTggggggggggg..*ggggggggTTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTggg*ggggg*g..ggggg*gggg^TT",
   "TTgggggggggGG..^ggggWWWggTTT",
   "TTgggggggg*GG..gggΩ*gggggTTT",
   "TTgggggggggGG..g^ggggggggTTT",
   "TTgggggggg!g^..GG*gggggggTTT",
   "TTTggTTgggggg..ggggggggggTTT",
   "TTTggggggggg^..^gggggggggTTT",
   "T^g.......................^T",
   "TTT.......................TT",
   "TTTgggTgggggg..ggTTggggTgTTT",
   "TTTgggggggggg..ggggggTgggTTT",
   "TTTTggggggggg..gggggggggTTTT",
   "TT^gggggggggg..gggggggggTTTT",
   "TTTggGGGggggg..ggggggggggTTT",
   "TT^ggGGGggggg..gggggggggTTTT",
   "TTTTgGGGggggg..ggggggggggTTT",
   "TTTTTgggTg^gg..ggggggggggTTT",
   "TTTTTT^TTTTTT..gTgggggggTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift_neareast:7,3"
  },
  "marks": {
   "18,7": "lm_hoopoe"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_neareast",
    "item": "coins",
    "n": 560
   }
  },
  "exits": {
   "13,23": {
    "map": "rift3",
    "x": 19,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift_eastasia": {
  "rows": [
   "TTTTTTTTT^TTTTTTTT^TTTTTTTTT",
   "TTTTTTTTTgTTTTTggTgTgTTTTTTT",
   "TTTggggggggggggggggggggggTTT",
   "TTggggggggggg..ggg*ggggggTTT",
   "TTTgggggggggg..TTggggggT*TTT",
   "TTggggggg^ggg..T*ggggggggTTT",
   "TTgggggg^gggg..*gTgggggTgTTT",
   "TTggggggggggg..gggΩggggggTTT",
   "TTggggggggggg..gTTgggggggTTT",
   "TTgTgggggg!gg..ggggggggg*TTT",
   "TTg*ggggggggg..ggggggggg^TTT",
   "TTTgggggggggg..gggggGGGggTTT",
   "TTT.......................TT",
   "TTT.......................TT",
   "TTTgTggggg^gg..ggggggggTgTTT",
   "TTT*ggggggggg..gggggggggg^TT",
   "TTTggggggWWWg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTgggGGGGGggg..Gg*gggggTgTTT",
   "T^gggGGGGGggg..G^^ggggggTTTT",
   "TT^ggGGGGGggg..GgggggggggTTT",
   "TTggggggggggg..gggggggggggTT",
   "TTTgTTT^TgTTT..TTTTTTggggTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift_eastasia:7,3"
  },
  "marks": {
   "18,7": "lm_tanuki"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_eastasia",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "rift4",
    "x": 13,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {},
  "gen": 15
 },
 "rift_oceania": {
  "rows": [
   "TTTTT^T^TT^TTTTTTTT^TTTTTTTT",
   "TTT^TggggggTgTTTTT^gggTgTTTT",
   "TTTggggggggggggggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..ggggg*ggggTTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..gggΩgg*ggg^TT",
   "TTTT*gggggggg..WGGGGggggggTT",
   "TTTTgggggg!gg..GGGGGgggggTTT",
   "TTTTggggggggg..GGGGG^ggggTTT",
   "TTTTGGGGggTTT..ggggg^ggggTTT",
   "TTT........................e",
   "TTT.........................",
   "TTTgggg*GGGGG..gggggggggTTTT",
   "TTTTggggGGGGG..gggggggggTTTT",
   "TTTgTggggTTT^..gg^^g*gggTTTT",
   "TTTgTgg*gggg^..gggggggggTTTT",
   "T^ggggggggggg..gggggggggTTTT",
   "TTTgggggggggg..gggggggTgTTTT",
   "TT^*ggggggggg..gggggggggTTTT",
   "TTTggTggggTgg..gg*ggggggTTTT",
   "TTTTTTTTTTTTTTTTTTTT^TTTTTTT",
   "TT^TTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift_oceania:7,3"
  },
  "marks": {
   "18,7": "lm_wayfinding"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_oceania",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {
   "27,12": {
    "map": "rift5",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   26,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift_arctic": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTT^TT",
   "TTTTTTgTTTTTgTgggg^TTTTTTTTT",
   "TTTTgggggggggggggg*gggggTTTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggg*g..ggggggggggTTT",
   "TTTTgg*gggggg..*gTggTggggTTT",
   "TTTTgggg!gggg..gggΩgggggggTT",
   "TTTTgggGGGGGg..ggggTggggggTT",
   "TTTTggWWWGGGg..g*gggggggggTT",
   "TTTTgTgGGGGGg..ggggggggggTTT",
   "TTTTggggggggg..gggggggggggTT",
   "TTT........................e",
   "TTT.........................",
   "TTTTgg*gGGGg^..ggggTgggggTTT",
   "TTTTgTg*GGGg^..gggggggggTTTT",
   "TTT*ggggGGGGG..^^TggggggTTTT",
   "TTTgggggGGGGG..gggTgggggTTTT",
   "TTTgggggGGGGG..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTTgTggggggTg..ggggggTgggTTT",
   "TTTTTTTT^^TTTT^TgggT^TTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "8,7": "rift_arctic:7,3"
  },
  "marks": {
   "18,7": "lm_greenland_shark"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_arctic",
    "item": "antidote",
    "n": 1
   }
  },
  "exits": {
   "27,12": {
    "map": "rift6",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   26,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift_americas": {
  "rows": [
   "TTTT^^TT^TTTTTTTTTTTTTTTTTTT",
   "TTTgggggggTTTgggTTgTggTTTTTT",
   "TTgggggggggggggggg*ggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..ggggggggTgTTT",
   "TTTgggggggggg..ggg*ggggggTTT",
   "TTTggggggggTg..gggg*gggTgTTT",
   "TTTg^ggg*ggTT..gggΩgggTg^TTT",
   "TTTgggggggggg..g^gggTggg^TTT",
   "TTTT^ggggg!gg..g^gggTggggTTT",
   "TTTTgT*gggGGG..ggggggTgggTTT",
   "TT^gggggggGGG..ggGGGGGgggTTT",
   "e.........................TT",
   "..........................^T",
   "TTTgTggggggg*..gg^^ggggTgTTT",
   "TTTGGGGGggggg..ggggggggggTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgggggggggg..WWggggggTgTTT",
   "TTTgggggggggg..ggggggggTgTTT",
   "TTTggggggggg*..ggggggggTgTTT",
   "TTggggggggggg..gggggggggg^TT",
   "TTTTgTgggTggg..gggg*ggggTTTT",
   "TTTTTTTTTTTTgTTTTTTTggTTT^TT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "rift_americas:7,3"
  },
  "marks": {
   "18,7": "lm_potoo"
  },
  "finds": {
   "4,3": {
    "id": "rift_s_americas",
    "item": "coins",
    "n": 580
   }
  },
  "exits": {
   "0,12": {
    "map": "rift6",
    "x": 26,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   1,
   12
  ],
  "links": {},
  "gen": 15
 },
 "rift6": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggg*g^TT",
   "TT^gggggggggg..ggggggggggTTT",
   "TTTg*gggggggg..ggggggggTgTTT",
   "TTTgTgggggggg..^gg^ggggTgTTT",
   "TTTgggggggggg..g^gggggggg^TT",
   "TT^gggggggggg..gggΩ^gggggTTT",
   "TTTgTggggg!gg..ggggggggggTTT",
   "TTTgggggggggg..gggggggTgTTTT",
   "TTTTggggggggg..gggggggg**TTT",
   "TTTgggggggggg..gggg^^gggTTTT",
   "e..........................e",
   "............................",
   "TT^gGGGGGgggg..¦Tggggggg^TTT",
   "TTTgggGGGgggT..gRggTGGTGTTTT",
   "TTTgggGGGgggT..TgTggggggTTTT",
   "TTTgggggggggg..gggggg*gTgTTT",
   "TTTggggggg*gg..ggggggggggTTT",
   "TTT*Tgggggggg..ggggggggggTTT",
   "TT^gggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gg*ggTggggTTT",
   "TTTTTggTTTTTT..TgTTTTTTTTTTT",
   "TT^TTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,8": "rift6:8,2",
   "16,15": "rift6:9,5"
  },
  "marks": {
   "18,7": "lm_mothman_crane"
  },
  "finds": {
   "4,21": {
    "id": "rift_r6",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "mythhub",
    "x": 19,
    "y": 1
   },
   "0,12": {
    "map": "rift_arctic",
    "x": 26,
    "y": 12
   },
   "27,12": {
    "map": "rift_americas",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {
   "n": {
    "map": "rift7",
    "off": 0
   }
  },
  "gen": 15
 },
 "rift7": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggg^TT",
   "TTggggggggggg..gggggggggTTTT",
   "T^ggggggggggg..gggggggggTTTT",
   "TTgggggggg*gg..ggggggggTgTTT",
   "T^ggggggggggg..gggggggggg^TT",
   "TT^gggg^g^ggg..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTggggggg!gg..^ggΩgTggggTTT",
   "TTggggggggggg..^ggTggTg*gTTT",
   "TTTgg*ggggggg..*^ggggggggTTT",
   "TTTgggggggggg..T*ggggggggTTT",
   "TTTg*ggggggWW..^gggGGGgggTTT",
   "TTTggggggGGGG..ggggggggggTTT",
   "TTTgggggggggg..gRggggggggTTT",
   "TTTgggggggggg..gTTggggg*TTTT",
   "TTTgggggggggg..gggggggggg^TT",
   "TTTggggRggggg..ggggggggggTTT",
   "TTTgggGGGgggg..ggggggggggTTT",
   "TTTgggGGGgggg..ggggggggggTTT",
   "TTTTggGGGgggg..g*gggggggggTT",
   "TTTTggggggggg..gggggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "10,8": "rift7:8,2",
   "16,14": "rift7:13,3",
   "7,17": "rift7:1,8"
  },
  "marks": {
   "18,8": "lm_drongo"
  },
  "finds": {
   "23,2": {
    "id": "rift_r7",
    "item": "coins",
    "n": 600
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "rift6",
    "off": 0
   },
   "n": {
    "map": "rift8",
    "off": 0
   }
  },
  "gen": 15
 },
 "rift8": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TT^gggggggggg..gg*gggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTggggggggg^g..ggggggggTgTTT",
   "TTTg**ggg!g^g..ggggggTgggTTT",
   "TTTgggggggWWW..gggΩggggggTTT",
   "TTTgggggTgggg..gggggTTgggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTg*gTTggggg..*gggggggggTTT",
   "TTggggggggggg..ggggggGGGgTTT",
   "TTggggggggggg..ggggggGGGgTTT",
   "TTggggggggggg..GgggggGGG^TTT",
   "TTTgggggggggg..ggRgggggg^TTT",
   "TTTTggggggggg..g*ggggggggTTT",
   "TTTgggggggggg..ggggggggg^TTT",
   "TTTggg^gggg^g..ggggGGGggTTTT",
   "TT^gggggg^ggg..*ggg*gggTgTTT",
   "TTTggg^gggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "9,7": "rift8:7,3",
   "17,15": "rift8:7,5"
  },
  "marks": {
   "18,8": "lm_lungfish"
  },
  "finds": {
   "4,3": {
    "id": "rift_r8",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "rift7",
    "off": 0
   },
   "n": {
    "map": "rift9",
    "off": 0
   }
  },
  "gen": 15
 },
 "rift9": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTggggggggggg..gggggggggggTT",
   "TTT*ggggggggg..gggggggggggTT",
   "TTTgggggg^ggg..gggggggggggTT",
   "TTTgGGGggg^gg..gggg*gggggTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTggggggg!gg..g^^ΩggggggTTT",
   "TTT*ggggggggg..ggggggggggTTT",
   "TTTgTgggggg*g..GGGGggggggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggGGGGG^TT",
   "TTTgggggggggg..gggggGGGTGTTT",
   "TTTTggg*ggggg..WWWggGGGGGgTT",
   "TTTggg*gggggg..ggRg*gggTgTTT",
   "TTTgTg^gggggg..gggggTggggTTT",
   "TTTgggggggggg..gTggTgggggTTT",
   "TTTg^gggggggg..ggggggTgggTTT",
   "TTTgggggggggg..ggTggggggTTTT",
   "TTTTggggggg*g..ggTggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "10,8": "rift9:8,2",
   "17,15": "rift9:13,6"
  },
  "marks": {
   "18,8": "lm_olm"
  },
  "finds": {
   "24,21": {
    "id": "rift_r9",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "rift8",
    "off": 0
   },
   "n": {
    "map": "rift10",
    "off": 0
   }
  },
  "gen": 15
 },
 "rift10": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTgTTTTgTTggTTTTggTggggTTT",
   "TTTgggggg*gggggggggggggggTTT",
   "TTggggggggggggggggg^gggTg^TT",
   "TTgggg*gggggggggggggg^ggTTTT",
   "TT^gGGGggggggggggggggggg^TTT",
   "TTTgGGGggggggg^gggggggggTTTT",
   "TTTgGGGgggggggg^GGΩgggggTTTT",
   "TTTggggggg!ggggggggggGGGgTTT",
   "TTTggggggg^^gggggggggGGGgTTT",
   "TTTggggggggggggg*ggggGGTgTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggTTg..ggggggggTgTTT",
   "TTggggggggggg..gggggggTggTTT",
   "TTggggggggggg..ggggggTggg^TT",
   "TTTgggggggggg..ggggg*ggggTTT",
   "TTTgggggggTWW..gggg*ggggg^TT",
   "TTTgggggg*ggg..ggggggggggTTT",
   "TTTgTgggggggg..ggggggggTgTTT",
   "TTTgggggggggg..gggg*gggggTTT",
   "TTTgggggggggg..ggggg*ggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "10,9": "rift10:7,3"
  },
  "marks": {
   "18,8": "lm_first_painting"
  },
  "finds": {
   "4,21": {
    "id": "rift_r10",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "rift9",
    "off": 0
   }
  },
  "gen": 15
 }
}, inbound: [
 {
  "from": "summit",
  "tile": "7,0",
  "map": "mythhub",
  "x": 13,
  "y": 22
 }
] });
