// GENERATED by design/tools/forge_wetland.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "wetland", maps: {
 "route2": {
  "rows": [
   "TTgggggggggg..gggggggggggTTT",
   "TTgggggggggg..gggggggggggTTT",
   "TTg*ggg*gggg..gggggggggggTTT",
   "TTgggggggggg..*ggg⁅ggggggTTT",
   "TTggGGGGGggg..ggTgggggggTTTT",
   "TTggGGGGGggg..ggTggWWWWWTTTT",
   "TTgTGGGGGggg..ggTgWWWWWWWTTT",
   "TTgggggggggg..ggggWWWWWWWTTT",
   "TTggTggggggg..ggggWWWWWWWgTT",
   "TTggggRgggg*..gggggWWWWWggTT",
   "TTT!gggggggg..gggggggg*gggTT",
   "e.............ggggggΩggggTTT",
   "T.............gggggggggRgTTT",
   "TTgggg*ggggg..gg¡gggg*gggTTT",
   "TTggggGGGggg..*ggggggggggTTT",
   "TTgggggggggg...gggGGGGGggTTT",
   "TTT*ggggRg*g...ggGGGGGGTgTTT",
   "TTTgWWWgggggg..ggGGGGGGGgTTT",
   "TTTgWWWg*gggg..ggGGGGGGGgTTT",
   "TTTgWWW*g⁂ggg..gggGGGGGgTTTT",
   "TTTgggggggggg..ggTggggTTTTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "3,10": "route2:gate",
   "6,9": "route2:3,1",
   "23,12": "route2:4,4",
   "8,16": "route2:11,10"
  },
  "marks": {
   "20,11": "lm_beaver_dam"
  },
  "finds": {
   "24,3": {
    "id": "wet_r2_pond",
    "item": "berries",
    "n": 3
   },
   "3,20": {
    "id": "wet_r2_mere",
    "item": "coins",
    "n": 90
   }
  },
  "exits": {
   "0,11": {
    "map": "thicket",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   13,
   20
  ],
  "links": {
   "n": {
    "map": "seg_w1",
    "off": 0
   },
   "s": {
    "map": "town2",
    "off": 0
   }
  },
  "gen": 3
 },
 "seg_w1": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..gggggggggTTT",
   "TTTgGGGGGggggg..gggGGGggggTT",
   "TTTgGGGGGggggg..g*ggggg*TgTT",
   "TTTgGGGGGggggg..gggggggRTgTT",
   "TTgggggggg*ggg..ggggggggggTT",
   "TTgg⁂gggg⁅gggg..gggTTTgggTTT",
   "TTTggggggggg....ggRggg*gggTT",
   "TTgggWWWgggg....WgWgWgggWgTT",
   "WWWWWWWWWWWW..WWWWWWWWWWWWWW",
   "WWWWWWWWWWWW..WWWWWWWWWWWWWW",
   "WWWWWWWWWWWW..WWWWWWWWWWWWWW",
   "TTTWgg*ggggg..gggggWggggTWWT",
   "TTTgggggΩggg..ggggggggggggTT",
   "TTTgTTTgggRg..gggg*ggTTTggTT",
   "TTT*Tggggggg..ggg¡ggg*ggggTT",
   "TTTggggggggg..ggggggggggggTT",
   "TTTggggggggg..ggGGGGGGggggTT",
   "TTTgggggRggg..ggGGGGGGGggTTT",
   "TTTgWWWggggg..gggGGGGGGg*TTT",
   "TTgggggggggg..ggggggggg*gTTT",
   "TTgggggggggg..gggggggggggTTT",
   "TTgggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "18,8": "seg_w1:6,3",
   "10,15": "seg_w1:6,8",
   "8,19": "seg_w1:3,10",
   "23,5": "seg_w1:11,10"
  },
  "marks": {
   "8,14": "lm_reed_warbler"
  },
  "finds": {
   "3,6": {
    "id": "wet_w1_bank",
    "item": "wakeberry",
    "n": 1
   },
   "24,20": {
    "id": "wet_w1_grass",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   20
  ],
  "links": {
   "s": {
    "map": "route2",
    "off": 0
   },
   "n": {
    "map": "seg_w2",
    "off": 0
   }
  },
  "gen": 3
 },
 "seg_w2": {
  "rows": [
   "TTggggggggg..gggggggggggggTT",
   "TTggggggggg..gggggggggggggTT",
   "Tgggggggggg..ggggggggggggggT",
   "Tgggggggggg..g*ggGGGggggRggT",
   "TTggg.Ω.ggg..gggggggggggggTT",
   "TTTggg*gggg..ggggRgWWWWWggTT",
   "TTTgggg*⁌gg..gggggWWWWWWWgTT",
   "TTg!ggggggg..gggggWWWWWWWgTT",
   "e............gggggWWWWWWWgTT",
   "T............ggggggWWWWWTgTT",
   "TTTgggggggg..gggTgggggggTgTT",
   "TTggRgggg⁅g..ggg*ggg¡ggggggT",
   "TTgggGGGggg..gggggg*gggggggT",
   "TTggggggWWW..WWWWWWWWgggTgTT",
   "TTgggggWWWW..WWWWWWWWWggTgTT",
   "TTTgggWWWWW.....WWWWWWWggTTT",
   "TTTgggWWWWW.....WWWWWWWggTTT",
   "TTTgTggggWWWWW..WWWWgggggTTT",
   "TTTggg*ggggggg..ggggggggggTT",
   "TTTg*ggggggggg..gggggggTgTTT",
   "TTTgGGGGGgg*gg..ggRggggggTTT",
   "TTTgggggRggggg..*ggGGGGGgTTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "3,7": "seg_w2:gate",
   "17,5": "seg_w2:6,1",
   "8,21": "seg_w2:3,3",
   "4,11": "seg_w2:1,5",
   "18,20": "seg_w2:13,5",
   "24,3": "seg_w2:4,10"
  },
  "marks": {
   "6,4": "lm_peat_bank"
  },
  "finds": {
   "8,3": {
    "id": "wet_w2_peat",
    "item": "antidote",
    "n": 1
   },
   "24,11": {
    "id": "wet_w2_isle",
    "item": "coins",
    "n": 110
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_cetarch",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_w1",
    "off": 0
   },
   "n": {
    "map": "seg_w3",
    "off": 0
   }
  },
  "gen": 3
 },
 "seg_w3": {
  "rows": [
   "TTggggggggggg..ggggggggggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTggggggggggg..ggTgggGGGgTTT",
   "TTgggRggg*ggg..*gggggggggTTT",
   "TTgTGGGGggggg..gggggggggggTT",
   "TTggGGGGGgggg..ggggWWWWWWWWW",
   "TTggGGGGG*ggg..⁂gggWWWWWWWWW",
   "TTggGGGGGgg*g..g*ggWW*ggggTT",
   "TTgTGGGGggggg..ggΩgWWggRgTTT",
   "TTggggggggggg..g*ggWWggggTTT",
   "TTggggggRgggg..ggggWWgGGGTTT",
   "TTTg¡gggggg....gRg⁂WWgGGGTTT",
   "TTggggggggg....ggggWWgGGGgTT",
   "TTggWWWgggg..ggggggWWgggTgTT",
   "TTgWWWWWWWW..WWWWWWWWggggTTT",
   "TTgWWWWWWWW..WWWWWWWWggggTTT",
   "TTTgggggggg..gggggggggggggTT",
   "TTTgggggggg..ggggggggggTTTTT",
   "TTTgggggRg*..GGGGGGggg*TTTTT",
   "TTTggggTggg..GGGGGGGgg*TTTTT",
   "TTggggggggg..gGGGGGGggggggTT",
   "TTggggggggg..gggggggggggggTT",
   "TTggggggggg..gggggggggggggTT"
  ],
  "cast": {
   "8,11": "seg_w3:3,2",
   "5,4": "seg_w3:5,4",
   "16,12": "seg_w3:7,4",
   "23,9": "seg_w3:9,4",
   "8,19": "seg_w3:5,7"
  },
  "marks": {
   "17,9": "lm_otter_holt"
  },
  "finds": {
   "24,15": {
    "id": "wet_w3_bend",
    "item": "bigberries",
    "n": 1
   },
   "4,19": {
    "id": "wet_w3_pool",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   20
  ],
  "links": {
   "s": {
    "map": "seg_w2",
    "off": 0
   },
   "n": {
    "map": "seg_w4",
    "off": 0
   }
  },
  "gen": 3
 },
 "seg_w4": {
  "rows": [
   "TTTgggggggggg..gggggggggggTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTggGGGGGg*g..ggggggggTggTT",
   "TTTTggggggggg..gggRggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "WWWWWWWWWWggg..g*gWWWWWWWWWW",
   "TTTgTgggggggg..gggggg*g*ggTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTgggRg*ggggg....ggGGGGGggTT",
   "TTgggWWWWWggg....ggGGGGGggTT",
   "TTgggWWWWWggggg..ggGGGGGggTT",
   "TTgTgWWWWWggggg..⁂ggggggggTT",
   "TTTgg*ggggΩgggg..*ggRgg**gTT",
   "TTggggggggggggg..g*gggggTgTT",
   "TTggTgggRgggggg..ggWWWWWggTT",
   "TTTgggggg*ggggg..ggWWWWWggTT",
   "TTg*ggggggggg....ggWWWWWTgTT",
   "TTggGGGGGgggg....g*ggggggTTT",
   "TTggGGGGGgggg..ggg**gggggTTT",
   "TTggGGGGGgggg..ggg⁅ggggggTTT",
   "TTgggggggg¡gg..gg*gggggg*TTT",
   "TTTgggggggggg..gggggGGGggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTggggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "18,3": "seg_w4:9,1",
   "8,14": "seg_w4:3,4",
   "5,8": "seg_w4:4,4",
   "20,12": "seg_w4:11,4"
  },
  "marks": {
   "10,12": "lm_lotus"
  },
  "finds": {
   "4,11": {
    "id": "wet_w4_lotus",
    "item": "berries",
    "n": 2
   },
   "24,18": {
    "id": "wet_w4_channel",
    "item": "coins",
    "n": 120
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   20
  ],
  "links": {
   "s": {
    "map": "seg_w3",
    "off": 0
   },
   "n": {
    "map": "town3",
    "off": 0
   }
  },
  "gen": 3
 },
 "town3": {
  "rows": [
   "TTTTTTTTTTTTTnTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTT.TTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTTgggggggggg..!ggggggggTTTT",
   "TTTgHgggggg!g..ggggggggggTTT",
   "TTgggg...Y........C...gHgTTT",
   "TTTgTΩ................gggTTT",
   "TTTggg....Ω.....Ω.....gggTTT",
   "TTgggg¦..............¦gggTTT",
   "TTgggΩgggggg¦..ggggΩggΩggTTT",
   "TTggggggΩgggg..gΩgRggggggTTT",
   "WWWWWWWWWWWWW..WWWWWWWWWWWWW",
   "WWWWWWWWWWWWW..WWWWWWWWWWWWW",
   "TTTgTgΩgggggg..¦ggggΩggTTTTT",
   "TTTgggggg*ggg..ggggggg*gTTTT",
   "TTTgggg¦............¦ggggTTT",
   "TTTgHgg...Ω......Ω...g*ggTTT",
   "TTTT*g*.M............*gHgTTT",
   "TTTTggg....Ω......Ω..ggggTTT",
   "TTTTggggggggg..gggg**ggggTTT",
   "TTTTTTVg*gggg..!gggggggggTTT",
   "TTTgggggggggg..gggggggHg*gTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTgggggggggg..gggggggggggTT"
  ],
  "cast": {
   "15,3": "town3:gate",
   "11,4": "town3:11,12",
   "15,20": "town3:11,3",
   "18,10": "town3:16,7",
   "6,20": "town3:9,10"
  },
  "marks": {
   "16,10": "lm_flood_post",
   "10,16": "decor:stall",
   "17,16": "decor:stall",
   "11,18": "decor:stall",
   "19,9": "decor:canoe",
   "8,10": "decor:canoe",
   "20,13": "decor:canoe",
   "5,9": "decor:nets",
   "22,9": "decor:nets",
   "6,13": "decor:nets",
   "16,7": "decor:bench",
   "10,7": "decor:bench",
   "18,18": "decor:crates",
   "5,6": "decor:crates"
  },
  "finds": {
   "23,14": {
    "id": "wet_t3_bank",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "13,0": {
    "map": "route3",
    "x": 7,
    "y": 14
   }
  },
  "beyond": {
   "e": "W",
   "w": "W"
  },
  "land": [
   14,
   20
  ],
  "links": {
   "s": {
    "map": "seg_w4",
    "off": 0
   }
  },
  "gen": 3
 }
}, inbound: [
 {
  "from": "thicket",
  "tile": "7,9",
  "map": "route2",
  "x": 1,
  "y": 11
 },
 {
  "from": "shrine_cetarch",
  "tile": "7,9",
  "map": "seg_w2",
  "x": 1,
  "y": 8
 },
 {
  "from": "route3",
  "tile": "7,15",
  "map": "town3",
  "x": 13,
  "y": 1
 }
] });
