// ---------- CHAPTER X — Part 13: THE VIGIL ----------
// Animals lost in the last ~10,000 years, and animals still here by a thread.
// Everything in this region is real. Nothing here is invented. That is the point.
//
// Field Guide status tags:  † = extinct   EW = extinct in the wild
//                           CR = critically endangered   ← = brought back

Object.assign(PALS, {
  vigilz: { ground: "#3a3f4c", grass: "#4a5060", grass2: "#545c6e", tree: { bg: "#2a2e38", em: "🕯️" }, mount: { bg: "#343a46", em: "🪦" }, water: "#3c5c7a", flower: "🕯️" },
  hopez: { ground: "#3c5c4c", grass: "#4c7a5c", grass2: "#568a68", tree: { bg: "#2a4436", em: "🌱" }, mount: { bg: "#3c5c4c", em: "🪨" }, water: "#4a9ac9", flower: "🌿" },
});
Object.assign(ARENA, { vigilz: "linear-gradient(#4a5060,#2a2e38)", hopez: "linear-gradient(#4c7a5c,#2a4436)" });

// ---- sprites (built on the generators from parts 8 & 9) ----
Object.assign(ART, {
  // — extinct mammals —
  thylacine: canArt({ fur: "#c9a878", inner: "#a8875c", muzzle: "#d9c4a3", iris: "#3a2e22", line: "#5c4030", spots: true, markC: "#4c3826" }),
  quagga: ungA({ coat: "#a3683c", stripes: true, markC: "#3c2a1e", mane: true, maneC: "#3c2a1e", muzzle: "#4c3c30", iris: "#3a2e22" }),
  aurochs: bovA({ coat: "#3a2f26", horns: true, longHorn: true, hornC: "#c9bca8", iris: "#3a2a18" }),
  stellerseacow: cetA({ hide: "#5c5448", belly: "#8a8578", melon: true, melonC: "#5c5448", fluke: "#4c4438", iris: "#3c3226" }),
  irishelk: ungA({ coat: "#a3855c", antler: true, hornC: "#c9b08a", mane: true, maneC: "#6b5442", muzzle: "#5c4c3c", iris: "#3a2e22" }),
  woollyrhino: rhinoA({ hide: "#8a7458", bigHorn: true, twoHorn: true, hair: true, hairC: "#5c4a34", iris: "#3a2a18" }),
  direwolf: canArt({ fur: "#8a8578", inner: "#5c5850", muzzle: "#a8a396", iris: "#c9a43a" }),
  smilodon: felArt({ fur: "#c9a05c", inner: "#a3783c", muzzle: "#e8d4b5", iris: "#c9853a", ruff: true, ruffC: "#a3783c", tufts: true }),
  megatherium: xenA({ fur: "#8a6f52", snout: false, iris: "#3a2e22", muzzle: "#c9a878" }),
  glyptodon: xenA({ fur: "#7a7468", shell: true, plateC: "#5c5850", iris: "#3a2e22" }),
  mastodon: elephA({ hide: "#6b5442", hair: true, hairC: "#8a6f52", tusks: true, longTusk: true, iris: "#5c4436" }),
  columbianmammoth: elephA({ hide: "#a3855c", hair: true, hairC: "#c9a878", tusks: true, longTusk: true, bigEar: true, iris: "#5c4436" }),
  cavelion: felArt({ fur: "#d9c9a3", inner: "#b5a078", muzzle: "#f2ede0", iris: "#c9a43a", ruff: true, ruffC: "#c9b08a" }),
  shortfacedbear: bearA({ fur: "#7a5c44", inner: "#5c4030", muzzle: "#c9a878", iris: "#3a2e22" }),
  giantbeaver: rodA({ fur: "#6b4c34", inner: "#4c3424", muzzle: "#a3856b", iris: "#2a2018", earRound: true }),
  steppebison: bovA({ coat: "#6b5240", hump: true, shag: true, horns: true, longHorn: true, hornC: "#4a423a", iris: "#3a2a18" }),
  baiji: cetA({ hide: "#a8b0b5", belly: "#dce4ec", melon: true, melonC: "#b5bcc0", rostrum: "#a8b0b5", iris: "#26221c" }),
  caribbeanmonkseal: pinA({ fur: "#7a7568", head: "#8a8578", muzzle: "#a8a396", iris: "#26221c" }),
  japanesewolf: canArt({ fur: "#a3906b", inner: "#7a6848", muzzle: "#c9b490", iris: "#8a5c2a" }),
  falklandwolf: canArt({ fur: "#c9853a", inner: "#a3622a", muzzle: "#f2ede0", iris: "#c9a43a" }),
  balitiger: felArt({ fur: "#d9853a", inner: "#a35c2a", muzzle: "#f8f4ea", iris: "#c9a43a", stripes: true, markC: "#26221c" }),
  javantiger: felArt({ fur: "#c9702a", inner: "#8a4c1e", muzzle: "#f2ede0", iris: "#c9a43a", stripes: true, markC: "#26221c" }),
  caspiantiger: felArt({ fur: "#e8a53a", inner: "#b5762a", muzzle: "#f8f4ea", iris: "#c9a43a", stripes: true, markC: "#3c2a1e" }),
  seamink: mustA({ fur: "#4c3428", inner: "#3a2620", muzzle: "#6b5040", iris: "#2a2018" }),
  bluebuck: ungA({ coat: "#5c6b7a", spiral: true, hornC: "#3c3226", muzzle: "#4c5460", iris: "#3a2e22" }),
  schomburgksdeer: ungA({ coat: "#8a6142", antler: true, hornC: "#c9b08a", muzzle: "#5c4030", iris: "#3a2e22" }),
  toolachewallaby: marsA({ fur: "#a8a08a", inner: "#c9c0a8", muzzle: "#d9d0b8", iris: "#3a2e22", stripes: true, markC: "#6b6858" }),
  desertratkangaroo: marsA({ fur: "#d9b884", inner: "#e8cfa5", muzzle: "#f2ede0", iris: "#3a2e22" }),
  pigfootedbandicoot: marsA({ fur: "#c9a878", inner: "#e8c9a5", muzzle: "#e8dcc3", iris: "#3a2e22" }),
  lesserbilby: marsA({ fur: "#c9bda3", inner: "#e8c9c9", muzzle: "#e0d5bd", iris: "#3a2e22" }),
  bramblecaymelomys: rodA({ fur: "#8a6f52", inner: "#6b5238", muzzle: "#c9a878", iris: "#2a2018" }),
  pyreneanibex: ungA({ coat: "#a8907a", curved: true, hornC: "#5c4436", muzzle: "#d9c9b5", iris: "#3a2e22" }),
  // — extinct birds —
  dodo: birdA({ body: "#8a8578", wingC: "#6b6858", head: "#a8a396", bill: "hook", beakC: "#c9b08a", iris: "#3c3226" }),
  greatauk: pengA({ body: "#26221c", wingC: "#16140f", bib: "#f5f2e8", mask: "#f5f2e8", bill: "long", beakC: "#26221c" }),
  passengerpigeon: songA({ body: "#5c6b8a", wingC: "#48566b", head: "#5c6b8a", bib: "#c9704a", beakC: "#26221c", iris: "#c94a3a" }),
  carolinaparakeet: parrA({ body: "#4c9a3c", wingC: "#3a7a2c", head: "#e8c547", cheek: true, cheekC: "#e8853a", beakC: "#e8dcc3" }),
  moa: birdA({ longLegs: true, body: "#6b5c4c", wingC: "#5c4c3c", neck: true, neckC: "#6b5c4c", head: "#8a7458", bill: "cone", beakC: "#c9b08a", iris: "#3c3226" }),
  haastseagle: rapA({ body: "#8a6f52", wingC: "#5c4436", head: "#c9b08a", tufts: true, beakC: "#3c3630", iris: "#e8c547" }),
  elephantbird: birdA({ longLegs: true, body: "#5c5448", wingC: "#4c4438", neck: true, neckC: "#5c5448", head: "#6b6358", bill: "cone", beakC: "#a8a08a" }),
  huia: songA({ body: "#26221c", wingC: "#16140f", bill: "long", beakC: "#e8c547", wattleC: "#e8853a", iris: "#3c3226" }),
  labradorduck: waterA({ body: "#f2ede0", wingC: "#26221c", head: "#f5f2e8", mask: "#26221c", neck: true, neckC: "#f2ede0", bill: "long", beakC: "#5c6b7a" }),
  heathhen: fowlA({ body: "#8a7458", wingC: "#6b5844", head: "#a3906b", bib: "#e8a53a", beakC: "#5c5448" }),
  imperialwoodpecker: songA({ body: "#26221c", wingC: "#f5f2e8", head: "#c94a3a", plume: true, plumeC: "#c94a3a", bill: "long", beakC: "#e8dcc3" }),
  kauaioo: songA({ body: "#26292e", wingC: "#16181c", head: "#26292e", bib: "#e8c547", bill: "long", beakC: "#16140f", iris: "#8a8578" }),
  poouli: songA({ body: "#8a7458", wingC: "#6b5844", head: "#3c3630", mask: "#26221c", bill: "cone", beakC: "#5c5448" }),
  laysanhoneycreeper: songA({ body: "#c94a3a", wingC: "#8a3428", head: "#c94a3a", bill: "long", beakC: "#3c3630" }),
  // — extinct small things —
  xercesblue: flutA({ wingC: "#6b8ad9", veins: true, veinC: "#3c5490", body: "#4c5c7a", eyeSpots: true, spotC: "#f2ede0" }),
  rockymountainlocust: insA({ body: "#8a7a4c", head: "#6b5c38", longWings: true, wingC: "#d9d4b5", legC: "#8a7a4c" }),
  goldentoad: frogA({ skin: "#e8853a", belly: "#e8a53a", iris: "#26221c", toes: true, toeC: "#e8853a" }),
  splendidpoisonfrog: frogA({ skin: "#c94a3a", belly: "#8a3428", iris: "#26221c", toes: true, toeC: "#c94a3a" }),
  chinesepaddlefish: fishA({ body: "#8a9099", bill: true, finC: "#6b7078", bigEye: true }),
  xmasislandpipistrelle: WA(ART.bat, {}),
  // — extinct in the wild —
  alala: songA({ body: "#3c3630", wingC: "#26221c", head: "#3c3630", bill: "hook", beakC: "#26221c", iris: "#5c4c3c" }),
  spixsmacaw: parrA({ body: "#6b8ad9", wingC: "#4c6bb5", head: "#a8c4e8", face: "#5c6b84", longTail: true, tailC: "#4c6bb5", beakC: "#26221c" }),
  peredavidsdeer: ungA({ coat: "#a3785c", antler: true, hornC: "#c9b08a", muzzle: "#c9bda3", iris: "#3a2e22" }),
  scimitaroryx: ungA({ coat: "#f2ede0", curved: true, hornC: "#3c3226", blaze: "#c9704a", muzzle: "#e8dcc3", iris: "#3a2e22" }),
  southchinatiger: felArt({ fur: "#e8953a", inner: "#b56a2a", muzzle: "#f8f4ea", iris: "#c9a43a", stripes: true, markC: "#26221c" }),
  guamkingfisher: songA({ body: "#c9853a", wingC: "#3a7ad9", head: "#c9622a", bill: "long", beakC: "#3c3630" }),
  socorrodove: songA({ body: "#a3785c", wingC: "#8a6142", head: "#c9a888", bill: "cone", beakC: "#3c3630", iris: "#c94a3a" }),
  wyomingtoad: frogA({ skin: "#8a7458", belly: "#c9bda3", spots: true, markC: "#4c4038", iris: "#c9a43a", toes: true, toeC: "#8a7458" }),
  partulasnail: snailA({ shell: "#c9a878", body: "#d9c9b8", bandC: "#8a6a4a" }),
  // — critically endangered —
  northernwhiterhino: rhinoA({ hide: "#9a978a", bigHorn: true, twoHorn: true, folds: true, iris: "#3a2a18" }),
  javanrhino: rhinoA({ hide: "#7a756a", folds: true, hookLip: true, iris: "#3a2a18" }),
  sumatranrhino: rhinoA({ hide: "#6b5a4a", twoHorn: true, hair: true, hairC: "#4a3c30", hookLip: true, iris: "#3a2a18" }),
  amurleopard: felArt({ fur: "#e8d4a5", inner: "#c9a878", muzzle: "#f8f4ea", iris: "#8fb35c", rosettes: true, markC: "#3c3226" }),
  saola: ungA({ coat: "#5c4436", straight: true, hornC: "#3c3226", blaze: "#f2ede0", muzzle: "#f2ede0", iris: "#3a2e22" }),
  hainangibbon: primA({ fur: "#26221c", face: "#3c3630", crest: true, crestC: "#26221c", ruff: true, ruffC: "#8a6f42", iris: "#5c4436" }),
  crossrivergorilla: primA({ fur: "#3c3630", face: "#26221e", crest: true, crestC: "#2a2620", brow: true, browC: "#26221e", iris: "#5c4436" }),
  tapanuliorangutan: primA({ fur: "#c9622a", face: "#8a5c3c", ruff: true, ruffC: "#a34a1e", iris: "#5c3a22" }),
  sumatranorangutan: primA({ fur: "#d9703a", face: "#8a5c3c", ruff: true, ruffC: "#b5562a", iris: "#5c3a22" }),
  redwolf: canArt({ fur: "#c97a4a", inner: "#a3562a", muzzle: "#e8dcc3", iris: "#c9853a" }),
  whoopingcrane: birdA({ longLegs: true, body: "#f8f4ea", wingC: "#e8e4d8", head: "#f8f4ea", neck: true, neckC: "#f8f4ea", mask: "#c94a3a", bill: "long", beakC: "#c9b08a" }),
  californiacondor: rapA({ body: "#26221c", wingC: "#16140f", head: "#e8853a", ruff: true, ruffC: "#3c3630", beakC: "#e8dcc3", wattle: true, wattleC: "#e8a53a" }),
  przewalskishorse: ungA({ coat: "#c9a05c", mane: true, maneC: "#3c3226", muzzle: "#e8dcc3", iris: "#3a2e22" }),
  yangtzesofttshell: armorA({ hide: "#5c6b5c", scutes: true, scuteC: "#4c5848", beakC: "#8a9a8a", iris: "#3c3226" }),
  chinesegiantsalamander: salA({ skin: "#5c5a48", belly: "#8a8670", warts: true, spots: true, markC: "#3a3828", finTail: true, iris: "#26221c" }),
  finlessporpoise: cetA({ hide: "#8a9099", belly: "#c9cdd4", melon: true, melonC: "#99a0a8", iris: "#26221c" }),
  angelshark: sharkA({ hide: "#a8906b", belly: "#d9cfc0", spots: true, markC: "#6b5844" }),
  kempsridley: armorA({ hide: "#5c7a6b", scutes: true, scuteC: "#4a6354", beakC: "#c9b98a", iris: "#3c3226" }),
  vancouvermarmot: rodA({ fur: "#4c3c30", inner: "#3a2c22", muzzle: "#e8dcc3", iris: "#2a2018" }),
  regenthoneyeater: songA({ body: "#e8d44a", wingC: "#26221c", head: "#26221c", mask: "#3c3630", bill: "long", beakC: "#26221c" }),
  orangebelliedparrot: parrA({ body: "#4c9a3c", wingC: "#3a5cd9", head: "#5cb54c", cheek: true, cheekC: "#e8853a", beakC: "#8a8578" }),
  sumatrantiger: felArt({ fur: "#c9702a", inner: "#8a4c1e", muzzle: "#f2ede0", iris: "#c9a43a", stripes: true, markC: "#26221c", ruff: true, ruffC: "#a3562a" }),
  hirola: ungA({ coat: "#c9a878", curved: true, hornC: "#3c3226", blaze: "#f2ede0", muzzle: "#e8dcc3", iris: "#3a2e22" }),
  damagazelle: ungA({ coat: "#f2ede0", curved: true, hornC: "#3c3226", patches: true, markC: "#a3562a", muzzle: "#f8f4ea", iris: "#3a2e22" }),
  rustypatchedbumblebee: beeA({ body: "#e8b83a", bandC: "#2e2a22", fuzzC: "#c96a3a", head: "#2e2a22", pollen: true, sting: true, iris: "#1a1614" }),
  franklinsbumblebee: beeA({ body: "#e8d44a", bandC: "#26221c", fuzzC: "#f2e08a", head: "#26221c", sting: true, iris: "#1a1614" }),
});

// n, art, types, stats, moves, status tag, note
const V = (n, art, t, b, m, st) => ({ n, art, t, b, m, l: [], c: 0.18, mem: true, org: st });
Object.assign(DEX, {
  // ---- extinct mammals ----
  thylacine: V("Thylacine", "thylacine", ["Predator", "Night"], B(58, 64, 48, 58), MV.pred, "† 1936"),
  quagga: V("Quagga", "quagga", ["Swift", "Wild"], B(58, 54, 46, 66), MV.swi, "† 1883"),
  aurochs: V("Aurochs", "aurochs", ["Wild", "Armor"], B(74, 72, 62, 40), MV.wild, "† 1627"),
  stellerseacow: V("Steller's Sea Cow", "stellerseacow", ["Aquatic", "Wild"], B(86, 44, 68, 16), MV.aqua, "† 1768"),
  irishelk: V("Irish Elk", "irishelk", ["Wild", "Swift"], B(70, 64, 54, 52), MV.wild, "† ~7,700 yrs"),
  woollyrhino: V("Woolly Rhinoceros", "woollyrhino", ["Ice", "Armor"], B(80, 74, 72, 30), MV.ice, "† ~10,000 yrs"),
  direwolf: V("Dire Wolf", "direwolf", ["Predator", "Ice"], B(66, 74, 54, 56), MV.pred, "† ~10,000 yrs"),
  smilodon: V("Smilodon", "smilodon", ["Predator", "Armor"], B(72, 82, 58, 44), ["apexfang", "maul", "intimidate"], "† ~10,000 yrs"),
  megatherium: V("Megatherium", "megatherium", ["Canopy", "Armor"], B(84, 70, 72, 18), MV.can, "† ~10,000 yrs"),
  glyptodon: V("Glyptodon", "glyptodon", ["Armor", "Burrow"], B(74, 56, 86, 16), MV.arm, "† ~10,000 yrs"),
  mastodon: V("Mastodon", "mastodon", ["Wild", "Armor"], B(84, 74, 70, 26), MV.wild, "† ~10,000 yrs"),
  columbianmammoth: V("Columbian Mammoth", "columbianmammoth", ["Wild", "Ice"], B(86, 76, 70, 24), MV.wild, "† ~11,000 yrs"),
  cavelion: V("Cave Lion", "cavelion", ["Predator", "Ice"], B(72, 80, 58, 50), MV.pred, "† ~13,000 yrs"),
  shortfacedbear: V("Short-faced Bear", "shortfacedbear", ["Predator", "Wild"], B(80, 80, 62, 44), MV.pred, "† ~11,000 yrs"),
  giantbeaver: V("Giant Beaver", "giantbeaver", ["Aquatic", "Burrow"], B(70, 56, 62, 28), MV.aqua, "† ~10,000 yrs"),
  steppebison: V("Steppe Bison", "steppebison", ["Ice", "Armor"], B(76, 70, 66, 34), MV.ice, "† ~9,000 yrs"),
  baiji: V("Baiji", "baiji", ["Aquatic", "Night"], B(58, 52, 46, 56), MV.aqua, "† 2006"),
  caribbeanmonkseal: V("Caribbean Monk Seal", "caribbeanmonkseal", ["Aquatic", "Wild"], B(60, 50, 52, 44), MV.aqua, "† 1952"),
  japanesewolf: V("Japanese Wolf", "japanesewolf", ["Predator", "Canopy"], B(52, 60, 44, 62), MV.pred, "† 1905"),
  falklandwolf: V("Falkland Islands Wolf", "falklandwolf", ["Predator", "Swift"], B(50, 56, 42, 58), MV.pred, "† 1876"),
  balitiger: V("Bali Tiger", "balitiger", ["Predator", "Canopy"], B(64, 74, 50, 62), MV.pred, "† ~1940s"),
  javantiger: V("Javan Tiger", "javantiger", ["Predator", "Canopy"], B(66, 74, 52, 60), MV.pred, "† ~1976"),
  caspiantiger: V("Caspian Tiger", "caspiantiger", ["Predator", "Swift"], B(70, 78, 54, 58), MV.pred, "† ~1970s"),
  seamink: V("Sea Mink", "seamink", ["Aquatic", "Swift"], B(44, 52, 38, 60), MV.aqua, "† ~1894"),
  bluebuck: V("Bluebuck", "bluebuck", ["Swift", "Wild"], B(56, 52, 46, 62), MV.swi, "† 1800"),
  schomburgksdeer: V("Schomburgk's Deer", "schomburgksdeer", ["Swift", "Wild"], B(54, 52, 44, 60), MV.swi, "† 1938"),
  toolachewallaby: V("Toolache Wallaby", "toolachewallaby", ["Swift", "Wild"], B(48, 48, 40, 70), MV.swi, "† 1939"),
  desertratkangaroo: V("Desert Rat-Kangaroo", "desertratkangaroo", ["Swift", "Burrow"], B(36, 40, 32, 72), MV.swi, "† ~1935"),
  pigfootedbandicoot: V("Pig-footed Bandicoot", "pigfootedbandicoot", ["Burrow", "Swift"], B(36, 42, 34, 62), MV.bur, "† ~1950s"),
  lesserbilby: V("Lesser Bilby", "lesserbilby", ["Burrow", "Night"], B(36, 40, 34, 56), MV.bur, "† ~1960s"),
  bramblecaymelomys: V("Bramble Cay Melomys", "bramblecaymelomys", ["Burrow", "Wild"], B(30, 34, 30, 50), MV.bur, "† 2016"),
  pyreneanibex: V("Pyrenean Ibex", "pyreneanibex", ["Armor", "Ice"], B(56, 56, 56, 46), MV.arm, "† 2000"),
  // ---- extinct birds ----
  dodo: V("Dodo", "dodo", ["Wild", "Armor"], B(58, 44, 52, 22), MV.wild, "† 1662"),
  greatauk: V("Great Auk", "greatauk", ["Aquatic", "Ice"], B(50, 48, 44, 42), MV.aqua, "† 1844"),
  passengerpigeon: V("Passenger Pigeon", "passengerpigeon", ["Aerial", "Swift"], B(38, 42, 32, 68), MV.aer, "† 1914"),
  carolinaparakeet: V("Carolina Parakeet", "carolinaparakeet", ["Aerial", "Canopy"], B(36, 42, 32, 64), MV.aer, "† 1918"),
  moa: V("Giant Moa", "moa", ["Wild", "Swift"], B(72, 58, 52, 54), MV.wild, "† ~1445"),
  haastseagle: V("Haast's Eagle", "haastseagle", ["Aerial", "Predator"], B(64, 78, 48, 66), ["divebomb", "apexfang", "stormdive"], "† ~1445"),
  elephantbird: V("Elephant Bird", "elephantbird", ["Wild", "Armor"], B(80, 60, 62, 30), MV.wild, "† ~1000"),
  huia: V("Huia", "huia", ["Canopy", "Aerial"], B(36, 42, 32, 58), MV.can, "† 1907"),
  labradorduck: V("Labrador Duck", "labradorduck", ["Aquatic", "Aerial"], B(38, 40, 34, 54), MV.aqua, "† 1878"),
  heathhen: V("Heath Hen", "heathhen", ["Wild", "Swift"], B(42, 42, 38, 52), MV.wild, "† 1932"),
  imperialwoodpecker: V("Imperial Woodpecker", "imperialwoodpecker", ["Canopy", "Bug"], B(42, 50, 36, 58), MV.bug, "† ~1956"),
  kauaioo: V("Kauaʻi ʻŌʻō", "kauaioo", ["Canopy", "Aerial"], B(32, 38, 28, 60), ["lullaby", "treeleap", "gust"], "† 1987"),
  poouli: V("Poʻouli", "poouli", ["Canopy", "Bug"], B(30, 36, 28, 58), MV.bug, "† 2004"),
  laysanhoneycreeper: V("Laysan Honeycreeper", "laysanhoneycreeper", ["Canopy", "Aerial"], B(28, 34, 26, 62), MV.aer, "† 1923"),
  // ---- extinct small things ----
  xercesblue: V("Xerces Blue", "xercesblue", ["Bug", "Aerial"], B(24, 30, 24, 60), MV.bug, "† 1943"),
  rockymountainlocust: V("Rocky Mountain Locust", "rockymountainlocust", ["Bug", "Swift"], B(26, 38, 26, 64), MV.bug, "† 1902"),
  goldentoad: V("Golden Toad", "goldentoad", ["Venom", "Canopy"], B(32, 38, 34, 36), MV.ven, "† 1989"),
  splendidpoisonfrog: V("Splendid Poison Frog", "splendidpoisonfrog", ["Venom", "Canopy"], B(28, 40, 28, 46), MV.ven, "† 2020"),
  chinesepaddlefish: V("Chinese Paddlefish", "chinesepaddlefish", ["Aquatic", "Swift"], B(56, 50, 42, 58), MV.aqua, "† 2019"),
  xmasislandpipistrelle: V("Christmas I. Pipistrelle", "xmasislandpipistrelle", ["Aerial", "Night"], B(26, 34, 24, 68), MV.night, "† 2009"),
  // ---- extinct in the wild ----
  alala: V("ʻAlalā", "alala", ["Canopy", "Night"], B(44, 50, 40, 58), ["treeleap", "peck", "lullaby"], "EW 2002"),
  spixsmacaw: V("Spix's Macaw", "spixsmacaw", ["Aerial", "Canopy"], B(42, 46, 36, 62), MV.aer, "EW 2000 ←"),
  peredavidsdeer: V("Père David's Deer", "peredavidsdeer", ["Wild", "Aquatic"], B(60, 54, 50, 48), MV.wild, "EW ←"),
  scimitaroryx: V("Scimitar-horned Oryx", "scimitaroryx", ["Armor", "Swift"], B(58, 58, 54, 56), MV.arm, "EW 2000 ←"),
  southchinatiger: V("South China Tiger", "southchinatiger", ["Predator", "Swift"], B(70, 80, 56, 60), MV.pred, "EW ~1990s"),
  guamkingfisher: V("Guam Kingfisher", "guamkingfisher", ["Aerial", "Canopy"], B(32, 42, 30, 64), MV.aer, "EW 1986 ←"),
  socorrodove: V("Socorro Dove", "socorrodove", ["Aerial", "Canopy"], B(34, 38, 30, 58), MV.aer, "EW 1972"),
  wyomingtoad: V("Wyoming Toad", "wyomingtoad", ["Venom", "Burrow"], B(34, 36, 38, 30), MV.ven, "EW 1991"),
  partulasnail: V("Partula Snail", "partulasnail", ["Armor", "Canopy"], B(30, 26, 52, 8), MV.arm, "EW ←"),
  // ---- critically endangered ----
  northernwhiterhino: V("Northern White Rhino", "northernwhiterhino", ["Armor", "Wild"], B(82, 70, 76, 24), MV.arm, "CR — 2 left"),
  javanrhino: V("Javan Rhino", "javanrhino", ["Armor", "Canopy"], B(76, 70, 72, 30), MV.arm, "CR"),
  sumatranrhino: V("Sumatran Rhino", "sumatranrhino", ["Armor", "Canopy"], B(72, 68, 70, 34), MV.arm, "CR"),
  amurleopard: V("Amur Leopard", "amurleopard", ["Ice", "Predator"], B(62, 74, 50, 68), MV.ice, "CR"),
  saola: V("Saola", "saola", ["Canopy", "Swift"], B(52, 50, 46, 58), MV.can, "CR"),
  hainangibbon: V("Hainan Gibbon", "hainangibbon", ["Canopy", "Swift"], B(48, 52, 42, 72), MV.can, "CR — ~40 left"),
  crossrivergorilla: V("Cross River Gorilla", "crossrivergorilla", ["Wild", "Armor"], B(76, 74, 64, 30), MV.wild, "CR"),
  tapanuliorangutan: V("Tapanuli Orangutan", "tapanuliorangutan", ["Canopy", "Wild"], B(66, 64, 56, 34), MV.can, "CR — ~800 left"),
  sumatranorangutan: V("Sumatran Orangutan", "sumatranorangutan", ["Canopy", "Wild"], B(68, 64, 58, 34), MV.can, "CR"),
  redwolf: V("Red Wolf", "redwolf", ["Predator", "Swift"], B(54, 62, 46, 62), MV.pred, "CR ←"),
  whoopingcrane: V("Whooping Crane", "whoopingcrane", ["Aerial", "Aquatic"], B(52, 48, 44, 58), MV.aer, "CR ←"),
  californiacondor: V("California Condor", "californiacondor", ["Aerial", "Wild"], B(64, 60, 50, 58), MV.aer, "CR ←"),
  przewalskishorse: V("Przewalski's Horse", "przewalskishorse", ["Swift", "Wild"], B(62, 58, 50, 68), MV.swi, "EW 1969 ←"),
  yangtzesofttshell: V("Yangtze Softshell", "yangtzesofttshell", ["Aquatic", "Armor"], B(64, 48, 70, 20), MV.arm, "CR — ~2 left"),
  chinesegiantsalamander: V("Chinese Giant Salamander", "chinesegiantsalamander", ["Aquatic", "Night"], B(58, 50, 50, 22), MV.aqua, "CR"),
  finlessporpoise: V("Yangtze Finless Porpoise", "finlessporpoise", ["Aquatic", "Swift"], B(50, 50, 42, 62), MV.aqua, "CR"),
  angelshark: V("Angelshark", "angelshark", ["Aquatic", "Armor"], B(54, 56, 56, 30), MV.aqua, "CR"),
  kempsridley: V("Kemp's Ridley Turtle", "kempsridley", ["Aquatic", "Armor"], B(54, 44, 62, 30), MV.arm, "CR"),
  vancouvermarmot: V("Vancouver I. Marmot", "vancouvermarmot", ["Burrow", "Ice"], B(46, 42, 46, 36), MV.bur, "CR ←"),
  regenthoneyeater: V("Regent Honeyeater", "regenthoneyeater", ["Canopy", "Aerial"], B(30, 36, 28, 62), MV.can, "CR"),
  orangebelliedparrot: V("Orange-bellied Parrot", "orangebelliedparrot", ["Aerial", "Swift"], B(30, 36, 28, 64), MV.aer, "CR"),
  sumatrantiger: V("Sumatran Tiger", "sumatrantiger", ["Predator", "Canopy"], B(68, 76, 54, 60), MV.pred, "CR"),
  hirola: V("Hirola", "hirola", ["Swift", "Wild"], B(52, 50, 44, 64), MV.swi, "CR"),
  damagazelle: V("Dama Gazelle", "damagazelle", ["Swift", "Wild"], B(48, 48, 40, 70), MV.swi, "CR"),
  rustypatchedbumblebee: V("Rusty-patched Bumblebee", "rustypatchedbumblebee", ["Bug", "Aerial"], B(26, 38, 26, 56), MV.bug, "CR"),
  franklinsbumblebee: V("Franklin's Bumblebee", "franklinsbumblebee", ["Bug", "Aerial"], B(26, 38, 26, 56), MV.bug, "CR"),
});

// ---- the region ----
const VIG_MID = ["^^^^^^^n^^^^^^^^", "^..GGG....GGG..^", "^.GGGGG..GGGGG.^", "^......!.......^", "^R...........R.^", "^..GGGG..GGGG..^", "^..GGGG..GGGG..^", "^......!.......^", "^..GGG....GGG..^", "^^^^^^^s^^^^^^^^"];
const VIG_END = ["^^^^^^^^^^^^^^^^", "^..GGG....GGG..^", "^.GGGGG..GGGGG.^", "^......!.......^", "^R...........R.^", "^..GGGG..GGGG..^", "^..GGGG..GGGG..^", "^......!.......^", "^..GGG....GGG..^", "^^^^^^^s^^^^^^^^"];

MAPS.vigil = {
  name: "The Vigil Gate", zone: "vigilz", music: "cave",
  rows: [
    "^^^^^n^^^^n^^^^^",
    "^...!......!...^",
    "^..............^",
    "e..............e",
    "^..CC......MM..^",
    "^..............^",
    "^......*.......^",
    "^...!......!...^",
    "^..............^",
    "^^^^^^^s^^^^^^^^",
  ],
  exits: {
    "7,9": { map: "town9", x: 1, y: 9 },
    "0,3": { map: "vig1", x: 7, y: 8 }, "15,3": { map: "vig4", x: 7, y: 8 },
    "5,0": { map: "vig6", x: 7, y: 8 }, "10,0": { map: "vig8", x: 7, y: 8 },
  },
};
// champion-gated doorway out of Gloam Town
MAPS.town9.rows = withRow(MAPS.town9.rows, 9, "e..............T");
MAPS.town9.exits = { ...MAPS.town9.exits, "0,9": { map: "vigil", x: 7, y: 8, req: "champion", reqMsg: "🕯️ A keeper in grey stands in the doorway. \"The Vigil is not a trophy hall, ranger. Come back when you've finished the trail — and come back ready to be sad for a while.\"" } };

const VIG = [
  { k: "vig1", n: "The Roll Call", z: "vigilz", lvl: [52, 56], next: "vig2", prev: { map: "vigil", x: 1, y: 3 },
    pool: [["thylacine", 11], ["quagga", 10], ["aurochs", 9], ["bluebuck", 9], ["schomburgksdeer", 8], ["japanesewolf", 8], ["falklandwolf", 8], ["seamink", 8], ["toolachewallaby", 8], ["desertratkangaroo", 7], ["pigfootedbandicoot", 7], ["lesserbilby", 7], ["pyreneanibex", 6], ["bramblecaymelomys", 6], ["caribbeanmonkseal", 6]] },
  { k: "vig2", n: "The Striped Hollow", z: "vigilz", lvl: [53, 57], next: "vig3", prev: { map: "vig1", x: 7, y: 1 },
    pool: [["balitiger", 9], ["javantiger", 9], ["caspiantiger", 8], ["thylacine", 9], ["japanesewolf", 8], ["quagga", 8], ["cavelion", 6], ["smilodon", 5], ["direwolf", 7], ["southchinatiger", 5], ["sumatrantiger", 6], ["amurleopard", 6]] },
  { k: "vig3", n: "The Ice Wake", z: "vigilz", lvl: [55, 59], next: null, prev: { map: "vig2", x: 7, y: 1 },
    pool: [["mammoth", 8], ["columbianmammoth", 7], ["mastodon", 7], ["woollyrhino", 7], ["steppebison", 8], ["irishelk", 8], ["direwolf", 8], ["cavelion", 6], ["smilodon", 6], ["shortfacedbear", 6], ["megatherium", 6], ["glyptodon", 6], ["giantbeaver", 7]] },
  { k: "vig4", n: "The Island Grave", z: "vigilz", lvl: [52, 56], next: "vig5", prev: { map: "vigil", x: 14, y: 3 },
    pool: [["dodo", 10], ["greatauk", 9], ["moa", 8], ["elephantbird", 7], ["haastseagle", 6], ["huia", 8], ["laysanhoneycreeper", 8], ["labradorduck", 8], ["heathhen", 8], ["socorrodove", 7], ["partulasnail", 8], ["stellerseacow", 6]] },
  { k: "vig5", n: "The Sky That Darkened", z: "vigilz", lvl: [53, 57], next: null, prev: { map: "vig4", x: 7, y: 1 },
    pool: [["passengerpigeon", 12], ["carolinaparakeet", 10], ["rockymountainlocust", 10], ["xercesblue", 9], ["goldentoad", 8], ["splendidpoisonfrog", 7], ["heathhen", 8], ["imperialwoodpecker", 7], ["labradorduck", 7], ["greatauk", 7], ["xmasislandpipistrelle", 7]] },
  { k: "vig6", n: "The Last Song", z: "vigilz", lvl: [54, 58], next: "vig7", prev: { map: "vigil", x: 5, y: 1 },
    pool: [["kauaioo", 11], ["poouli", 10], ["laysanhoneycreeper", 9], ["huia", 9], ["alala", 8], ["imperialwoodpecker", 7], ["guamkingfisher", 7], ["regenthoneyeater", 7], ["orangebelliedparrot", 7], ["spixsmacaw", 6]] },
  { k: "vig7", n: "The Drowned Song", z: "vigilz", lvl: [55, 59], next: null, prev: { map: "vig6", x: 7, y: 1 },
    pool: [["baiji", 9], ["chinesepaddlefish", 9], ["yangtzesofttshell", 6], ["finlessporpoise", 8], ["chinesegiantsalamander", 8], ["vaquita", 6], ["angelshark", 8], ["kempsridley", 8], ["stellerseacow", 6], ["caribbeanmonkseal", 7], ["giantbeaver", 7], ["seamink", 7]] },
  { k: "vig8", n: "The Thin Edge", z: "vigilz", lvl: [56, 60], next: "vig9", prev: { map: "vigil", x: 10, y: 1 },
    pool: [["vaquita", 5], ["northernwhiterhino", 4], ["javanrhino", 5], ["sumatranrhino", 5], ["amurleopard", 6], ["saola", 5], ["hainangibbon", 5], ["crossrivergorilla", 5], ["tapanuliorangutan", 5], ["sumatranorangutan", 6], ["sumatrantiger", 6], ["southchinatiger", 4], ["hirola", 7], ["damagazelle", 7], ["rustypatchedbumblebee", 8], ["franklinsbumblebee", 8], ["kakapo", 5], ["gharial", 6], ["philippineeagle", 5]] },
  { k: "vig9", n: "The Glass Ark", z: "vigilz", lvl: [56, 60], next: "vig10", prev: { map: "vig8", x: 7, y: 1 },
    pool: [["axolotl", 11], ["alala", 9], ["spixsmacaw", 8], ["wyomingtoad", 9], ["partulasnail", 9], ["guamkingfisher", 8], ["socorrodove", 8], ["peredavidsdeer", 8], ["scimitaroryx", 8], ["przewalskishorse", 7], ["californiacondor", 7], ["whoopingcrane", 7], ["redwolf", 7], ["ferret", 8], ["vancouvermarmot", 8], ["kakapo", 6], ["orangebelliedparrot", 7], ["regenthoneyeater", 7], ["southchinatiger", 4]] },
  { k: "vig10", n: "What We Kept", z: "hopez", lvl: [58, 62], next: null, prev: { map: "vig9", x: 7, y: 1 },
    pool: [["przewalskishorse", 10], ["scimitaroryx", 9], ["peredavidsdeer", 9], ["californiacondor", 8], ["whoopingcrane", 8], ["redwolf", 7], ["ferret", 9], ["vancouvermarmot", 8], ["bison", 9], ["oryx", 8], ["humpback", 7], ["greywhale", 0], ["graywhale", 7], ["seaotter", 8], ["panda", 7], ["snowleopard", 6], ["baldeagle", 8], ["peregrine", 8], ["alala", 6], ["spixsmacaw", 6], ["kakapo", 6], ["beaver", 9], ["grizzly", 7], ["moonbear", 6], ["mandarinduck", 8], ["swan", 8], ["greenseaturtle", 8], ["hawksbill", 7]] },
];
VIG.forEach((d) => {
  MAPS[d.k] = {
    name: d.n, zone: d.z, music: d.k === "vig10" ? "town" : "cave",
    rows: d.next ? VIG_MID : VIG_END,
    exits: { "7,9": d.prev, ...(d.next ? { "7,0": { map: d.next, x: 7, y: 8 } } : {}) },
    pool: d.pool.filter(([sp]) => DEX[sp]), lvl: d.lvl,
  };
});

Object.assign(SIGNS, {
  "vigil:4,1": "🪧 'THE VIGIL — nothing here is invented. Every animal past this gate either is gone, or is very nearly. Walk slowly.'",
  "vigil:11,1": "🪧 'The keeper's rule: you may befriend anyone here. They are easy to befriend. They have been waiting a long time for someone to come back for them.'",
  "vigil:4,7": "🪧 '⬅ THE ROLL CALL · THE ISLAND GRAVE ➡ · ⬆ THE LAST SONG · ⬆ THE THIN EDGE'",
  "vigil:11,7": "🪧 'Keep walking to the end. The last room is not sad. We made sure of that.'",
  "vig1:7,3": "🪧 'THE ROLL CALL — the last thylacine died in a Hobart zoo on 7 September 1936, locked out of its shelter on a freezing night. It had a name: Benjamin. The species was granted legal protection 59 days earlier.'",
  "vig1:7,7": "🪧 'The quagga was a zebra whose stripes faded halfway down. We shot them all for hides and grazing land by 1883. In 1984 its DNA became the first ever recovered from an extinct animal.'",
  "vig2:7,3": "🪧 'THE STRIPED HOLLOW — of nine tiger subspecies, three are gone: Bali, Javan, Caspian. All in one century. All of them ours.'",
  "vig2:7,7": "🪧 'The tigers still here — Sumatran, South China, Amur — are here because people decided they should be. That is the only reason any of them are here.'",
  "vig3:7,3": "🪧 'THE ICE WAKE — the last mammoths died on Wrangel Island about 4,000 years ago. The pyramids were already a thousand years old. They overlapped with us the entire time.'",
  "vig3:7,7": "🪧 'Nearly every megafauna extinction of the last 50,000 years follows the same arrival on the map. We are the asteroid in this one.'",
  "vig4:7,3": "🪧 'THE ISLAND GRAVE — the dodo was not stupid. It was fearless, because for four million years nothing on Mauritius had ever hunted it. We mistook trust for idiocy and made its name a synonym for it.'",
  "vig4:7,7": "🪧 'Islands hold a fraction of the world\\'s land and most of its extinctions. Everything here evolved without predators, and then a ship arrived.'",
  "vig5:7,3": "🪧 'THE SKY THAT DARKENED — passenger pigeon flocks took three days to pass overhead and blotted out the sun. There were maybe five billion. The last one, Martha, died alone in Cincinnati Zoo on 1 September 1914.'",
  "vig5:7,7": "🪧 'Abundance is not safety. The Rocky Mountain locust swarmed in the trillions — the largest animal congregation ever recorded — and was extinct within thirty years.'",
  "vig6:7,3": "🪧 'THE LAST SONG — the Kauaʻi ʻōʻō\\'s mating call was recorded in 1987. It is a duet. On the recording you can hear him singing the male part, then pausing for the female response that never comes. She had already died in a hurricane. He was the last of his kind and he did not know it.'",
  "vig6:7,7": "🪧 'The ʻalalā — the Hawaiian crow — went extinct in the wild in 2002. Every one alive today lives in a breeding facility. They are learning to be crows again from humans, and it is going badly, and we are not stopping.'",
  "vig7:7,3": "🪧 'THE DROWNED SONG — the baiji was declared functionally extinct in 2006, the first dolphin humans erased. Not hunted. Just crowded out of a river by boats and nets and noise.'",
  "vig7:7,7": "🪧 'Around 10 vaquita remain in the Gulf of California. They drown in gillnets set for another endangered fish, whose swim bladder sells as medicine. Nobody wants the vaquita gone. It is going anyway.'",
  "vig8:7,3": "🪧 'THE THIN EDGE — there are two northern white rhinos left. Both female. Both live under armed guard in Kenya. Najin and Fatu. There is no third. The last male, Sudan, died in 2018.'",
  "vig8:7,7": "🪧 'Every animal in this room could still be saved. That is what makes this the hardest room.'",
  "vig9:7,3": "🪧 'THE GLASS ARK — the axolotl is nearly gone from the canals of Xochimilco, and lives in millions of aquariums worldwide. It is simultaneously one of the most common and most endangered animals on earth.'",
  "vig9:7,7": "🪧 'Captive breeding is not a happy ending. It is a held breath — a species parked in a room while we decide whether we will fix the place it came from.'",
  "vig10:7,3": "🪧 'WHAT WE KEPT — Przewalski\\'s horse went extinct in the wild in 1969. Every one alive descends from about 12 captive animals. In 1992 we started letting them go. There are wild herds in Mongolia now. They did not need us to be perfect. They needed us to not stop.'",
  "vig10:7,7": "🪧 'The bison came back from about 500. The California condor from 22. The sea otter from a few thousand pelts\\' worth. The whooping crane from 15 birds. Fifteen. It works. It is slow and expensive and it works, and that is the entire argument. Thank you for walking all the way to the end, ranger. 🌱'",
});
