// GENERATED by design/tools/forge_desert.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "desert", maps: {
 "route4": {
  "rows": [
   "WWWggggggggg..gggggggggggWWW",
   "TTTggggggggg..gggggggggggTTT",
   "TTTg^ggggggg..gggg^ggggggTTT",
   "TTgggggggggg..gRgggggggggTTT",
   "TTgTggggg*gg..gg^^.....g^TTT",
   "TTgg^ggggggg..ggg...Ω...TTTT",
   "TTTgGGGGGggg..ggT.......gTTT",
   "TTTgGGGGGRgg..Tggggg*^gggTTT",
   "TTTTGGGGGggg..gggggggggggTTT",
   "TTTT!gggg*gg..ggg*ggggggg^TT",
   "TTT^gggggggg..gggggggggg!TTT",
   "e..........................e",
   "T..........................T",
   "TTTggggggggg..ggg¡ggggTggTTT",
   "TTgTggggg⁂gg..ggggggggggTTTT",
   "TTgggGGGgggg...gggGGGGGggTTT",
   "TTgTgggggggg...gggGGGGGgTTTT",
   "TTTg....ggggg..gggGG^GGgg^TT",
   "TTT*.....Tggg..gggR^gggggTTT",
   "TTTg.....gggg..ggggggggggTTT",
   "TTgggggggTggg..gggggg*gggTTT",
   "TTTggggTggggg..gggggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "4,9": "route4:gate",
   "24,10": "route4:gate2",
   "9,7": "route4:4,4",
   "18,18": "route4:11,10",
   "15,3": "route4:12,10"
  },
  "marks": {
   "20,5": "lm_singing_dune"
  },
  "finds": {
   "23,3": {
    "id": "des_r4_dune",
    "item": "treats",
    "n": 2
   },
   "4,20": {
    "id": "des_r4_scrub",
    "item": "coins",
    "n": 150
   }
  },
  "exits": {
   "0,11": {
    "map": "outback",
    "x": 7,
    "y": 8
   },
   "27,11": {
    "map": "digsite",
    "x": 1,
    "y": 6,
    "req": "champion",
    "reqMsg": "🚧 Ranger barricade: \"The Fossil Rift canyon is champions-only. Earn the title first!\""
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "tidewater",
    "off": 0
   },
   "s": {
    "map": "town4",
    "off": 0
   }
  },
  "gen": 5
 },
 "tidewater": {
  "rows": [
   "WWgg..ggWWWWWWWWWWWWWWWWWWWW",
   "WWgg..ggWWWWWWWWWWWWWWWWWWWW",
   "WWgg..ggWWWWnWWWWWWWnWWWWWWW",
   "WWgg..ggWWWW.WWWWWWW.WWWWWWW",
   "WWgg..ggWWWW.WWWWWWW.WWWWWWW",
   "WWgg..ggWWWW.WWWWWWW.WWWWWWW",
   "WWgg..ggWWWW.WWWWWWW.WWWWWWW",
   "WWgg..ggWWWW.WWWWWWW.WWWWWWW",
   "WWgg..ggWWWW.WWWWWWW.WWWWWWW",
   "WWgg..ggWWgg.WWgggWg.WgWggWW",
   "WWgg..gggggg.ggggggg.gggggWW",
   "WWWg..gGGGgg.ggggggg.!ggggWW",
   "WWgg..!gggg!.ggggΩg*.GGGggWW",
   "WWgg..gggΩg*.g!ggggg.gggggWW",
   "WWgg..gggggg.ggggggg.gggggWW",
   "WWgg....................ggWW",
   "WWgg....................ggWW",
   "e...ggggg!gg..ggggg**g.....e",
   "WWg!*ggggggg..gggggggggg!gWW",
   "WWgggggCgggg..gMggg*g!gggWWW",
   "WWgggΩggggΩg..gggggggggΩggWW",
   "WWWggggggggg..Ωg...Ω.gggggWW",
   "WWgggggggggg..ggggggggggggWW",
   "WWWggggggggg..gggggggggggWWW"
  ],
  "cast": {
   "14,13": "tidewater:3,2",
   "9,17": "tidewater:11,1",
   "6,12": "tidewater:4,7",
   "21,19": "tidewater:11,7",
   "11,12": "tidewater:blue",
   "21,11": "tidewater:ice",
   "3,18": "tidewater:reef",
   "24,18": "tidewater:kelp"
  },
  "marks": {
   "19,21": "lm_turtle_nest",
   "10,20": "decor:canoe",
   "17,12": "decor:canoe",
   "5,20": "decor:nets",
   "23,20": "decor:nets",
   "14,21": "decor:crates",
   "9,13": "decor:bench"
  },
  "finds": {
   "24,11": {
    "id": "des_tw_spit",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "12,2": {
    "map": "openocean",
    "x": 7,
    "y": 8
   },
   "20,2": {
    "map": "polarsea",
    "x": 7,
    "y": 8
   },
   "0,17": {
    "map": "reef",
    "x": 7,
    "y": 8
   },
   "27,17": {
    "map": "kelp",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {
   "e": "W",
   "w": "W"
  },
  "land": [
   12,
   20
  ],
  "links": {
   "s": {
    "map": "route4",
    "off": 0
   },
   "n": {
    "map": "seg_d1",
    "off": 0
   }
  },
  "gen": 5
 },
 "seg_d1": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgg^ggggggg..ggGGGgggggTTT",
   "TTTTggggggggg..ggRggggg^gTTT",
   "TTTTggg^ggggg..gggggg^gggTTT",
   "TTTgggggg*............ggTTTT",
   "TTTTgggggg............^ggTTT",
   "TTTgggggRg..g..g*ggggggggTTT",
   "TTTggggggg..g..ggggg^gggTTTT",
   "TTT.........g..TgT*gggg^TTTT",
   "TTT.........g..gggggΩgggTTTT",
   "TTTgGGGGGgggg..gggg...gg^TTT",
   "TTTgGGGGGgg⁂g..gggggggggTTTT",
   "TTTgGGGGGgggg..gggGGGgggTTTT",
   "TTggRgg¡ggggg..gggggggggTTTT",
   "TTggggg*ggg*g..gggggggggTTTT",
   "TTgg...........gggWWWWWWWWWW",
   "TTgg...........gRgWWWWWWWWWW",
   "T^gg..ggggTgWWWWWWWWWWWWWWWW",
   "TTgT..RgggggWWWWWWWWWWWWWWWW",
   "WWgg..gTWWWWWWWWWWWWWWWWWWWW",
   "WWgg..ggWWWWWWWWWWWWWWWWWWWW",
   "WWgg..ggWWWWWWWWWWWWWWWWWWWW",
   "WWgg..ggWWWWWWWWWWWWWWWWWWWW"
  ],
  "cast": {
   "6,19": "seg_d1:2,1",
   "16,17": "seg_d1:10,6",
   "8,7": "seg_d1:6,8",
   "17,3": "seg_d1:3,10",
   "4,14": "seg_d1:11,10"
  },
  "marks": {
   "20,10": "lm_fog_beetle"
  },
  "finds": {
   "23,11": {
    "id": "des_d1_crest",
    "item": "wakeberry",
    "n": 1
   },
   "3,2": {
    "id": "des_d1_corner",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   5,
   20
  ],
  "links": {
   "s": {
    "map": "tidewater",
    "off": 0
   },
   "n": {
    "map": "seg_d2",
    "off": 0
   }
  },
  "gen": 5
 },
 "seg_d2": {
  "rows": [
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTggggg*ggggg..gggggggggggTT",
   "TTggGGGGGgggg..gRgggggggggTT",
   "TTggGGGGGgggg..gggg^ggggggTT",
   "TTTgGGGGG⁌ggg..gggg^gg*ggTTT",
   "TTTgggggggggg..gg^ggggggggTT",
   "TTg!ggggggggg..gggggGGGggTTT",
   "e..............gggggggggggTT",
   "T..............gggggggggggTT",
   "TTggggggggggg..gggggggRgggTT",
   "TTggggggRggg*..gggg*ggggggTT",
   "TTggggggggggg..ggg..Ω..gg^TT",
   "TTTgTTggg^ggg..ggg.....ggTTT",
   "TT^gTggg^Tg....ggg.....TgTTT",
   "TTTggRgTggg....g⁂ggggggggTTT",
   "TTTgggggggg..gggggTgg^ggTTTT",
   "TT^gT^ggggg..gggggg*gggggTTT",
   "TT^gggggggg..ggggggTggg^^^TT",
   "TTTTgg^gggg..gggggggggggg^TT",
   "TTTgggggggg..gggRgGGGGGggTTT",
   "TT^ggggg¡gg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "3,7": "seg_d2:gate",
   "16,3": "seg_d2:6,1",
   "8,11": "seg_d2:2,4",
   "5,15": "seg_d2:1,5",
   "22,10": "seg_d2:13,5",
   "16,20": "seg_d2:6,7"
  },
  "marks": {
   "20,12": "lm_sandstone_arch"
  },
  "finds": {
   "22,13": {
    "id": "des_d2_arch",
    "item": "antidote",
    "n": 1
   },
   "4,3": {
    "id": "des_d2_rocks",
    "item": "coins",
    "n": 160
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_bathynax",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "seg_d1",
    "off": 0
   },
   "n": {
    "map": "seg_d3",
    "off": 0
   }
  },
  "gen": 5
 },
 "seg_d3": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TT^gggggggg..gggggggggggggTT",
   "TTTgggggggg..ggggggggg^gggTT",
   "TTggGGGGGgg..ggggTggg*gg^gTT",
   "TTggggggggg..gggggggggggggTT",
   "TTggggggRgg..ggg*ggg^ggg*TTT",
   "TTTg^^ggggg..ggggg.......TTT",
   "TTTgggggggg..ggggg.......TTT",
   "TTTTggggggg..ggggg..gg*ggTTT",
   "TTTgggTTggg.....gg..gΩggg^TT",
   "TTTgggggggg.....gg..ggggTTTT",
   "TT^*gggggggggg..⁂g..gggggTTT",
   "TTTgggggg...........gggRgTTT",
   "TTTTggggg....R......gggggTTT",
   "TTTTGGGgg.WW.g..ggggGGGggTTT",
   "TTTTggggg....g..ggggggggggTT",
   "TTTgggggg..ggg..ggRgggggggTT",
   "TTTgggRgg..ggg..gggggggggTTT",
   "TTTgggggg..ggg..TggggggggTTT",
   "TTT........ggg..gggggggggTTT",
   "TTT........ggg..gggg^g^ggTTT",
   "T^gg¡ggggggggg..ggTgg*gggTTT",
   "TTgggggggggggg..gggggggggTTT",
   "TTggggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "23,12": "seg_d3:14,1",
   "8,5": "seg_d3:4,3",
   "13,13": "seg_d3:9,4",
   "6,17": "seg_d3:5,7",
   "18,16": "seg_d3:9,7"
  },
  "marks": {
   "21,9": "lm_welwitschia"
  },
  "finds": {
   "22,7": {
    "id": "des_d3_bank",
    "item": "bigberries",
    "n": 1
   },
   "4,11": {
    "id": "des_d3_west",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_d2",
    "off": 0
   },
   "n": {
    "map": "seg_d4",
    "off": 0
   }
  },
  "gen": 5
 },
 "seg_d4": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..gggggggg^gTTT",
   "TTTgggggggg*g..ggggggg^ggTTT",
   "TTTgGGGGGgggg..gggggggggggTT",
   "TTTggggggg⁂gg..ggRgTgggggg^T",
   "TTTT!*ggggggg..*gggggggg^gTT",
   "TTTT*Tggggggg..ggggggggggTTT",
   "e..............gggggGGGggTTT",
   "T..............gggggggggggTT",
   "TTTggg*gTTggg..gggggggggggTT",
   "TTTgg¡ggggggg..ggg....RggTTT",
   "TTTggg^gggggg..ggg.WWW.gggTT",
   "TTTTggggg^ggg..ggg.WWW.gggTT",
   "TTTgTg^gggggg..ggg.....gggTT",
   "TT^gggggggggg...ggΩgggggggTT",
   "TTTgggggggggg...gggggggggggT",
   "TTTgTgggRggggg..gggggggggggT",
   "TTTgGGGGGggggg..⁅ggggggg*ggT",
   "TTggGGGGGggggg..gTggggggggTT",
   "TTTgGGGGGggggg..gggg^ggggggT",
   "TTTggggggggggg..gggTg^ggggTT",
   "TTTggggggggggg..gggggggggg^T",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "4,6": "seg_d4:gate",
   "17,5": "seg_d4:11,1",
   "22,11": "seg_d4:3,4",
   "8,17": "seg_d4:11,4"
  },
  "marks": {
   "18,15": "lm_sandgrouse"
  },
  "finds": {
   "23,14": {
    "id": "des_d4_water",
    "item": "berries",
    "n": 3
   },
   "4,21": {
    "id": "des_d4_south",
    "item": "coins",
    "n": 170
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_glyptor",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_d3",
    "off": 0
   },
   "n": {
    "map": "town5",
    "off": 0
   }
  },
  "gen": 5
 },
 "town5": {
  "rows": [
   "TTTTTTTTTTTTTnTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTT.TTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTTTggggggggg..!ggggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgHg*gCgggg..gggYggggHggTT",
   "TTTgTgggggggg..*ggggggggggTT",
   "TTggggg¦............¦gggggTT",
   "TTTgggg..............gΩgggTT",
   "TTTTgΩg..Ω......Ω....ggggTTT",
   "TTTggTg....Ω......Ω..ggggTTT",
   "TTTgggg..R...........ggHTTTT",
   "T^ggHgg.....Ω...Ω....gggTTTT",
   "TTTgggg¦............¦ggTTTTT",
   "TTTgggΩgggggg..ggVggg*gggTTT",
   "TTTgggggggΩgg..gggggggggg^TT",
   "TTTg.....................TTT",
   "TTTg.....................TTT",
   "TT^g!gggggg¦g..g¦g*MgΩgggTTT",
   "TTTgg*ggggggg..ggggggΩgg^TTT",
   "TTTggΩggHgggg..ggggggg^ggTTT",
   "TTTTgggggggg!..ggΩgggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "15,3": "town5:gate",
   "12,21": "town5:9,3",
   "4,18": "town5:8,12",
   "9,11": "town5:3,8",
   "17,14": "town5:9,10"
  },
  "marks": {
   "21,19": "lm_qanat",
   "11,10": "decor:well",
   "9,9": "decor:jars",
   "12,12": "decor:jars",
   "21,18": "decor:jars",
   "16,9": "decor:stall",
   "16,12": "decor:stall",
   "10,15": "decor:stall",
   "5,9": "decor:tent",
   "22,8": "decor:tent",
   "5,20": "decor:tent",
   "17,21": "decor:tent",
   "18,10": "decor:bench",
   "6,14": "decor:crates"
  },
  "finds": {
   "23,12": {
    "id": "des_t5_tents",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "13,0": {
    "map": "route5",
    "x": 7,
    "y": 14
   }
  },
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_d4",
    "off": 0
   }
  },
  "gen": 5
 }
}, inbound: [
 {
  "from": "outback",
  "tile": "7,9",
  "map": "route4",
  "x": 1,
  "y": 11
 },
 {
  "from": "digsite",
  "tile": "0,6",
  "map": "route4",
  "x": 26,
  "y": 11
 },
 {
  "from": "reef",
  "tile": "7,9",
  "map": "tidewater",
  "x": 2,
  "y": 17
 },
 {
  "from": "kelp",
  "tile": "7,9",
  "map": "tidewater",
  "x": 24,
  "y": 17
 },
 {
  "from": "openocean",
  "tile": "7,9",
  "map": "tidewater",
  "x": 12,
  "y": 13
 },
 {
  "from": "polarsea",
  "tile": "7,9",
  "map": "tidewater",
  "x": 20,
  "y": 13
 },
 {
  "from": "shore",
  "tile": "0,8",
  "map": "tidewater",
  "x": 13,
  "y": 20
 },
 {
  "from": "shrine_bathynax",
  "tile": "7,9",
  "map": "seg_d2",
  "x": 1,
  "y": 8
 },
 {
  "from": "shrine_glyptor",
  "tile": "7,9",
  "map": "seg_d4",
  "x": 1,
  "y": 8
 },
 {
  "from": "route5",
  "tile": "7,15",
  "map": "town5",
  "x": 13,
  "y": 1
 }
] });
