// GENERATED by design/tools/forge_fossil.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "fossil", maps: {
 "digsite": {
  "rows": [
   "^^^^^^^^^^^^^n^^^^^^^^^^^^^^",
   "^^^^^^^^^^^^^..g^^^^^^^^^^^^",
   "^^^^^g^g^^^^!..ggggggggggg^^",
   "^^^gggggggggg..ggggg*gTggg^^",
   "^^^ggg^gg*ggg..ggggggggggg^^",
   "^^^g^^ggggggg..ggggggggT^g^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^^ggggggggg..gggΩg**ggg^^^",
   "^^^ggggCggggg..gggggggΩgg^^^",
   "^^^^Ωgg*gg!gg..g!gggggggg^^^",
   "^^^^g^ggggggg..gggg*gggg!^^^",
   "^^^^ggggggggg..ggggggggg^^^^",
   "e..........................e",
   "^..........................^",
   "^^^g^gggggggg..ggggggggg^^^^",
   "^^^gΩggggg!gg..g!gggggggg^^^",
   "^^^^ggggggggg..gggΩgggg^g^^^",
   "^^^^g^...gggg..gggggMggg^^^^",
   "^^^^.....gggg..ggggggg^g^^^^",
   "^^^gg....gggg..gggggggggg^^^",
   "^^^gggggΩg!gg..gggggggg^g^^^",
   "^^^gggggggg^g..gggggggg^g^^^",
   "^^^^^^^^^^^^^..^^^^^^g^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "10,9": "digsite:4,2",
   "16,9": "digsite:11,2",
   "10,15": "digsite:6,4",
   "16,15": "digsite:4,9",
   "12,2": "digsite:north",
   "24,10": "digsite:east",
   "10,20": "digsite:south"
  },
  "marks": {
   "18,7": "lm_field_jacket",
   "4,9": "decor:tent",
   "8,20": "decor:tent",
   "22,8": "decor:crates",
   "18,16": "decor:crates",
   "4,15": "decor:bench"
  },
  "finds": {
   "4,21": {
    "id": "fos_camp_beds",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "0,12": {
    "map": "route4",
    "x": 26,
    "y": 11
   },
   "13,0": {
    "map": "dig3",
    "x": 13,
    "y": 22
   },
   "27,12": {
    "map": "dig2",
    "x": 13,
    "y": 22
   },
   "13,23": {
    "map": "dig1",
    "x": 13,
    "y": 22
   }
  },
  "beyond": {},
  "land": [
   13,
   13
  ],
  "links": {},
  "gen": 12
 },
 "dig1": {
  "rows": [
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..ggggggggg^gg^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^g^GGGGggg..gggRggggg^g^^^",
   "^^^gGGGGGggg..ggggggggg^g^^^",
   "^^^gGGGGGggg..*gggggggggg^^^",
   "^^^ggggggggg..ggggggggg^g^^^",
   "^^^gggggRggg..gg*ggΩggggg^^^",
   "^^^ggggggggg..ggg.....ggg^^^",
   "^^^g^ggggggg..ggg.....ggg^^^",
   "^^^ggggggggg...gg.....*gg^^^",
   "^^^ggggggggg...ggggggggggg^^",
   "^^^g^gggggggg..ggggggggg^g^^",
   "^^^g^gggggggg..ggggggggggg^^",
   "^^^gggggggggg..g!ggg*gggg^^^",
   "^^gggggTggggg..ggggGGGGGg^^^",
   "^^g^gTggggggg..ggggGGGGGg^^^",
   "^^g^ggggggggg..ggggGGGG^g^^^",
   "^^ggggggggggg..*ggggggggg^^^",
   "^^gggg^gggggg..^g^^^g^ggg^^^",
   "^^^^^^^^^^^^g..^^^^^^^^^g^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "8,9": "dig1:2,2",
   "17,5": "dig1:6,2",
   "16,16": "dig1:8,3"
  },
  "marks": {
   "19,9": "lm_chirotherium"
  },
  "finds": {
   "4,3": {
    "id": "fos_d1_corner",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "digsite",
    "x": 13,
    "y": 21
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "dig1b",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig1b": {
  "rows": [
   "^^^ggggggggggg..ggggggggg^^^",
   "^^^ggggggggggg..ggggggggg^^^",
   "^^^ggggggggggg..gggggggggg^^",
   "^^^ggggggggggg..gggGGGGGgg^^",
   "^^^ggggggggggg..gggGGGGGgg^^",
   "^^^g^ggggggggg..gggGGGGGg^^^",
   "^^^ggggggggggg..ggggggggg^^^",
   "^^^ggggggggggg..Tgggggg^g^^^",
   "^^^ggggTΩggggg..Tgggggggg^^^",
   "^^g......................^^^",
   "^^^......................g^^",
   "^^^ggg*ggggg*g..Tggggggg*^^^",
   "^^^ggTgggggggg..gg!ggggggg^^",
   "^^^^gggggggggg..ggggggggg^^^",
   "^^^g^ggggggg....gggggggggg^^",
   "^^^ggggggggg....ggg*ggggg^^^",
   "^^gggggggggg..ggggggggggg^^^",
   "^^ggGGGGGg*g..ggggggggg^g^^^",
   "^^g^GGGGGggg..ggggggggggg^^^",
   "^^ggGGGGGggg..ggggggggggg^^^",
   "^^gggggggggg..ggggggggggg^^^",
   "^^gggggggggg..gggggggggggg^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..ggggggggggg^^^"
  ],
  "cast": {
   "18,12": "dig1b:8,2"
  },
  "marks": {
   "8,8": "lm_coelophysis"
  },
  "finds": {
   "23,19": {
    "id": "fos_d1b_wash",
    "item": "coins",
    "n": 400
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "dig1",
    "off": 0
   },
   "n": {
    "map": "dig1c",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig1c": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^^gg^^^^^^^^^^^gg^gg^^^^^^",
   "^^^ggggggggggggggggggggg^^^^",
   "^^^^gggggggggg*gggggggggg^^^",
   "^^^^ggggggggggggg*gggg^^gg^^",
   "^^^^g^ggggggggggggggggggg^^^",
   "^^^^ggWWWWWgggggggggggggg^^^",
   "^^^ggWWWWWWWggggΩggggggg^^^^",
   "^^^ggWWWWWWWggggggggggg*^^^^",
   "^^^ggWWWWWWWg.....ggggggg^^^",
   "^^^g^gWWWWWgggggggggggggg^^^",
   "^^^gggg*gggg!ggggggggggg^^^^",
   "^^^ggggggggggg..gggg*g^g^^^^",
   "^^gggggggggggg..gggggggg^^^^",
   "^^^ggggggggggg..gggggggg^^^^",
   "^^^ggggggggggg..ggWWWWWg^^^^",
   "^^^ggggggggggg..ggWWWWWg^^^^",
   "^^ggGGGGGggggg..ggWWWWWg^^^^",
   "^^^gGGGGGggggg..gggggggg^^^^",
   "^^^g^GGGGggggg..ggggggggg^^^",
   "^^^ggggggggggg..ggggggggg^^^",
   "^^^ggggggggggg..gggggggggg^^",
   "^^^ggggggggggg..ggggggggg^^^",
   "^^^ggggggggggg..ggggggggg^^^"
  ],
  "cast": {
   "12,11": "dig1c:7,3"
  },
  "marks": {
   "16,7": "lm_ichthyosaur"
  },
  "finds": {
   "4,3": {
    "id": "fos_d1c_shore",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   15,
   20
  ],
  "links": {
   "s": {
    "map": "dig1b",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig2": {
  "rows": [
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^ggggggggggg..gggggggggg^^^",
   "^^gggggggggg*..gggg*Tggg^^^^",
   "^^^ggGGGggggg..ggggggggg^^^^",
   "^^^gGGGGGgggg..g!ggggggg^^^^",
   "^^^g^GGGGgggg..gggggg⁂gT^^^^",
   "^^^^GGGGGgggg..ggggggggg^^^^",
   "^^^^gGGGGgggg..gggggg⁂gg^^^^",
   "^^^^^gggggggg..gggggggggg^^^",
   "^^^^g*ggggggg..ggggΩg⁂ggg^^^",
   "^^^^ggggggggg..*gggggggg^^^^",
   "^^^gggggggggg..gggggg⁂gg^^^^",
   "^^^^gggggRggg..ggggggggg^^^^",
   "^^^^ggggggggg..ggggg*⁂ggg^^^",
   "^^^^ggggggggg..gggggggg^g^^^",
   "^^^^GGGGGgggg..gggggggggg^^^",
   "^^^gGGGGGgggg..gggggggggg^^^",
   "^^^gGGGGGgggg..gggggggggg^^^",
   "^^^gggggggggg..gggggGGGggg^^",
   "^^^^ggggggggg..gggggggggg^^^",
   "^^^gggggg^^^^..ggggggggg^^^^",
   "^^^^^^^^^^^^^..^ggg^g^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "16,5": "dig2:8,3",
   "9,13": "dig2:4,6"
  },
  "marks": {
   "19,10": "lm_sauropod_tracks"
  },
  "finds": {
   "4,3": {
    "id": "fos_d2_ferns",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "digsite",
    "x": 26,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "dig2b",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig2b": {
  "rows": [
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^ggggggggg..ggggggggggg^^^^",
   "^^ggggggggg..ggggggggggg^^^^",
   "^^^gGGGGGgg..ggggggggggg^^^^",
   "^^ggGGGGGgg..gggggggggggg^^^",
   "^^^gGGGGGgg..ggggg....ggg^^^",
   "^^^gggggggg..ggg...Ω...ggg^^",
   "^^ggg*ggg*g..ggg.......gg^^^",
   "^^ggggggggg..ggg.......gg^^^",
   "^^gg*gggRgg..ggggg....ggg^^^",
   "^^ggggggggg..gggggggggggg^^^",
   "^^^gggggggg....gggggggRggg^^",
   "^^^^ggggggg....gggggggggg^^^",
   "^^^^ggggggggg..g!gggggggg^^^",
   "^^^^ggggggggg..gggggggggg^^^",
   "^^^^G^GGGgggg..gg*ggggg^gg^^",
   "^^^gGGGGGgggg..ggggggg^ggg^^",
   "^^^^GGGGGgggg..gggggggg^g^^^",
   "^^^^ggggggggg..ggggggggggg^^",
   "^^^ggggggRggg..ggggggTgggg^^",
   "^^^*ggggggggg..ggggggggggg^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^"
  ],
  "cast": {
   "16,14": "dig2b:8,2",
   "22,12": "dig2b:12,3",
   "8,10": "dig2b:6,5",
   "9,20": "dig2b:1,8"
  },
  "marks": {
   "19,7": "lm_archaeopteryx"
  },
  "finds": {
   "23,2": {
    "id": "fos_d2b_quarry",
    "item": "coins",
    "n": 420
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "dig2",
    "off": 0
   },
   "n": {
    "map": "dig2c",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig2c": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^^^^g^^^^^^^^^^^^^^^^^^^^^",
   "^^^gggggggggggg^ggg^^^gg^^^^",
   "^^^ggggggggggggggggg*ggg^^^^",
   "^^^ggggggggggggggggGGGGG^^^^",
   "^^^^ggggggggggggggggTggg^^^^",
   "^^^^g^ggggggggggggggggg^g^^^",
   "^^^gggggggg*gggggggTggggg^^^",
   "^^ggggggΩggggg*gggggggggg^^^",
   "^^^gggggggggggggggggTgg^g^^^",
   "^^^gggggggggggg!gggggggggg^^",
   "^^^ggggggggggggggggggggggg^^",
   "^^^gggRgggg..gggggggggggg^^^",
   "^^^gggggggg..gggggg....ggg^^",
   "^^^gg*ggggg..gggggg.WW.ggg^^",
   "^^^^g^ggggg..gggggg....gg^^^",
   "^^^gGGGGGgg..ggggggggggg^^^^",
   "^^^^GGGGGgg..ggggRggggggg^^^",
   "^^^gGGGGGgg..gggggggggg^g^^^",
   "^^^^ggggggg..gggggggggggg^^^",
   "^^^^ggggggg..gggggggg^^gg^^^",
   "^^^^ggggggg..g*gggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^"
  ],
  "cast": {
   "15,10": "dig2c:7,3",
   "17,17": "dig2c:8,4",
   "6,12": "dig2c:1,8"
  },
  "marks": {
   "8,8": "lm_amber"
  },
  "finds": {
   "4,3": {
    "id": "fos_d2c_resin",
    "item": "antidote",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   20
  ],
  "links": {
   "s": {
    "map": "dig2b",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig3": {
  "rows": [
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gg*ggggg..gggggggggggg^^^",
   "^^^gggggggg..ggggggggggggg^^",
   "^^^gggggggg..ggggggggg^gg^^^",
   "^^^gGGGGGgg..gg*ggggg*g^g^^^",
   "^^ggGGGGGgg..gggggggggggg^^^",
   "^^ggGGGGGgg..gggggggggggg^^^",
   "^^g^ggggggg..g*ggggΩggggg^^^",
   "^^ggggggggg..ggg.....ggggg^^",
   "^^^g^gggggg..ggg.....gggg^^^",
   "^^^gggggggg....gg....gggg^^^",
   "^^^gggggRgg....gggggggggg^^^",
   "^^^^gggggggg*..gggggggggg^^^",
   "^^^^g^ggggggg..gggggggggg^^^",
   "^^^^g^ggggggg..gggggggggg^^^",
   "^^^gggggggggg..g!ggggggg^^^^",
   "^^^gGGGGGgggg..gggggggggg^^^",
   "^^^g^GGGGgggg..gggggggggg^^^",
   "^^^gGGGGGgggg..gggggggTgg^^^",
   "^^^gggggggggg..gggggTggggg^^",
   "^^^gggggggg^g..ggggggg^^^^^^",
   "^^^^^^^^^^^^^..ggg^g^^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "8,12": "dig3:2,3",
   "16,16": "dig3:8,3"
  },
  "marks": {
   "19,8": "lm_ammonite"
  },
  "finds": {
   "4,3": {
    "id": "fos_d3_shells",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "digsite",
    "x": 13,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "dig3b",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig3b": {
  "rows": [
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggg*ggggg^^^",
   "^^^gggggggggg..gggggg*gggg^^",
   "^^^^GGGGGgggg..gRggggggggg^^",
   "^^^gGGGGGgggg..ggggggggggg^^",
   "^^^gGGGGGgggg..ggggggggggg^^",
   "^^^gggggggggg..gg.....⁅gg^^^",
   "^^^gggggggggg..g...Ω...ggg^^",
   "^^^g^gggggggg..g.......gg^^^",
   "^^^^ggggg**gg..g.......gg^^^",
   "^^^gggggRgggg..gg⁅...⁅^g^^^^",
   "^^^^ggggggggg..ggggggggg^^^^",
   "^^^gggggggggg..g!ggggggg^^^^",
   "^^^gggggggg....gggggggg^g^^^",
   "^^^gggggggg....gggggggggg^^^",
   "^^^g^gggggg..gggggggggggg^^^",
   "^^^gGGGGGgg..ggggggggg^gg^^^",
   "^^^g^GGGGgg..gggggggggggg^^^",
   "^^^g^GGGGgg..gggggggg^g^g^^^",
   "^^^^ggggggg..gggggggggggg^^^",
   "^^^gg*ggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^"
  ],
  "cast": {
   "16,4": "dig3b:8,1",
   "16,13": "dig3b:8,2",
   "8,11": "dig3b:1,8"
  },
  "marks": {
   "19,8": "lm_maiasaura"
  },
  "finds": {
   "24,3": {
    "id": "fos_d3b_nests",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "dig3",
    "off": 0
   },
   "n": {
    "map": "dig3c",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig3c": {
  "rows": [
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..gggggggggggg^^",
   "^^^ggggg*ggg..gggggggggggg^^",
   "^^^*gggggggg..gggggggTgggg^^",
   "^^^ggggggggg..ggggggTggggg^^",
   "^^^ggg...ggg..gggggggTggg^^^",
   "^^gg...Ω...g..gggg*gggggg^^^",
   "^^^g.......g..ggggggggggg^^^",
   "^^^g.......g..ggggggggggg^^^",
   "^^^gg.....gg..gg!gggGGGgg^^^",
   "^^gggggggggg..ggggggggggg^^^",
   "^^g^gggggggg...gggggg*ggg^^^",
   "^^^ggggggggg...gggggggg^g^^^",
   "^^^ggggggRggg..gggggggg^g^^^",
   "^^^gggggggggg..ggg.....ggg^^",
   "^^^gggggggggg..ggg.....gg^^^",
   "^^^g^GGGGgggg..ggg....ggg^^^",
   "^^^gGGGGGgggg..gggggggggg^^^",
   "^^^g^GGGGgggg..gggRgggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggg*g^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^"
  ],
  "cast": {
   "16,10": "dig3c:8,2",
   "18,19": "dig3c:13,3",
   "9,14": "dig3c:1,8"
  },
  "marks": {
   "7,7": "lm_ashfall"
  },
  "finds": {
   "24,3": {
    "id": "fos_d3c_ash",
    "item": "coins",
    "n": 440
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "dig3b",
    "off": 0
   },
   "n": {
    "map": "dig3d",
    "off": 0
   }
  },
  "gen": 12
 },
 "dig3d": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^^^^gg^^^^^^^^^^^^^^g^^^^^",
   "^^^ggggggggg*gggggggggggg^^^",
   "^^^ggggggggggggggggggggg^^^^",
   "^^^gggggggggggggggggg^gg^^^^",
   "^^^gggggggggggggggggg^^g^^^^",
   "^^^g*ggggggg*gggggggggggg^^^",
   "^^^ggggggggggggggggggggggg^^",
   "^^^gggggggggggggggggggggg^^^",
   "^^^^^.^^^^.^..^.^^^^.^^^^^^^",
   "^^^^ggggggggggggggΩggggg^^^^",
   "^^^ggTggg!ggggggggggggggg^^^",
   "^^^^gggTgggg..ggggggggggg^^^",
   "^^^ggggggggg..gggggggggg^^^^",
   "^^^ggTgggggg..gRggggggggg^^^",
   "^^^ggggggggg..ggggg*ggggg^^^",
   "^^^ggggggggg..ggggGGGGGg^^^^",
   "^^g*GGGGGggg..ggggGGGGGg^^^^",
   "^^^gGGGGGggg..ggggGGGGGgg^^^",
   "^^^gGGGGGggg..gggggggggg^^^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..gggggggggg^^^^",
   "^^^ggggggggg..ggggggggggg^^^",
   "^^^ggggggggg..ggggggggggg^^^"
  ],
  "cast": {
   "15,14": "dig3d:14,1",
   "9,11": "dig3d:7,3"
  },
  "marks": {
   "18,10": "lm_kpg_boundary"
  },
  "finds": {
   "4,4": {
    "id": "fos_d3d_last",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   20
  ],
  "links": {
   "s": {
    "map": "dig3c",
    "off": 0
   }
  },
  "gen": 12
 }
}, inbound: [
 {
  "from": "route4",
  "tile": "27,11",
  "map": "digsite",
  "x": 1,
  "y": 12
 }
] });
