// GENERATED by design/tools/forge_savanna.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "savanna", maps: {
 "town1": {
  "rows": [
   "TTTTTTTTTTTT....TTTTTTTTTTTT",
   "TTTTTTTTTTTT....TTTTTTTTTTTT",
   "TT........................TT",
   "TT.......g..!.......¡T....TT",
   "TT..¦.....g¦....¦....T....TT",
   "TT...H.g*.........*P.¡.*..TT",
   "TT.T..*...........R.......TT",
   "TT.T.....H....g........¦..TT",
   "TT..g....*................TT",
   "TT.........*..........H...TT",
   "TT.....*..**..............TT",
   "TT..gWWWg.................TT",
   "TT..gWWWg.................TT",
   "TT..gWWWg........g.........e",
   "TT..........g.............TT",
   "TT.......*............R...TT",
   "TT..¦.....C.......M.......TT",
   "TT..............g.........TT",
   "TT..R.....................TT",
   "TT..*...!..¦........¦...g.TT",
   "TT..............V.*.ggggg.TT",
   "TT.................g......TT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "12,3": "town1:8,2",
   "18,6": "town1:9,2",
   "4,18": "town1:3,8",
   "22,15": "town1:16,8",
   "16,20": "town1:9,10",
   "8,19": "town1:8,12"
  },
  "exits": {
   "27,13": {
    "map": "archive",
    "x": 7,
    "y": 1
   }
  },
  "land": [
   6,
   19
  ],
  "links": {
   "n": {
    "map": "route1",
    "off": 0
   }
  },
  "gen": 1
 },
 "route1": {
  "rows": [
   "TTTTT....TTTTTTTTTTTTTTTTTTT",
   "TTTTT....TTTTTTTTTTTTTTTTTTT",
   "TT.T................T....TTT",
   "TT.....................T..TT",
   "TTTTTTVTTTTTTTTTTTTTTTTTTTTT",
   "TT....*.......*..GGGGGG...TT",
   "TT.............GGGGGGGGG..TT",
   "TT......⁌.....GGGGGGGGGGG.TT",
   "TTT...........GGGGGGGGGGG.TT",
   "TT........GGGGGGGGGGGGGGG.TT",
   "TT........GGGGGGGGGGGGGG..TT",
   "TT*.......GGGGG.RGGGGGGT..TT",
   "TT.¡.................T....TT",
   "TT...*...R.........T.*...TTT",
   "TT................*...¦T..TT",
   "TT...........*.........T..TT",
   "TT.............⁂.GGGGGGG..TT",
   "TT.GGG..........GGGGGGGGG.TT",
   "TT.GGG..........GGGGGGGGG.TT",
   "TT.GGG....⁃.....GGGGGGGGG.TT",
   "TT.GGG.....R.....GGGGGGG..TT",
   "TT.GGG...*⁃............T..TT",
   "TTTTTTTTTTTT....TTTTTTTTTTTT",
   "TTTTTTTTTTTT....TTTTTTTTTTTT"
  ],
  "cast": {
   "6,4": "route1:7,1",
   "11,20": "route1:5,12",
   "9,13": "route1:4,4",
   "16,11": "route1:11,10"
  },
  "exits": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "town1",
    "off": 0
   },
   "n": {
    "map": "seg_m1",
    "off": 0
   }
  },
  "gen": 1
 },
 "seg_m1": {
  "rows": [
   "TTTTTTTTTTTTTTTTTT....TTTTTT",
   "TTTTTTTTTTTTTTTTTT....TTTTTT",
   "TT*.......T...............TT",
   "TTTggggg.........R...GGG..TT",
   "TT.gWWWg...GGGGG....GGGGG.TT",
   "TT.gWWWg...GGGGG....GGGGG.TT",
   "TT.gWWWg...GGGGG....GGGGG.TT",
   "TT..gggg...T..TT....GGGGG.TT",
   "TT.......TT....⁂....GGGGG.TT",
   "TT.....T.R..T....T...GGG..TT",
   "TT.......T...........¦.T..TT",
   "TT.T......................TT",
   "TT........................TT",
   "TT..T.................T...TT",
   "TT.....................RT.TT",
   "TT.............T.TT.......TT",
   "TTTR......GGGGG........*..TT",
   "TT.......GGGGGGG....T.....TT",
   "TT..*....GGGGGGG..........TT",
   "TT.......GGGGGGG.**...T.¡.TT",
   "TT........⁃GGGGT..T..*....TT",
   "TT..T....T.R..............TT",
   "TTTTT....TTTTTTTTTTTTTTTTTTT",
   "TTTTT....TTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "3,16": "seg_m1:1,5",
   "23,14": "seg_m1:13,5",
   "17,3": "seg_m1:6,1",
   "9,9": "seg_m1:6,7",
   "11,21": "seg_m1:6,10"
  },
  "exits": {},
  "land": [
   7,
   21
  ],
  "links": {
   "s": {
    "map": "route1",
    "off": 0
   },
   "n": {
    "map": "seg_m2",
    "off": 0
   }
  },
  "gen": 1
 },
 "seg_m2": {
  "rows": [
   "TTTTTTTTTTT....TTTTTTTTTTTTT",
   "TTTTTTTTTTT....TTTTTTTTTTTTT",
   "TT..T......*.......WWW....TT",
   "TT..GGGGGR.........WWW....TT",
   "TT.GGGGGGG........!..GGG.*TT",
   "TT*GGGGGGG...*......GGGGG.TT",
   "TTTGGGGGGG.........GGGGGGGTT",
   "TTT.GGGGG.....*....GGGGGGGTT",
   "TT...............*.GGGGGGGTT",
   "TT..⁃..........R...GGGGGGGTT",
   "TT*................GGGGGGGTT",
   "e.*.....*..........GGGGGG.TT",
   "T..............*.....GGGG.TT",
   "TT................**......TT",
   "TT....T..R*.*.........R.*.TT",
   "TT........*...............TT",
   "TT..GGGGG.....*.*.........TT",
   "TT.GGGGGGG..............¡.TT",
   "TT.GGGGGGG......⁂.........TT",
   "TT.GGGGGGG................TT",
   "TTT*GGGGG.......GGG..*.T.TTT",
   "TT.*..T....*.........!....TT",
   "TTTTTTTTTTTTTTTTTT....TTTTTT",
   "TTTTTTTTTTTTTTTTTT....TTTTTT"
  ],
  "cast": {
   "21,21": "seg_m2:7,4",
   "18,4": "seg_m2:7,3",
   "15,9": "seg_m2:9,4",
   "9,14": "seg_m2:5,7",
   "22,14": "seg_m2:9,7",
   "9,3": "seg_m2:4,3"
  },
  "exits": {
   "0,11": {
    "map": "shrine_bramwold",
    "x": 7,
    "y": 8
   }
  },
  "land": [
   20,
   21
  ],
  "links": {
   "s": {
    "map": "seg_m1",
    "off": 0
   },
   "n": {
    "map": "seg_m3",
    "off": 0
   }
  },
  "gen": 1
 },
 "seg_m3": {
  "rows": [
   "TTTT....TTTTTTTTTTTTTTTTTTTT",
   "TTTT....TTTTTTTTTTTTTTTTTTTT",
   "TT........................TT",
   "TT.....*.........*...T...TTT",
   "TT....*.......GGGGGGGG....TT",
   "TT........⁂...GGGGGGGGGG..TT",
   "TT...........GGGGGGGGGGGT.TT",
   "TT............GGGGGGGGGG..TT",
   "TT.....*.......GGGGGGG....TT",
   "TT......R........T..TT..T.TT",
   "TT..............R.T.......TT",
   "TT........................TT",
   "TT¡T¡..¡¡T¡¡T¡¡T¡¡T¡¡T¡¡T¡TT",
   "TT..............*....T....TT",
   "TT...............T........TT",
   "TT....................WWW.TT",
   "TT..*...........GGGGGGWWW.TT",
   "TT.R...........GGGGGGGGG..TT",
   "TT......GGG....GGGGGGGGG..TT",
   "TT......GGG....GGGGGGGGG..TT",
   "TT......GGG.*..⁃.GGGGGG...TT",
   "TT.............TR..*..T...TT",
   "TTTTTTTTTTT....TTTTTTTTTTTTT",
   "TTTTTTTTTTT....TTTTTTTTTTTTT"
  ],
  "cast": {
   "8,9": "seg_m3:4,4",
   "3,17": "seg_m3:3,4",
   "16,10": "seg_m3:11,4",
   "16,21": "seg_m3:5,10"
  },
  "exits": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "seg_m2",
    "off": 0
   },
   "n": {
    "map": "seg_m4",
    "off": 0
   }
  },
  "gen": 1
 },
 "seg_m4": {
  "rows": [
   "TTTTTTTTTTTTTTTT....TTTTTTTT",
   "TTTTTTTTTTTTTTTT....TTTTTTTT",
   "TT...........*............TT",
   "TT.....GGGGGGG..........^.TT",
   "TT....GGGGGGGGR*....*....^TT",
   "TT.^*..GGGGGGG..........*.TT",
   "TT...................⁃....TT",
   "TT...*...⁌........*.......TT",
   "TT.......*.*..........R⁃..TT",
   "e.......**..............*.TT",
   "T..............*...*⁃.GGG.TT",
   "TT........*..........GGGGGTT",
   "TT......R..........*RGGGGGTT",
   "TT.WW..*..*..........GGGGGTT",
   "TT.WW........⁂...*...GGGGGTT",
   "TT.................!.GGGGGTT",
   "TT...........*...*...GGGGGTT",
   "TT............*.....*.GGGGTT",
   "TT.......*............GGG.TT",
   "TT.....*GGGGR.............TT",
   "TT.¡.*..GGGGG.*...........TT",
   "TT......GGGGG.*.*.........TT",
   "TTTT....TTTTTTTTTTTTTTTTTTTT",
   "TTTT....TTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "22,8": "seg_m4:13,8",
   "20,12": "seg_m4:1,3",
   "8,12": "seg_m4:1,4",
   "12,19": "seg_m4:14,4",
   "14,4": "seg_m4:6,2",
   "19,15": "seg_m4:7,3"
  },
  "exits": {
   "0,9": {
    "map": "shrine_myrmedon",
    "x": 7,
    "y": 8
   }
  },
  "land": [
   6,
   21
  ],
  "links": {
   "s": {
    "map": "seg_m3",
    "off": 0
   },
   "n": {
    "map": "seg_m5",
    "off": 0
   }
  },
  "gen": 1
 },
 "seg_m5": {
  "rows": [
   "TTTTTTTTTTTT....TTTTTTTTTTTT",
   "TTTTTTTTTTTT....TTTTTTTTTTTT",
   "TT..g.............*...g...TT",
   "TT...........g..!...GGGG..TT",
   "TT..GGGGGT..........GGGGG.TT",
   "TT..GGGGG...........GGGGG.TT",
   "TT..GGGGG...........GGGGG.TT",
   "TT........¡.......g..GGGG.TT",
   "TT..........g...*....R....TT",
   "TT....g.................g.TT",
   "TT**T...................*.TT",
   "TT...R..T.............T...TT",
   "TT........................TT",
   "TT*.................⁂.....TT",
   "TT....GGGG.............g..TT",
   "TT..GGGGGGGR....g.....WW..TT",
   "TT..GGGGGGG.........*.WW..TT",
   "TT.⁃GGGGGGG...........WW..TT",
   "TT..GGGGGGG...............TT",
   "TT...GGGGGG....*....T.*...TT",
   "TT...GGGG...............T.TT",
   "TT...............g........TT",
   "TTTTTTTTTTTTTTTT....TTTTTTTT",
   "TTTTTTTTTTTTTTTT....TTTTTTTT"
  ],
  "cast": {
   "16,3": "seg_m5:7,4",
   "11,15": "seg_m5:5,8",
   "21,8": "seg_m5:11,8",
   "5,11": "seg_m5:3,10"
  },
  "exits": {},
  "land": [
   18,
   21
  ],
  "links": {
   "s": {
    "map": "seg_m4",
    "off": 0
   },
   "n": {
    "map": "town2",
    "off": 0
   }
  },
  "gen": 1
 },
 "town2": {
  "rows": [
   "TTTTTTTTTTTTTnTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTT.TTTTTTTTTTTTTT",
   "TT..........TXT...........TT",
   "TT...................*....TT",
   "TT..g..*..g¦....¦......*g.TT",
   "TT...............Y........TT",
   "TT..............R.....g..*TT",
   "TT.........!..............TT",
   "TT........................TT",
   "TT......C.................TT",
   "TT..¦..R..............¦...TT",
   "TT...............*........TT",
   "e...................*.....TT",
   "TT........................TT",
   "TT................V.......TT",
   "TT..¦......*g...*.*M......TT",
   "TT...............g*.......TT",
   "TT.*................*...*.TT",
   "TT....H....¦....¦.........TT",
   "TT................g.gWWWg.TT",
   "TT.........!........gWWWg.TT",
   "TT...*..............ggggg.TT",
   "TTTTTTTTTTTT....TTTTTTTTTTTT",
   "TTTTTTTTTTTT....TTTTTTTTTTTT"
  ],
  "cast": {
   "11,7": "town2:9,3",
   "11,20": "town2:8,12",
   "7,10": "town2:3,8",
   "18,14": "town2:9,10",
   "16,6": "town2:13,11"
  },
  "exits": {
   "13,0": {
    "map": "route2",
    "x": 7,
    "y": 14
   },
   "0,12": {
    "map": "hearthgate",
    "x": 7,
    "y": 8,
    "req": "champion",
    "reqMsg": "🏡 A breeder's gate, latched. \"Hearthside is for Champions — folks who've met enough wild animals to think properly about the tame ones. Come back after the Citadel.\""
   }
  },
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "seg_m5",
    "off": 0
   }
  },
  "gen": 1
 }
}, inbound: [
 {
  "from": "archive",
  "tile": "7,0",
  "map": "town1",
  "x": 26,
  "y": 13
 },
 {
  "from": "shrine_bramwold",
  "tile": "7,9",
  "map": "seg_m2",
  "x": 1,
  "y": 11
 },
 {
  "from": "shrine_myrmedon",
  "tile": "7,9",
  "map": "seg_m4",
  "x": 1,
  "y": 9
 },
 {
  "from": "hearthgate",
  "tile": "7,9",
  "map": "town2",
  "x": 1,
  "y": 12
 },
 {
  "from": "route2",
  "tile": "7,15",
  "map": "town2",
  "x": 13,
  "y": 1
 }
] });
