// GENERATED by design/tools/forge_grove.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "grove", maps: {
 "route8": {
  "rows": [
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..g**gTggggggTTT",
   "TTTgggTggggg..gTgggggggggTTT",
   "TTTgTgggg⁄gg..gggggggggggTTT",
   "TTgTGGGGGggg..gggggTRggg^TTT",
   "TTggGGGGGggg..gggggggg*ggTTT",
   "TTTgGGGGGggg..gggggGGGGGgTTT",
   "TTTgggggRggg..gggggGGGGGg^TT",
   "TTTggggggggg..gggggGGGGGgTTT",
   "TTT!gggggggg..g*gggggTgg^TTT",
   "e.............ggggggggggTTTT",
   "T.............ggggggggTTTTTT",
   "TTTggggggggg..ggRgggggggTTTT",
   "TTTgggggTggg..ggggggggTgTTTT",
   "TTgggggggTgg...*gg*ggg*gTTTT",
   "TTTgTggggggg...ggggΩggggTTTT",
   "TTTgGGGGGgggg..g¡¡¡g¡¡¡g^TTT",
   "TTT*GGGGGgggg..ggg*ggggggTTT",
   "TTTgGGGGGgg*g..ggggggggggTTT",
   "TTTg....ggggg..⁅gggggggggTTT",
   "TTTg.WW.ggggg..gggggGGGggTTT",
   "TTTg....ggggg..ggggggggggTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "3,10": "route8:gate",
   "8,8": "route8:4,4",
   "16,13": "route8:5,10",
   "20,5": "route8:11,10"
  },
  "marks": {
   "19,16": "lm_nurse_log"
  },
  "finds": {
   "23,18": {
    "id": "grv_r8_log",
    "item": "berries",
    "n": 3
   },
   "3,3": {
    "id": "grv_r8_corner",
    "item": "coins",
    "n": 260
   }
  },
  "exits": {
   "0,11": {
    "map": "taiga",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "seg_g1",
    "off": 0
   },
   "s": {
    "map": "town8",
    "off": 0
   }
  },
  "gen": 9
 },
 "seg_g1": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..gggggggggTTT",
   "TTTgGGGGGggggg..ggggggRggTTT",
   "TTTTGTGGGggggg..gggGGGGGgTTT",
   "TTT⁅GGGGGg⁄ggg..gggGGGGGgTTT",
   "TTTggggTgggggg..gggGGGGTgTTT",
   "TTTgTggggg*ggg..Rgg*ggggg^TT",
   "TTTgTg*gg*gggg..gggTgggggTTT",
   "TTTgTgggΩg*ggg..gTgggggggTTT",
   "TTTTgggggggggg..TggggggggTTT",
   "TTTggggggggggg..ggggWggggTTT",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "TTTgTggggggggg..ggggggggWTTW",
   "TTTggRggg*gggg..ggggg*gggTTT",
   "TTTggggggggg....ggggggTggTTT",
   "TTTggggggRgg....gggggTgggTTT",
   "TTTgGGGGGggg..ggggRGGGGGgTTT",
   "TTTTGGGGGggg..gggggGGGGGgTTT",
   "TTTgGGGGGTgg..gggggGGGGGgTTT",
   "TTTggggTgggg..*gg¡gg*ggg*TTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "22,3": "seg_g1:14,2",
   "16,7": "seg_g1:7,6",
   "9,17": "seg_g1:7,8",
   "5,15": "seg_g1:3,10",
   "18,18": "seg_g1:11,10"
  },
  "marks": {
   "8,9": "lm_foxfire"
  },
  "finds": {
   "4,3": {
    "id": "grv_g1_corner",
    "item": "treats",
    "n": 2
   },
   "24,9": {
    "id": "grv_g1_stream",
    "item": "wakeberry",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "route8",
    "off": 0
   },
   "n": {
    "map": "seg_g2",
    "off": 0
   }
  },
  "gen": 9
 },
 "seg_g2": {
  "rows": [
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTTgggggggg..ggg*ggggggggg^T",
   "TTTgGGGGG⁄g..gggRgggggggggTT",
   "T^ggGGGGGgg..ggggggTTTTggTTT",
   "TTTgGGGGGgg..gggggTTTTTTgTTT",
   "TTTgTgggggg..gggggTTTTgTgTTT",
   "TTT*ggggRgg..ggggggggg*ggTTT",
   "TT^ggTTTgg*..gggggggg*gTgTTT",
   "TTTgTTTTg*g..ggggggggggggTTT",
   "TTTggTTTggg..ggggggΩgggggTTT",
   "TTTTgTTTggg..ggggggggggggTTT",
   "TTTTTgTgggg..ggggRgggggggTTT",
   "TTgTggggggg..gggggggGGGggTTT",
   "TTggggggggg.....gggggggTgTTT",
   "TTggg....gg.....gggggTTTgTTT",
   "TTggg.WW.ggggg..⁅ggggTTTgTTT",
   "TTggg....Rgggg..gggggTTTggTT",
   "TTgggggggggg*g..gRggg*gggg^T",
   "TTTgTgggggggg*..ggGGGGGgggTT",
   "TTTgg*TTTggggg..ggTGGGGggg^T",
   "TTTg¡gg*ggggg*..ggGGGGGggggT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "16,3": "seg_g2:6,1",
   "8,7": "seg_g2:3,3",
   "17,12": "seg_g2:10,3",
   "9,17": "seg_g2:1,5",
   "17,18": "seg_g2:13,5"
  },
  "marks": {
   "19,10": "lm_fungal_web"
  },
  "finds": {
   "24,10": {
    "id": "grv_g2_roots",
    "item": "antidote",
    "n": 1
   },
   "4,3": {
    "id": "grv_g2_corner",
    "item": "coins",
    "n": 270
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_g1",
    "off": 0
   },
   "n": {
    "map": "seg_g3",
    "off": 0
   }
  },
  "gen": 9
 },
 "seg_g3": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTT^ggggggggg..ggggggggggTTT",
   "TTTTGGGGGgggg..ggggggggRgTTT",
   "TTTgGGGGGgggg..TgggGGGGGTTTT",
   "TTTgGGGGG⁄ggg..gTggGGGGGTTTT",
   "TTTgggggggggg..ggggGGGGGTTTT",
   "TTT!ggg*gg*gg..gggggggggTTTT",
   "e..............ggg*ggggggTTT",
   "T..............ggggggggTgTTT",
   "TTTggggRggggg..gggggggTggTTT",
   "TTTgggggggggg..ggRgggggggTTT",
   "TTgg¡ggTggggg..gg*....ΩggTTT",
   "TTggggggTgggg..gg*.....ggTTT",
   "TTgggggggTg....ggg.....gg^TT",
   "TTTgg*ggggg....ggggggggggTTT",
   "TTTggggRggg..ggggggggggg^TTT",
   "TTggGGGGGgg..gggggRggggggTTT",
   "TTTgGGGGGgg..ggg*ggggggTgTTT",
   "TTTgGGGGGg*..gggggggggg*ggTT",
   "TTTgggTgggg..ggg⁅gGGGGGggTTT",
   "TTgggggTggg..ggg**gggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "3,7": "seg_g3:gate",
   "7,10": "seg_g3:4,3",
   "23,3": "seg_g3:14,3",
   "17,11": "seg_g3:9,4",
   "18,17": "seg_g3:5,7",
   "7,16": "seg_g3:9,7"
  },
  "marks": {
   "22,12": "lm_owl_pellet"
  },
  "finds": {
   "24,14": {
    "id": "grv_g3_glade",
    "item": "bigberries",
    "n": 1
   },
   "4,3": {
    "id": "grv_g3_corner",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_nyxfang",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "seg_g2",
    "off": 0
   },
   "n": {
    "map": "seg_g4",
    "off": 0
   }
  },
  "gen": 9
 },
 "seg_g4": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTgGGGGGg⁄gg..gggggGGGggTTT",
   "TTTgTGGGGgggg..gggRgg*gggTTT",
   "TTTgGGGGGgggg..ggggggggggTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgg*g*Rgggg..gggggΩggggTTT",
   "TTgg*ggggggg*...gggggggggTTT",
   "TTTgggTTggTgg...gggggggggTTT",
   "TTTgTggggggggg..ggggggggggTT",
   "TTTgggggg*gggg..gggggTTgggTT",
   "TTgg¡ggggggggg..ggg....gggTT",
   "TTgggggggggg*g..ggg.WW.gggTT",
   "TTgTg*gggggggg..ggg....ggTTT",
   "TTTggggggRggg...*ggggggggTTT",
   "TTTgggggggggg...gggGGGGGgTTT",
   "TTTgGGGGGgggg..ggggGGGGGgTTT",
   "TTTTGGGGGgggg..gg⁅gGGGGGgTTT",
   "TTTgGGGGGgggg..ggTgggggg*TTT",
   "TTTgTggggg*gg..gggggggggggTT",
   "TTTTggTgggg*g..ggggTggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "8,7": "seg_g4:3,4",
   "18,4": "seg_g4:11,4",
   "9,15": "seg_g4:6,7"
  },
  "marks": {
   "20,7": "lm_woodpecker_tree"
  },
  "finds": {
   "24,8": {
    "id": "grv_g4_snag",
    "item": "berries",
    "n": 3
   },
   "4,21": {
    "id": "grv_g4_south",
    "item": "coins",
    "n": 280
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_g3",
    "off": 0
   },
   "n": {
    "map": "town9",
    "off": 0
   }
  },
  "gen": 9
 },
 "town9": {
  "rows": [
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTTTggggggggg..!ggggggggTTTT",
   "TTTTggggggggg..gggggggggTTTT",
   "TTTTHTgggCggg..gggYggggHTTTT",
   "TTTTggggggggg..gggggggggTTTT",
   "TTTTggg¦............¦gTTTTTT",
   "TTTTggg.Ω............gggTTTT",
   "TTTTggg.........Ω....gggTTTT",
   "TTTTggg...Ω..........gTgTTTT",
   "TTTTggg.R............gggTTTT",
   "TTTTHgg.........Ω....g*HTTTT",
   "TTTTggg¦...Ω........¦*ggTTTT",
   "TTTT!ggg*gggg..ggVggggggTTTT",
   "TTTTg¦ggggggg..ggggggg¦gTTTT",
   "e........................TTT",
   "T........................TTT",
   "TTT^ggg*ggg¦g..g¦g*ggΩ*gTTTT",
   "TTTTgg!gg*ggg..ggggM*gggTTTT",
   "TTTTgggggHggg..gggg*ggggTTTT",
   "TTTTTTΩgggg*!..ggΩΩggggHTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "15,3": "town9:gate",
   "4,14": "town9:gate2",
   "12,21": "town9:9,3",
   "6,19": "town9:8,12",
   "8,11": "town9:3,8",
   "17,14": "town9:9,10"
  },
  "marks": {
   "10,10": "lm_ancient_oak",
   "16,9": "decor:stall",
   "16,12": "decor:stall",
   "11,13": "decor:bench",
   "8,8": "decor:bench",
   "21,18": "decor:crates",
   "6,21": "decor:woodpile",
   "17,21": "decor:garden",
   "18,21": "decor:garden"
  },
  "finds": {
   "23,13": {
    "id": "grv_t9_oak",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "0,16": {
    "map": "vigil",
    "x": 7,
    "y": 8,
    "req": "champion",
    "reqMsg": "🕯️ A keeper in grey stands in the doorway. \"The Vigil is not a trophy hall, ranger. Come back when you've finished the trail — and come back ready to be sad for a while.\""
   }
  },
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_g4",
    "off": 0
   },
   "n": {
    "map": "route9",
    "off": 0
   }
  },
  "gen": 9
 },
 "route9": {
  "rows": [
   "TTTTTTTTTTTTTnTTTTTTTTTTTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggg!g..ggggggg*gTTTT",
   "TTTTgggggggg...ggg^gggggTTTT",
   "TTTTgggggggg...gggggggggTTTT",
   "TTTTgT^^gggg..ggRgggg^^gTTTT",
   "TTTTgggggggg..ggggggggggTTTT",
   "TTTTgggggggg..ggggggggggTTTT",
   "TTTTgggggggg..gggggGGGggTTTT",
   "TTT^g^gg*Rgg..ggggggg*ggTTTT",
   "TTTTgggggggg..gggggggggg^TTT",
   "TTTTgggggggg..*gggggggTgTTTT",
   "TTTTGGGGGggg..gggggΩggggTTTT",
   "TTTTGGGGGggg..ggggggggggTTTT",
   "TTT^GGGGGggg..ggggggggggTTTT",
   "TTTTgggggggg...gggggggTgTTTT",
   "TTTTg*gggggg...gggggggggTTTT",
   "TTT^g^ggggggg..gRgggg^ggTTTT",
   "TTTTgTg^gg*gg..gggggggggTTTT",
   "TTTT*gggg⁂g*g..gggggg^ggTTTT",
   "TTTTggggggggg..gggggggggTTTT",
   "TTTTggggggggg..gggggGGGgTTTT",
   "TTTTggggggggg..gggggggggTTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "11,2": "route9:gate",
   "9,9": "route9:4,4",
   "16,17": "route9:3,10",
   "16,5": "route9:11,10"
  },
  "marks": {
   "19,12": "lm_lichen"
  },
  "finds": {
   "23,4": {
    "id": "grv_r9_rocks",
    "item": "revives",
    "n": 1
   },
   "4,20": {
    "id": "grv_r9_south",
    "item": "coins",
    "n": 300
   }
  },
  "exits": {
   "13,0": {
    "map": "summit",
    "x": 7,
    "y": 13
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "town9",
    "off": 0
   }
  },
  "gen": 9
 }
}, inbound: [
 {
  "from": "taiga",
  "tile": "7,9",
  "map": "route8",
  "x": 1,
  "y": 11
 },
 {
  "from": "shrine_nyxfang",
  "tile": "7,9",
  "map": "seg_g3",
  "x": 1,
  "y": 8
 },
 {
  "from": "vigil",
  "tile": "7,9",
  "map": "town9",
  "x": 1,
  "y": 16
 },
 {
  "from": "summit",
  "tile": "7,14",
  "map": "route9",
  "x": 13,
  "y": 1
 }
] });
