// GENERATED by design/tools/forge_hearth.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "hearth", maps: {
 "hearthgate": {
  "rows": [
   "^^^^^^^^n^^^^^^^^^^n^^^^^^^^",
   "^^^^^^^^..ggggggggg..^^^^^^^",
   "^^^^gggg..ggggggggg..g^ggg^^",
   "^^gggg^g.............!gggg^^",
   "^^gggg*!.............ggggg^^",
   "^^gggg^gggggg..ggggggggggg^^",
   "^^gggggggRggg..*ggg*ggggg^^^",
   "^^gggHggggggg..gggggggH^g^^^",
   "^^^*ggggggggg..gΩgggggggg^^^",
   "^^g^ΩΩgggg!gg..ggggggggΩgg^^",
   "^^ggggggggggg..g!gggggggg^^^",
   "^^^!ggggggg*g..ggggggggg!^^^",
   "e..........................e",
   "^..........................^",
   "^^gggggg*gggg..gggggggg^g^^^",
   "^^gggggggg!gg..g!gggg*ggg^^^",
   "^^gggggCggggg..gggggMgggg^^^",
   "^^ggggggggggg..g*gggggggg^^^",
   "^^^gg....gggg..g*ggggggggg^^",
   "^^^g^.WW.ggΩg..gΩgggggggg^^^",
   "^^^gg....gggg..gggggg^gg^^^^",
   "^^^gggggggggg..g*^^^g^ggg^^^",
   "^^^^g^^^^^^^^..^^^^^^^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "10,9": "hearthgate:4,1",
   "16,10": "hearthgate:11,1",
   "10,15": "hearthgate:4,7",
   "16,15": "hearthgate:11,7",
   "9,6": "hearthgate:2,2",
   "3,11": "hearth:west",
   "24,11": "hearth:east",
   "7,4": "hearth:nw",
   "21,3": "hearth:ne"
  },
  "marks": {
   "16,8": "lm_first_dog",
   "11,19": "decor:bench",
   "16,19": "decor:bench",
   "4,9": "decor:garden",
   "5,9": "decor:garden",
   "23,9": "decor:doghouse"
  },
  "finds": {
   "4,21": {
    "id": "hth_hub_pond",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "0,12": {
    "map": "cattery1",
    "x": 13,
    "y": 22
   },
   "27,12": {
    "map": "kennel1",
    "x": 13,
    "y": 22
   },
   "8,0": {
    "map": "cattery3",
    "x": 13,
    "y": 22
   },
   "19,0": {
    "map": "kennel4",
    "x": 13,
    "y": 22
   },
   "13,23": {
    "map": "town2",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 14
 },
 "cattery3": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^^^^^^^gggg^^^^^^^^^^^^^^^",
   "^^^*gggggg*ggggg*gggggg^^^^^",
   "^^^ggggggggggggggggggggg^^^^",
   "^^^^g^ggggggggggggggggggg^^^",
   "^^^^GGGGGggggggggggg^ggg^^^^",
   "^^^*GGGGGgg*gggg*gggggggg^^^",
   "^^^gGGGGGgggggggggggggggg^^^",
   "^^^gggggggggg..gggΩggggg^^^^",
   "^^^gggggg!ggg..gggggggggg^^^",
   "^^ggggggggggg..ggggggggg^^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggΩg^g^^^^",
   "^^^ggggΩggggg..ggggggggg^^^^",
   "^^^gggg^ggggg..gg!gggggg^^^^",
   "^^^g^gg^ggggg..ggggggggg^^^^",
   "^^^gggggggggg..ggggGGGGGg^^^",
   "^^^^gggg^g*gg..ggggGGGGGg^^^",
   "^^^^ggggggggg..ggggGGGGGg^^^",
   "^^^^ggggggggg..ggggggg^g^^^^",
   "^^^^ggggggggg..gggggggggg^^^",
   "^^^^ggggggggg..^ggg^ggggg^^^",
   "^^^^g^^^^^^^^..^^^^^^^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "9,9": "cattery3:7,3",
   "17,14": "cattery3:7,7"
  },
  "marks": {
   "18,8": "lm_serval",
   "20,12": "decor:cattree",
   "7,13": "decor:cattree"
  },
  "finds": {
   "4,3": {
    "id": "hth_c3_perch",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "hearthgate",
    "x": 8,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {},
  "gen": 14
 },
 "cattery1": {
  "rows": [
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..ggggggggg^^^^",
   "^^ggggggggggg..ggggggggg^^^^",
   "^^g^gggggggg*..gggggggg^^^^^",
   "^^gggg*gggggg..ggggggggg^^^^",
   "^^ggggggggggg..gggggggggg^^^",
   "^^ggg.Ω...ggg..gggggΩgggg^^^",
   "^^^gg.....ggg..gggggggggg^^^",
   "^^^^*....gggg..gggΩggggg^^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^g**ggg!ggg..gggggggggg^^^",
   "^^^gggggggggg..ggggggggg^^^^",
   "^^^^ggggggggg..ggggggggg^^^^",
   "^^^^ggggggggg..gggggggggg^^^",
   "^^^^g^gggggg*..gg!gggggggg^^",
   "^^^^^gggggggg..gg.....g^g^^^",
   "^^^^*g^gggggg..gg.....ggg^^^",
   "^^^^gggggRggg..gg.....ggg^^^",
   "^^^gggggggggg..g*ggggg*gg^^^",
   "^^^gggggΩgggg..ggggggggggg^^",
   "^^^gg*ggggggg..ggggg^^gggg^^",
   "^^^^g^^gg^ggg..gg^^^^^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "9,11": "cattery1:7,3",
   "17,15": "cattery1:7,7",
   "9,18": "cattery1:13,8"
  },
  "marks": {
   "18,9": "lm_cyprus_cat",
   "6,7": "decor:cattree",
   "20,7": "decor:cattree",
   "8,20": "decor:bench"
  },
  "finds": {
   "24,21": {
    "id": "hth_c1_sun",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "hearthgate",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "cattery2",
    "off": 0
   }
  },
  "gen": 14
 },
 "cattery2": {
  "rows": [
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^g^gggggg..gggggggggggg^^^",
   "^^^gg^ggggg..ggggRgggggg^^^^",
   "^^^g^gggggg..gggggggggggg^^^",
   "^^^g*gggggg..gggggggggggg^^^",
   "^^^gggg***g..ggggggggggg^^^^",
   "^^^g^gggggg..gggggΩgggggg^^^",
   "^^^gggRgggg..gggggg*ggggg^^^",
   "^^^gggggggg..ggggggggggg^^^^",
   "^^^^ggggggg..ggggggggggg^^^^",
   "^^^gggggggg....ggggggRggg^^^",
   "^^^g^gggggg....gggggggggg^^^",
   "^^^^gg*g!gggg..*ggggggggg^^^",
   "^^^^ggggggggg..ggggggggg*^^^",
   "^^^g^ggggggg*..g!gg^g*^gg^^^",
   "^^^gggggggggg..gggg^ggggg^^^",
   "^^^^ggggggggg..ggggggggggg^^",
   "^^^^g^gΩggggg..ggggggggggg^^",
   "^^^gggggggggg..ggggggggggg^^",
   "^^^gggggggggg..gggggΩggggg^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^"
  ],
  "cast": {
   "17,4": "cattery2:9,1",
   "6,9": "cattery2:1,3",
   "8,14": "cattery2:7,3",
   "16,16": "cattery2:7,7",
   "21,12": "cattery2:14,8"
  },
  "marks": {
   "18,8": "lm_fel_d_1",
   "7,19": "decor:cattree",
   "20,21": "decor:bench"
  },
  "finds": {
   "4,21": {
    "id": "hth_c2_coats",
    "item": "coins",
    "n": 500
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "cattery1",
    "off": 0
   },
   "n": {
    "map": "cattery4",
    "off": 0
   }
  },
  "gen": 14
 },
 "cattery4": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^g^^^^^^ggggg^g^^^^^^^^^^^",
   "^^^ggggggggggggggggg*gggg^^^",
   "^^^gggggggggggggggggggggg^^^",
   "^^^gg*ggggggggggggggggggg^^^",
   "^^^ggggg^ggggggggggggggggg^^",
   "^^^gggg^ggggggggggggΩgggg^^^",
   "^^^ggg^gggggggggggggggggg^^^",
   "^^^^gggggggggggggggggg*gg^^^",
   "^^^gggggggggg*ggggΩggggg^^^^",
   "^^^ggggggggggggggggggggg^^^^",
   "^^^ggggggggggggggggggggg^^^^",
   "^^^gggRgggg..gg*gggggggg^^^^",
   "^^ggggggggg..gg!*gggggg*^^^^",
   "^^gg*gggggg..ggggggggRgg^^^^",
   "^^g*ggggggg..gggggggggggg^^^",
   "^^^ggg*gggg..gggggggg^ggg^^^",
   "^^^^gggg!gg..gggggggggggg^^^",
   "^^^g^gggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggΩgggg..ggggggggg^gg^^^",
   "^^^gggggggg..ggggggggggggg^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^"
  ],
  "cast": {
   "6,12": "cattery4:1,1",
   "15,13": "cattery4:7,3",
   "8,17": "cattery4:7,7",
   "21,14": "cattery4:14,8"
  },
  "marks": {
   "18,9": "lm_ship_cats",
   "20,6": "decor:cattree",
   "6,20": "decor:bench"
  },
  "finds": {
   "4,3": {
    "id": "hth_c4_short",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "cattery2",
    "off": 0
   }
  },
  "gen": 14
 },
 "kennel1": {
  "rows": [
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..ggggggggggg^^",
   "^^^gggggggggg..ggg*ggggggg^^",
   "^^^gggggΩgggg..gggggg*g^gg^^",
   "^^^gggggggggg..gRgggggggg^^^",
   "^^^gg....gggg..ggggggggg^g^^",
   "^^ggg.....ggg..ggggggΩgggg^^",
   "^^^g^.....ggg..ggggg*gg^g^^^",
   "^^^^ggggggggg..gggΩggggggg^^",
   "^^^^ggg*ggggg..gggg*gggggg^^",
   "^^^^g*ggg!ggg..gggggggggg^^^",
   "^^^gggggggggg..ggggggggggg^^",
   "^^^gggggggggg..*ggggggggg^^^",
   "^^gggg^gggggg..gggggggg^g^^^",
   "^^^g^gggggggg..gg!ggggggg^^^",
   "^^ggggggggggg..gg.....ggg^^^",
   "^^^gggggggggg..gg.....ggg^^^",
   "^^^g^gggggggg..gg.....g^g^^^",
   "^^^gggggggg*g..gggggggggg^^^",
   "^^^^ggΩgggggg..gggggggggg^^^",
   "^^^^ggggggggg..^^^^^ggg^^^^^",
   "^^^^^ggg^^^^^..^^^^^^^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "9,11": "kennel1:7,3",
   "16,5": "kennel1:9,3",
   "17,15": "kennel1:7,7"
  },
  "marks": {
   "18,9": "lm_dog_nose",
   "6,20": "decor:doghouse",
   "21,7": "decor:doghouse",
   "8,4": "decor:bench"
  },
  "finds": {
   "23,20": {
    "id": "hth_k1_yard",
    "item": "treats",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "hearthgate",
    "x": 26,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "kennel2",
    "off": 0
   }
  },
  "gen": 14
 },
 "kennel2": {
  "rows": [
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^^ggggggg..gggggggggggg^^^",
   "^^^g*g^gg*g..gggggggggggg^^^",
   "^^^gggggggg..ggggΩggggggg^^^",
   "^^^ggggΩggg..ggggggggggg^^^^",
   "^^^ggg^gggg..gggggggggggg^^^",
   "^^^gggggggg..ggggg*ggggg^^^^",
   "^^^gggggggg..ggggggΩgggg^^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggRgggg..gggggggggg^g^^^",
   "^^^gggggggg..ggggggggggg^^^^",
   "^^^g^gggggg....ggg*gggggg^^^",
   "^^^^gggg*gg....gggggggg^g^^^",
   "^^^^ggggggggg..gg!ggggg*^^^^",
   "^^^^gggg!gggg..gggggggggg^^^",
   "^^^gggggggggg..ggggg^gggg^^^",
   "^^^gggggggggg..ggggggggggg^^",
   "^^^^g^gggg*gg..ggggggggggg^^",
   "^^^WWWWWWWWWW..WWWWWWWWWWg^^",
   "^^^gggggggg*g..ggggggggggg^^",
   "^^^^gRggggggg..ggggggRgggg^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^"
  ],
  "cast": {
   "6,10": "kennel2:4,3",
   "8,15": "kennel2:7,3",
   "17,14": "kennel2:7,7",
   "5,21": "kennel2:1,8",
   "21,21": "kennel2:14,8"
  },
  "marks": {
   "19,8": "lm_scent_dogs",
   "17,4": "decor:doghouse",
   "7,5": "decor:bench"
  },
  "finds": {
   "24,3": {
    "id": "hth_k2_field",
    "item": "coins",
    "n": 520
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   22
  ],
  "links": {
   "s": {
    "map": "kennel1",
    "off": 0
   },
   "n": {
    "map": "kennel3",
    "off": 0
   }
  },
  "gen": 14
 },
 "kennel3": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^^^g^^^^^^^^^^^^^^^^^^^^^^",
   "^^ggggg^^^^^^^gggggggggg^^^^",
   "^^ggggggggggggggggggggggg^^^",
   "^^g^ggggggggg*ggggggggggg^^^",
   "^^^gggggggggggggRggggggg^^^^",
   "^^^ggggggggggggggggggggg^^^^",
   "^^^ggggggggggggggWWWWWgg^^^^",
   "^^^ggggΩgggggg*ggWWWWWgg^^^^",
   "^^^^gggggggggggggWWWWWgg^^^^",
   "^^^^g^ggggggggg!gggggggg*^^^",
   "^^^^ggggggggggg*ggggggggg^^^",
   "^^^ggΩggggg..gggggggggggg^^^",
   "^^^gggggggg..ggggggggR^g^^^^",
   "^^^ggggg!gg..ggggggggg**^^^^",
   "^^^^g^ggg*g..ggggggggggg^^^^",
   "^^^g^gggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggΩgg..ggΩggg^^ggggg^^",
   "^^^gg^ggg*g..gggggggggggg^^^",
   "^^^gggggggg..gggggg^ggggg^^^",
   "^^^gggggggg..ggggggggggggg^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^"
  ],
  "cast": {
   "21,13": "kennel3:14,1",
   "15,10": "kennel3:7,3",
   "16,5": "kennel3:7,5",
   "8,14": "kennel3:7,7"
  },
  "marks": {
   "7,8": "lm_serum_run",
   "8,18": "decor:sled",
   "15,18": "decor:sled",
   "5,12": "decor:doghouse"
  },
  "finds": {
   "24,21": {
    "id": "hth_k3_snow",
    "item": "antidote",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "kennel2",
    "off": 0
   }
  },
  "gen": 14
 },
 "kennel4": {
  "rows": [
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..ggggggggg^^^^",
   "^^^gggggggggg..ggggg¡ggg*^^^",
   "^^^gggggggggg..ggggg¡g*g^^^^",
   "^^ggggggggggg..ggggg¡g*g^^^^",
   "^^g^ggggggggg..ggggg¡ggg^^^^",
   "^^ggggggggggg..ggggg¡gggG^^^",
   "^^g^ggggΩgggg..ggggg¡gg^G^^^",
   "^^ggggggggggg..ggggg¡gggG^^^",
   "^^ggggggggggg..ggggg¡g^g^^^^",
   "^^ggggggg!ggg..ggggggggg^^^^",
   "^^ggggggggggg..ggggggggg^^^^",
   "^^g^g*ggggggg..*gggg¡g^g^^^^",
   "^^^gggggggggg..ggggg¡ggg^^^^",
   "^^^gggggggggg..g!ggg¡gg^g^^^",
   "^^^^g^ggggggg..ggggg¡gggg^^^",
   "^^^gggggggggg..ggggg¡ggggg^^",
   "^^ggggg^*gggg..ggggg¡gg*g^^^",
   "^^g^ggggggggg..ggggg¡gggg^^^",
   "^^ggggggggggg..ggggg¡gggg^^^",
   "^^^gggggg^^^g..gggg*gggg^^^^",
   "^^^^g^^^^^^^^..^^^^^^^^^^^^^",
   "^^^^^^^^^^^^^s.^^^^^^^^^^^^^"
  ],
  "cast": {
   "9,11": "kennel4:7,3",
   "16,15": "kennel4:7,7"
  },
  "marks": {
   "8,8": "lm_guardian_dogs"
  },
  "finds": {
   "23,20": {
    "id": "hth_k4_fence",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "hearthgate",
    "x": 19,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "kennel5",
    "off": 0
   }
  },
  "gen": 14
 },
 "kennel5": {
  "rows": [
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggg*ggg*ggg^^^",
   "^^^gg^ggggg..gggggggggggg^^^",
   "^^^gg^ggggg..gggggggggggg^^^",
   "^^ggggggggg..ggggggggggggg^^",
   "^^^gggggggg..ggggggggggggg^^",
   "^^^gggggggg..gggggΩgggggg^^^",
   "^^^^*gΩgggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggg*^g^^^^",
   "^^^^ggggggg..ggggggggggg^^^^",
   "^^^^ggggggg....ggggggggg^^^^",
   "^^^^g^ggggg....gggggΩg^g^^^^",
   "^^^^gggg!gggg..ggggggggg^^^^",
   "^^^^ggggggggg..g!gggg*ggg^^^",
   "^^^g^gggggggg..ggggggggg^^^^",
   "^^^g^ggggg*gg..ggggggggg^^^^",
   "^^^g^gggggggg..gggg^^*ggg^^^",
   "^^^ggggΩΩgggg..ggggggg^g^^^^",
   "^^ggggggggggg..g*g*g*ggg^^^^",
   "^^gggggggggg*..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^",
   "^^^gggggggggg..gggggggggg^^^"
  ],
  "cast": {
   "8,14": "kennel5:7,3",
   "16,15": "kennel5:7,7"
  },
  "marks": {
   "18,8": "lm_old_dogs",
   "6,9": "decor:bench",
   "20,13": "decor:doghouse",
   "7,19": "decor:garden",
   "8,19": "decor:garden"
  },
  "finds": {
   "24,3": {
    "id": "hth_k5_lawn",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "kennel4",
    "off": 0
   },
   "n": {
    "map": "rescue",
    "off": 0
   }
  },
  "gen": 14
 },
 "rescue": {
  "rows": [
   "^^^^^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^g^^^^^^^^^^^^^^^^^^^^^^^^",
   "^^^gggg^^^^^g^g^gggg*gggg^^^",
   "^^^^^gggggggggggggggggggg^^^",
   "^^^^g^ggggggggggggggggggg^^^",
   "^^^ggggg^gg*ggggggggggggg^^^",
   "^^^gg*gggggggggggggggggg^^^^",
   "^^^ggg*gggggggggggggggggg^^^",
   "^^^g^gggggggggggggΩgggg^g^^^",
   "^^^gggΩggggggggggg*gggggg^^^",
   "^^^^ggggggggggggggggggggg^^^",
   "^^^gggggggggggg!gggggggggg^^",
   "^^^g*gggggg..*gggggggggg*^^^",
   "^^^gggggggg..gggggggΩ*gggg^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^g^gg*g!gg..gggggggggg^g^^^",
   "^^ggggggggg..gggggggggggg^^^",
   "^^ggggggggg..ggggggggg^^g^^^",
   "^^^gg*ggggg..gggggggggggg^^^",
   "^^^ggggΩggg..g*gggggggggg^^^",
   "^^ggggggggg..gggggggΩgg^^^^^",
   "^^^gggggggg..ggggggggggg^^^^",
   "^^^gggggggg..gggggggggggg^^^",
   "^^^gggggggg..gggggggggggg^^^"
  ],
  "cast": {
   "15,11": "rescue:7,3",
   "8,15": "rescue:7,7"
  },
  "marks": {
   "18,8": "lm_mixed_breed",
   "6,9": "decor:doghouse",
   "20,13": "decor:cattree",
   "7,19": "decor:doghouse",
   "20,20": "decor:bench"
  },
  "finds": {
   "4,21": {
    "id": "hth_rescue",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "kennel5",
    "off": 0
   }
  },
  "gen": 14
 }
}, inbound: [
 {
  "from": "town2",
  "tile": "0,11",
  "map": "hearthgate",
  "x": 13,
  "y": 22
 }
] });
