// GENERATED by design/tools/forge_sides.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "sides", maps: {
 "thicket": {
  "rows": [
   "TTTTTTTTTTTTTTTTT^TTTTTTTTTT",
   "TTTTgTTTTTTTTgTgggTTTTTTTTTT",
   "TTTgg*ggggggggggggggggggTgTT",
   "TTTTGGGgggggggggggggggggggTT",
   "TTTgggggggggggg*⁂gggggggggTT",
   "TTTgggTTTggggg..ggTTTTgggTTT",
   "TTTgTTTTTTgggg..ggTTTTT*gTTT",
   "TTTggTTTTT*ggg..gggTTTggggTT",
   "TT^ggTTTTTgggg..ggΩggggggTTT",
   "TTT*ggTTTgggRg..ggg*gggTgTTT",
   "TTTggggGGGGGgg..gggggg!g*TTT",
   "TTTgTggGGGGGgg..gggggggggg^T",
   "TTTgg*gGGGGGgg.............e",
   "TTTggggggggggg.............T",
   "TTTggggggggggg..ggggggggggTT",
   "WWWWWWWWWWgggg..gggg⁅gggggTT",
   "TTTgWWWggggggg..ggg*gggggTTT",
   "TTTg*ggggg!ggg..ggggTTTTTTTT",
   "TTTTgggggggggg..ggggTTTTTTTT",
   "TTT^gg..........ggggTTTTTTTT",
   "TT^g¡g..........gggggggggTTT",
   "TTTggggg*ggggggTgGGG*ggggTTT",
   "TTTTT^TTTTTTgTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "12,9": "thicket:7,2",
   "22,10": "thicket:8,3",
   "10,17": "thicket:8,8"
  },
  "marks": {
   "18,8": "lm_bramble"
  },
  "finds": {
   "4,3": {
    "id": "side_th_tangle",
    "item": "berries",
    "n": 3
   },
   "23,21": {
    "id": "side_th_stream",
    "item": "coins",
    "n": 160
   }
  },
  "exits": {
   "27,12": {
    "map": "route2",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   24,
   12
  ],
  "links": {},
  "gen": 11
 },
 "canopywalk": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTT^TTTTTTT^TTTTTTTTTTTTTTT",
   "TTTggggggggGGTT^TTTTTTTTTTTT",
   "TTTggRgggggRgggg⁌*gggTTTTTTT",
   "TTTgggg*ggggggggggggTTTTTTTT",
   "TTTgTggg............TTTTTTTT",
   "TTTTgTgg............ggggTTTT",
   "TTTggggg..ggggggg*..gggggTTT",
   "TTTTTTgg..gggggggg..RgggTTTT",
   "TT^TTTgg..ggTTTggg..g*gggTTT",
   "TTTTTTgg..ggTΩTggg..gggggTTT",
   "TTTTTTgg..ggTgTggg..gggggTTT",
   "TTTTTT*g..gggggggg.........e",
   "TTTTTT⁂g..gggggggg.........T",
   "TTTgTTgg..gg*ggggggggg!ggTTT",
   "TTTggggg..Rgggggggg¡GGGggTTT",
   "TTTggggg..gggg*ggggg*gg*gTTT",
   "TTgg*ggg..........ggggggggTT",
   "TTTggggg..........gggg*gggTT",
   "TT^gggggggg*ggggg!ggTTTTTgTT",
   "TTTTGGgggggggggggg*gTTTTTgTT",
   "TTTTgggggggTTTgggg*gTTTTggTT",
   "TT^T^ggTTgTTTTTTTgTgTTTTTTTT",
   "TTTTT^^TT^TTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "5,3": "highstation:10,2",
   "11,3": "canopywalk:7,2",
   "20,8": "canopywalk:8,2",
   "10,15": "canopywalk:10,3",
   "22,14": "canopywalk:8,3",
   "17,19": "canopywalk:8,8"
  },
  "marks": {
   "13,10": "lm_canopy_fogging"
  },
  "finds": {
   "4,21": {
    "id": "side_cw_crown",
    "item": "treats",
    "n": 3
   },
   "21,6": {
    "id": "side_cw_top",
    "item": "coins",
    "n": 200
   }
  },
  "exits": {
   "27,12": {
    "map": "route3",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   24,
   12
  ],
  "links": {},
  "gen": 11
 },
 "outback": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTT^TT",
   "TTTgTTTTTTTgTTTTTTTTTTT^TTTT",
   "TTTgggggTggggggggTggTggggTTT",
   "TTTggggggggggggGGGGGgggg*TTT",
   "TTT^gggggggg..gggggggggggTTT",
   "TTT^gggggggg..ggggggggggg^TT",
   "TTTggg....gg..gggggΩgggggTTT",
   "TT^gg.....gg..ggg*ggggg*gTTT",
   "TTTTg....ggg..gRggggggTggTTT",
   "TTTgggggg⁂gg..ggggggggggggTT",
   "TTTggggggggg..gggggg*TgTgTTT",
   "TTTTTggggggg..gggggggg!gg^TT",
   "TTTTgTgggggg...............e",
   "TTTgggTgg*gg...............T",
   "TTTggggTggggggggggggGGGgggTT",
   "TTTggggggggggggg^g*gGGGgg^TT",
   "TTTTg.....ggggg^gggggggggTTT",
   "TT^gg.WWW.!ggggg.....gggTgTT",
   "TTTgg.WWW.ggggg.......ggggTT",
   "TTTgT.....gggg*.......ggggTT",
   "TTgggggggg*ggggg¡ggggTggggTT",
   "TTTTTgGGGGGgggggTTTggT^TggTT",
   "TTTTTT^TTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "15,8": "outback:7,2",
   "22,11": "outback:8,3",
   "10,17": "outback:8,8"
  },
  "marks": {
   "19,6": "lm_malleefowl"
  },
  "finds": {
   "23,3": {
    "id": "side_ob_mound",
    "item": "bigberries",
    "n": 1
   },
   "3,20": {
    "id": "side_ob_water",
    "item": "coins",
    "n": 240
   }
  },
  "exits": {
   "27,12": {
    "map": "route4",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   24,
   12
  ],
  "links": {},
  "gen": 11
 },
 "savanna": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTggTTTggggTgggTRggTgggTTTT",
   "TTTggggg*gRgggggGGGGGGgggTTT",
   "TTTgggGGGGGGgggGGGGGGGGggTTT",
   "TTTgTGGGGGGGGggGGGGGGGGGgTTT",
   "TTTgGGGGGGGGGgggGGGGGGGGgTTT",
   "TTTgGGGGGGGGGggg¡GGGGGGRgTTT",
   "TTTggGGGGGGgggΩggggggggggTTT",
   "TTTTgggggggg¡gggggggg....TTT",
   "TTTTTT⁂*ggggggg¡gggg*.WW.TTT",
   "TTTgggggggg*gggggg⁃gg....TTT",
   "TTT*.......................e",
   "TTTg.......................T",
   "TTTgTgggggg!gggggggggg!gggTT",
   "TTTggR*ggggggggggggggRggg^TT",
   "TTTgggGGGGGgggRgggGGGGGgg^TT",
   "TTTgTGGGGGGGgggggGGGGGGTgTTT",
   "TTTgGGGGGGGGG*gggGGGGGGTTTTT",
   "TT^TGGGGGGGGGggggGGGGGGTTTTT",
   "TTTTgGGGGGGgg*ggggGGGGGgggTT",
   "TTTT*g^TggggTTTT*gggggTT^TTT",
   "TTTTTTTTTTTTTTTTT^TTT^TTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "10,3": "savanna:7,2",
   "17,2": "savanna:8,2",
   "23,7": "savanna:9,2",
   "5,15": "savanna:2,3",
   "14,16": "savanna:6,3",
   "21,15": "savanna:10,3",
   "11,14": "savanna:8,3",
   "22,14": "savanna:8,8"
  },
  "marks": {
   "14,8": "lm_elephant_trees"
  },
  "finds": {
   "4,3": {
    "id": "side_sv_grass",
    "item": "treats",
    "n": 3
   },
   "22,20": {
    "id": "side_sv_herd",
    "item": "coins",
    "n": 260
   }
  },
  "exits": {
   "27,12": {
    "map": "route5",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   24,
   12
  ],
  "links": {},
  "gen": 11
 },
 "tundra": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTT^TT",
   "TTTTTT^TTTggggggggTTTgTTTTTT",
   "TTTgggggggggggggggggggggg^TT",
   "TTTTGGGGggggggGGGggg*gggg^TT",
   "TTTTggggggggggggggggTTgggTTT",
   "TTTggggggg..ggggWWWWWggggTTT",
   "TTTgTggggg..ggggWWWWWggggTTT",
   "TTTggggggg..ggggWWWWWgggggTT",
   "TTTggTgggg..gggggggg*ggg^TTT",
   "TTTTggTggg..*gRgggg*gggg^TTT",
   "TTTTgTgggg..ggggggg¡ggggggTT",
   "TTTTgggggg..gggggggggg!gggTT",
   "TTTggggggg.................e",
   "TTTGGGgggg.................T",
   "TTTggggg!gggggggggggRggggTTT",
   "TTT*ggggggggg*ggΩgggggggTgTT",
   "TTTgTgggggggggggggggggggggTT",
   "TT^ggWWWWWgg⁂ggggggggggggTTT",
   "TTTggWWWWWgggggggggWWWgggTTT",
   "TTTggWWWWWg*TgTggggggggggTTT",
   "TTTTgggggggggggggggggggggTTT",
   "TTTTTggggg*ggggggggggggTggTT",
   "TTTTTTTTTTTTTTTgTg^gTTTTTTTT",
   "TTTTTTTTTTTTTTTTT^TTTTTTTTTT"
  ],
  "cast": {
   "14,9": "tundra:7,2",
   "20,14": "tundra:10,3",
   "22,11": "tundra:8,3",
   "8,14": "tundra:8,8"
  },
  "marks": {
   "16,15": "lm_permafrost"
  },
  "finds": {
   "4,20": {
    "id": "side_tn_pool",
    "item": "antidote",
    "n": 1
   },
   "24,3": {
    "id": "side_tn_ridge",
    "item": "coins",
    "n": 280
   }
  },
  "exits": {
   "27,12": {
    "map": "route6",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   24,
   12
  ],
  "links": {},
  "gen": 11
 },
 "taiga": {
  "rows": [
   "TTTTTTT^T^TTTT^TTTTTTTTTTTTT",
   "TTTTTTTggggggggTTTTTgggTTTTT",
   "TTTTgggggggggggggTggggggTTTT",
   "TTTgGgg*ggggggggggggggg*ggTT",
   "TTTgTgTTTgggg..gggTTTTTgggTT",
   "TTgggTTTTTggg..gggTTTTTgggTT",
   "TTTggTTTTTggg..ggggTTTggggTT",
   "TTgggTTTTTggg..⁂gggggggggTTT",
   "TTggggTTTgggg..ggggg*ggggTTT",
   "TTTgggggg*Rgg..ggΩgggggg*TTT",
   "T^TTg*ggggggg..gggggGGGTgTTT",
   "TTTgggggggggg..gggg⁂gg*ggTTT",
   "TTTggg....ggg..............e",
   "TTT^gg.WW.ggg..............T",
   "TTT^gg....ggg..gggggg!gggTTT",
   "TTTgggggggggg..ggWWWgggggTTT",
   "TTTTggggGGGgg..g*ggggggggTTT",
   "TTTTTgggggggg..ggggggggggTTT",
   "TTTTTTTTggg*g..!gggTTTTTgTTT",
   "TTTTTTTTTgggg..ggggTTTTTggTT",
   "TTTTTTTTTgggg..ggggTTTTTgTTT",
   "TTTggggggg¡gg..gT^ggggg*gg^T",
   "TTTTTTTTTTTTT^^TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "taiga:7,2",
   "21,14": "taiga:8,3",
   "15,18": "taiga:8,8"
  },
  "marks": {
   "17,9": "lm_lynx_hare"
  },
  "finds": {
   "24,21": {
    "id": "side_tg_bog",
    "item": "berries",
    "n": 3
   },
   "4,10": {
    "id": "side_tg_spruce",
    "item": "coins",
    "n": 300
   }
  },
  "exits": {
   "27,12": {
    "map": "route8",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   24,
   12
  ],
  "links": {},
  "gen": 11
 },
 "cave1": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTn^TTTTT^TT",
   "TTTTTTTTTTTTTTTTTT.^.....TTT",
   "T^...^.T....T...!..^......TT",
   "T^.....^......^...........TT",
   "TT............^...........TT",
   "TT^^^..^^^..^^^^^.^^^^.^..TT",
   "TTT....^......^......^....TT",
   "TT.....^...⁂..^......^....TT",
   "TTT....^......^...........TT",
   "TT^^^^.^.^^^..^^.^^^^^.^..TT",
   "TTT..!...............^....TT",
   "TT^....^.............^....TT",
   "e.........................TT",
   "T.........................TT",
   "TTT..............Ω...^....TT",
   "TTT...........^......^....^T",
   "TTT.^.^^^^^...^.^.^^^^^.^.TT",
   "TTTT^T.^......^...........TT",
   "TTT.T....WWW..^..........TTT",
   "TTT..................^...TTT",
   "TT^^^^.^^..^^.^...^^^^^.^^TT",
   "T^^TT..^T.T...^.....¡.....TT",
   "TTTTT^TTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "5,10": "cave1:4,6",
   "16,2": "cave1:gate"
  },
  "marks": {
   "17,14": "lm_cave_bats"
  },
  "finds": {
   "24,21": {
    "id": "side_cv_deep",
    "item": "revives",
    "n": 1
   },
   "4,3": {
    "id": "side_cv_corner",
    "item": "coins",
    "n": 220
   }
  },
  "exits": {
   "0,12": {
    "map": "route3",
    "x": 26,
    "y": 11
   },
   "18,0": {
    "map": "shrine_qilin",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   2,
   12
  ],
  "links": {},
  "gen": 11
 }
}, inbound: [
 {
  "from": "route2",
  "tile": "0,11",
  "map": "thicket",
  "x": 26,
  "y": 12
 },
 {
  "from": "route3",
  "tile": "0,11",
  "map": "canopywalk",
  "x": 26,
  "y": 12
 },
 {
  "from": "route3",
  "tile": "27,11",
  "map": "cave1",
  "x": 1,
  "y": 12
 },
 {
  "from": "route4",
  "tile": "0,11",
  "map": "outback",
  "x": 26,
  "y": 12
 },
 {
  "from": "route5",
  "tile": "0,11",
  "map": "savanna",
  "x": 26,
  "y": 12
 },
 {
  "from": "route6",
  "tile": "0,11",
  "map": "tundra",
  "x": 26,
  "y": 12
 },
 {
  "from": "route8",
  "tile": "0,11",
  "map": "taiga",
  "x": 26,
  "y": 12
 },
 {
  "from": "shrine_qilin",
  "tile": "7,9",
  "map": "cave1",
  "x": 18,
  "y": 1
 }
] });
