// GENERATED by design/tools/forge_jungle.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "jungle", maps: {
 "route3": {
  "rows": [
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTT*ggGGGGGg..ggTggT*gggTTTT",
   "TTTTgggggggg..gggTggggggTTTT",
   "TTTTTTggTggg.TggTTTgTTTgTTTT",
   "TTT^TT^TT^TTVTT^TT^TT^TT^TTT",
   "TTTgGGGGGggg..ggggGGGGGGGTTT",
   "TTTgGGGGGggg..gg*gGGGGGGGTTT",
   "TTTgTGGGGggg..ggg*GGGGGT*TTT",
   "TTTgggRggggg..g*ggggRggggTTT",
   "TTT!gggggggg..gggggggggg!TTT",
   "e..........................e",
   "T..........................T",
   "TTggggTTgggg..ggg⁂gggggTTTTT",
   "TTgggggTg⁄gg..gggggggggTg^TT",
   "TT^gGGGGGg*g...gggΩggTgggTTT",
   "TTgTGGGGGggg...gggg*gggT¡TTT",
   "TTggGGGGGgggg..ggggWWWWWWWWW",
   "TTTgTgRgggggg..gRggWgggTgTTT",
   "TTggggggggggg..gg*gWgg***TTT",
   "TTTgWWWWWWWWW..WWWWWgggggTTT",
   "TTTgggTggTggg..ggggGGGGGTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "12,5": "route3:7,1",
   "3,10": "route3:gate",
   "24,10": "route3:gate2",
   "6,18": "route3:2,2",
   "6,9": "route3:4,4",
   "20,9": "route3:11,10",
   "16,18": "route3:3,14"
  },
  "marks": {
   "18,15": "lm_strangler_fig"
  },
  "finds": {
   "22,18": {
    "id": "jun_r3_creek",
    "item": "berries",
    "n": 3
   },
   "4,2": {
    "id": "jun_r3_ridge",
    "item": "coins",
    "n": 130
   }
  },
  "exits": {
   "0,11": {
    "map": "canopywalk",
    "x": 7,
    "y": 8
   },
   "27,11": {
    "map": "cave1",
    "x": 14,
    "y": 10
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "seg_j1",
    "off": 0
   },
   "s": {
    "map": "town3",
    "off": 0
   }
  },
  "gen": 4
 },
 "seg_j1": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggTgggggg..ggggggggggTT",
   "TTTgggggggTggg..gggRggggggTT",
   "TTTTGTGGGgg*gg..ggggggggggTT",
   "TTTTGGGGGTgggg..ggggggggTgTT",
   "TTTTGGGGGRgggg..gTTGGGGGggTT",
   "TTTT!ggggggggg..gggGGGGGggTT",
   "TTTTgggggggggg..gggGGGGGggTT",
   "e...............ggggggggggTT",
   "T...............gggggggggggT",
   "TTTTggRggggggg..gRgggggTggTT",
   "TTTg*ggggg⁅ggg..ggggggggggTT",
   "TTTgTGGgggg*gg..ggggg*TgggTT",
   "TTTgTggggggg....ggggggggTgTT",
   "TTTggggggggg....gg*ΩgggggTTT",
   "TTTgWWWWWggg..ggg...gggggTTT",
   "TTTTggggWggg..ggggggggRggTTT",
   "TTT*g¡ggWggg..g*ggggggggggTT",
   "TTTgggggWggg..gggggggggggTTT",
   "TTTTgggggggg..g*⁂gGGGGGgggTT",
   "TTTTgT*ggR*g..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "4,7": "seg_j1:gate",
   "9,6": "seg_j1:3,1",
   "19,3": "seg_j1:11,1",
   "6,11": "seg_j1:3,3",
   "22,17": "seg_j1:4,3",
   "17,11": "seg_j1:14,3",
   "9,21": "seg_j1:1,10"
  },
  "marks": {
   "19,15": "lm_leafcutter"
  },
  "finds": {
   "4,4": {
    "id": "jun_j1_grove",
    "item": "treats",
    "n": 2
   },
   "24,20": {
    "id": "jun_j1_trail",
    "item": "wakeberry",
    "n": 1
   }
  },
  "exits": {
   "0,9": {
    "map": "shrine_solenn",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "route3",
    "off": 0
   },
   "n": {
    "map": "seg_j2",
    "off": 0
   }
  },
  "gen": 4
 },
 "seg_j2": {
  "rows": [
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..*ggggggggggggTT",
   "TTggGGGGGg⁂..ggggggggggRgTTT",
   "TTTgGGGGGgg..ggggggGGGGGTgTT",
   "TTTgGGGGGgg..ggggggGGGGG*gTT",
   "TTgTgggRggg..gggTggGGGGTgTTT",
   "TTggggggggg..ggg⁄gTgggggggTT",
   "TTT*Tgggggg..ggggTggggggggTT",
   "TTTgggggΩgg.....ggggggggggTT",
   "TTTggg*gggg.....gg*ggggTgTTT",
   "WTggWggggggggg..gggggggggTTT",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "TWTWgggggWgggg..ggWWWgggWTTT",
   "TTTggggggggggg..Rggg*gggg^TT",
   "TT^gggRTgggggg..ggggRgggggTT",
   "TTTgTGGGGgTTgg..gggGGGGG*gTT",
   "TTTgGGGGGg*ggg..gggGGGGGggTT",
   "TTT^GGGGGggggg..gggGGGGGgg^T",
   "TTTg*ggggRgggg..ggg¡gTggTgTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "23,3": "seg_j2:13,1",
   "7,6": "seg_j2:3,3",
   "16,16": "seg_j2:6,8",
   "6,17": "seg_j2:3,10",
   "9,21": "seg_j2:4,10",
   "20,17": "seg_j2:11,10"
  },
  "marks": {
   "8,9": "lm_bromeliad"
  },
  "finds": {
   "3,10": {
    "id": "jun_j2_bank",
    "item": "antidote",
    "n": 1
   },
   "24,16": {
    "id": "jun_j2_south",
    "item": "coins",
    "n": 140
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_j1",
    "off": 0
   },
   "n": {
    "map": "seg_j3",
    "off": 0
   }
  },
  "gen": 4
 },
 "seg_j3": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..Tgg*ggg*ggTTT",
   "TTTgGGGGGgggg..ggg*gggggggTT",
   "TTTgTGGGGgggg..TRggGGGGGgTTT",
   "TTTgGGGGGgggg..*gggGGGGGggTT",
   "TTTgggggg⁌ggg..ggggGGGGTgTTT",
   "TTg!ggggggggg..ggggggg*gggTT",
   "e..............ggggg*ggggTTT",
   "T..............ggggggggTggTT",
   "TTTgTggRggggg..g*g*ggggTgTTT",
   "TTTgTgggggggg..gggRggggggTTT",
   "TTTgggggggTgg..⁂ggggg.Ω.gTTT",
   "TTTgggggTTggg..ggggggggggTTT",
   "T^ggggggggg....gggggWWWWWWWW",
   "TTgggRggggg....gggggWgggTTTT",
   "Tgggggggggg..gggggggWggTgTTT",
   "TgggGGGGGgg..*gWWWWWWggggTTT",
   "TgggGGGGGgg..gggggggggggTTTT",
   "TTgTGGGGGgg..ggggggggg*gTTTT",
   "TTggggTg¡gg..*gggRgg*GGGgTTT",
   "Tgggggggggg..*gggggggggg^TTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "3,7": "seg_j3:gate",
   "16,4": "seg_j3:6,1",
   "7,10": "seg_j3:3,3",
   "5,15": "seg_j3:1,5",
   "17,20": "seg_j3:13,5",
   "18,11": "seg_j3:12,6"
  },
  "marks": {
   "22,12": "lm_clay_lick"
  },
  "finds": {
   "24,10": {
    "id": "jun_j3_clay",
    "item": "bigberries",
    "n": 1
   },
   "3,10": {
    "id": "jun_j3_west",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_verdanmane",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "seg_j2",
    "off": 0
   },
   "n": {
    "map": "town4",
    "off": 0
   }
  },
  "gen": 4
 },
 "town4": {
  "rows": [
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTTgggggggggg..!gggggTggTTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTgHgggCgg*g..gggYggggHgTTT",
   "TTg*ggg¦............¦ggggTTT",
   "TTTTgΩg..............*g*gTTT",
   "TTTgTgT...Ω..........ΩggggTT",
   "TTTgggg..R...........ggggTTT",
   "TTTTggg....Ω....Ω....ggggTTT",
   "TTTTggg¦............¦ggHgTTT",
   "TTTgTHggggggg..ggggggggggTTT",
   "TTTgggggggΩgg..gΩVgggggggTTT",
   "TTT*.....................TTT",
   "TTgg.....................TTT",
   "TTgg!ggggΩg¦g..*¦g*gMgΩgTTTT",
   "WWWWWWWgggggg..*ggΩgggTgTTTT",
   "TTTTΩTWgggggg..ggggggggggTTT",
   "TTTTTTWggHggg..gggggggg*gTTT",
   "TTWWWWWgggggg..*ggHgggggTTTT",
   "TTTggggΩΩgg*!..ggggggggTgTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "15,3": "town4:gate",
   "12,21": "town4:7,3",
   "4,16": "town4:6,12",
   "9,9": "town4:3,8",
   "17,13": "town4:9,10"
  },
  "marks": {
   "10,8": "lm_kapok",
   "10,13": "decor:stall",
   "16,13": "decor:stall",
   "18,17": "decor:stall",
   "5,7": "decor:hammock",
   "21,8": "decor:hammock",
   "9,16": "decor:hammock",
   "11,10": "decor:bench",
   "16,10": "decor:bench",
   "22,16": "decor:crates",
   "4,18": "decor:canoe",
   "8,21": "decor:garden",
   "7,21": "decor:garden"
  },
  "finds": {
   "24,13": {
    "id": "jun_t4_market",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_j3",
    "off": 0
   },
   "n": {
    "map": "route4",
    "off": 0,
    "fallback": {
     "tile": "13,0",
     "ch": "n",
     "map": "route4",
     "x": 7,
     "y": 14
    }
   }
  },
  "gen": 4
 }
}, inbound: [
 {
  "from": "canopywalk",
  "tile": "7,9",
  "map": "route3",
  "x": 1,
  "y": 11
 },
 {
  "from": "cave1",
  "tile": "15,10",
  "map": "route3",
  "x": 26,
  "y": 11
 },
 {
  "from": "shrine_solenn",
  "tile": "7,9",
  "map": "seg_j1",
  "x": 1,
  "y": 9
 },
 {
  "from": "shrine_verdanmane",
  "tile": "7,9",
  "map": "seg_j3",
  "x": 1,
  "y": 8
 },
 {
  "from": "route4",
  "tile": "7,15",
  "map": "town4",
  "x": 13,
  "y": 1
 }
] });
