// GENERATED by design/tools/forge_sea.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "sea", maps: {
 "shore": {
  "rows": [
   "TTTTTnTTTTTTTTTTTTTTTTTTT^TT",
   "TTTT^..........WWWWWWWWWWWWW",
   "TTTgg.........gWWWWWWWWWWWWW",
   "TTTgTg!gΩggg..gWWWWWWWWWWWWW",
   "TTgggTggggg!............eWWW",
   "TTTggTggggR...gWWWWWWWWWWWWW",
   "TTgggggggg....gWWWWWWWWWWWWW",
   "TTg^gggggΩ....gWWWWWWWWWWWWW",
   "TTTg^gggg..!..gWWWWWWWWWWWWW",
   "TTTgGGGgg...............eWWW",
   "TTT!ggggg.....gWWWWWWWWWWWWW",
   "e.............gWWWWWWWWWWWWW",
   "T.............g.WWWWWWWWWWWW",
   "TTTTΩgggg.R...gWWWWWWWWWWWWW",
   "TTTgggggg...............eWWW",
   "TTTTΩTggg..!..g.WWWWWWWWWWWW",
   "TTTTgTgggΩ.....WWWWWWWWWWWWW",
   "e.............gWWWWWWWWWWWWW",
   "T.............gWWWWWWWWWWWWW",
   "TT^ggg..gg.!............eWWW",
   "TTTTGG..g^Rg..gWWWWWWWWWWWWW",
   "TTTggg..^TTT..gWWWWWWWWWWWWW",
   "TTTTTT..^TTT...WWWWWWWWWWWWW",
   "TTTTTTs.TTTTTTTTTTTTTTTTTTTT"
  ],
  "cast": {
   "10,5": "shore:2,2",
   "10,13": "shore:2,5",
   "10,20": "shore:2,10",
   "11,4": "shore:ice",
   "11,8": "shore:blue",
   "11,15": "shore:kelp",
   "11,19": "shore:reef",
   "3,10": "shore:west",
   "6,3": "shore:ember"
  },
  "marks": {
   "9,7": "lm_tide_pool",
   "4,13": "decor:nets",
   "9,16": "decor:canoe",
   "8,3": "decor:crates",
   "4,15": "decor:nets"
  },
  "finds": {
   "14,21": {
    "id": "sea_sh_south",
    "item": "revives",
    "n": 1
   },
   "3,3": {
    "id": "sea_sh_slope",
    "item": "coins",
    "n": 300
   }
  },
  "exits": {
   "0,11": {
    "map": "town8",
    "x": 26,
    "y": 11
   },
   "0,17": {
    "map": "tidewater",
    "x": 13,
    "y": 20
   },
   "6,23": {
    "map": "aquarium",
    "x": 7,
    "y": 8
   },
   "5,0": {
    "map": "ember",
    "x": 7,
    "y": 10
   },
   "24,4": {
    "map": "polarsea",
    "x": 13,
    "y": 22
   },
   "24,9": {
    "map": "openocean",
    "x": 13,
    "y": 22
   },
   "24,14": {
    "map": "kelp",
    "x": 13,
    "y": 22
   },
   "24,19": {
    "map": "reef",
    "x": 13,
    "y": 22
   }
  },
  "beyond": {
   "e": "W"
  },
  "land": [
   10,
   11
  ],
  "links": {},
  "gen": 10
 },
 "reef": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTT^T^TTgTT^TgTTTTTTTTT^TTT",
   "TTTggggggggT!ggggggTTgggggTT",
   "TTTgggggggggTTggggggGGGgggTT",
   "TTgggWWWWWggggggggggggggRgTT",
   "TTTgWWWWWWWggggTgggggggggTTT",
   "TTTgWWWWWWWggggggggWWWWWggTT",
   "TTTgWWWWWWWgggggggWWWWWWWTTT",
   "TTgggWWWWWggg*ggggWWWWWWWTTT",
   "TTTgTgggggggggggggWWWWWWWTTT",
   "TTTggggggTgggggΩgggWWWWWTT^T",
   "TT^ggTgggggggggggggg*gTggTTT",
   "TTgggggggTggggggg*gggg!ggTTT",
   "TTTgTggggggg*gggg^^ggggggTTT",
   "T^ggggggggggggggRggggggTgTTT",
   "TTTgGGGGGgggggggggggggTggTTT",
   "TTTgGGGGGggRg*ggggWWWWWggTTT",
   "TTTgGGGGGgggggggggWWWWWggTTT",
   "TTTgggggg*ggg..gggWWWWWgg^TT",
   "TTTTgRggggggg..gggggggg*gTTT",
   "TTTTggggggggg..gggRggggggTTT",
   "TTTTgggGGGggg..Tggg*ggggTTTT",
   "TTTTTTTTTTTTT..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "5,19": "reef:1,7",
   "11,16": "reef:2,7",
   "18,20": "reef:13,7",
   "12,2": "reef:5,8",
   "16,14": "reef:6,8",
   "22,12": "reef:10,8",
   "24,4": "reef:11,8"
  },
  "marks": {
   "15,10": "lm_cleaning_station"
  },
  "finds": {
   "4,3": {
    "id": "sea_rf_corner",
    "item": "treats",
    "n": 3
   },
   "24,20": {
    "id": "sea_rf_flats",
    "item": "coins",
    "n": 320
   }
  },
  "exits": {
   "13,23": {
    "map": "shore",
    "x": 23,
    "y": 19
   }
  },
  "beyond": {
   "n": "W",
   "e": "W",
   "w": "W"
  },
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 10
 },
 "kelp": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTT^TgTTTggggTTTgTTTTT",
   "TTTTggggggggggggggggggggggTT",
   "TTTggggTgg*gGGGggg!gggggggTT",
   "TTTggggTggggggggggggggggggTT",
   "TTTgggggggggggggggWWWWW*gTTT",
   "TTTgggWWWWWggggggWWWWWWWTTTT",
   "TTTTggWWWWWggggggWWWWWWWgTTT",
   "TTTTgTWWWWWggggggggggggggTTT",
   "TTTTgTWWWWWgggTgggggggggggTT",
   "TTTTggWWWWgggggTgggggTTgggTT",
   "TTTTRggggggggTggggggggggggTT",
   "TTTTggggggg*ΩgggggggggggTgTT",
   "TTTTgggTTgggggg*gggggTgggTTT",
   "TTTgggggggggggg!gggggggggTTT",
   "TTTTgggggggTgggggWWWWWggRTTT",
   "TTTgGGGGGggggggggWWWWWgggTTT",
   "TTTgGGGGGggRgggggWWWWWggTTTT",
   "TTTTGGGGGgggg..ggggggggggTTT",
   "TTTTgTggggggg..gggggggggTTTT",
   "TTTTg^ggggggg..ggggggggggTTT",
   "TTTT^g*gggggg..TTggggGGGgTTT",
   "TTTTTTTTTgTTT..gggggT^gTgTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "11,17": "kelp:2,7",
   "24,15": "kelp:14,7",
   "4,11": "kelp:2,8",
   "15,14": "kelp:5,8",
   "18,3": "kelp:10,8"
  },
  "marks": {
   "12,12": "lm_kelp_forest"
  },
  "finds": {
   "24,3": {
    "id": "sea_kp_corner",
    "item": "berries",
    "n": 3
   },
   "4,15": {
    "id": "sea_kp_west",
    "item": "antidote",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "shore",
    "x": 23,
    "y": 14
   }
  },
  "beyond": {
   "n": "W",
   "e": "W",
   "w": "W"
  },
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 10
 },
 "openocean": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TT^T^^TTTTTT^^TTTTTTTTTTTTTT",
   "TTTggggggTTTggggTTTTTTTggTTT",
   "TTTTggggggggggΩggggggggggTTT",
   "TTTTgggggggggggg!WWWWWWWTTTT",
   "TTTTWWWWWWWggTggWWWWWWWWWTTT",
   "TTTWWWWWWWWWggggWWWWWWWWWTTT",
   "TTTWWWWWWWWW*gTggggggggggTTT",
   "TTTWWWWWWWWWgggggggggggggTTT",
   "TTTgWWWWWWWggggggRggggggTTTT",
   "TTTggggg*gggggggggggggggg^TT",
   "TTTggggggggggggggggg!...nTTT",
   "TTTgGgggggggGGGgggggg....TTT",
   "TTTggggggggggggggggWWWWWgTTT",
   "TTTgggggggRgggggggWWWWWWWTTT",
   "TTT*ggggg*ggggggggWWWWWWWTTT",
   "TTggWWWWWgggggggggWWWWWWWTTT",
   "TTTgWWWWWggggggggggWWWWWTTTT",
   "TTTgWWWWWgggg..g^gggggTgTTTT",
   "TTTgggggggg!g..gggggggTgTTTT",
   "TT^ggggggg*Tg..gggRgggggTTTT",
   "TTTgggggggggg..ggggggggTTTTT",
   "TTTTTTTTgTTTg..TT^T^TTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,14": "openocean:2,7",
   "18,20": "openocean:13,7",
   "17,9": "openocean:3,8",
   "11,19": "openocean:5,8",
   "16,4": "openocean:10,8",
   "20,11": "openocean:dive"
  },
  "marks": {
   "14,3": "lm_whale_pump"
  },
  "finds": {
   "4,3": {
    "id": "sea_oo_corner",
    "item": "coins",
    "n": 340
   },
   "23,20": {
    "id": "sea_oo_bar",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "shore",
    "x": 23,
    "y": 9
   },
   "24,11": {
    "map": "abyss",
    "x": 13,
    "y": 22
   }
  },
  "beyond": {
   "n": "W",
   "e": "W",
   "w": "W"
  },
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 10
 },
 "polarsea": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTT^TTTTTTT^TTTTTgTTTTTTT",
   "TTTTgggggggggggggggggggggTTT",
   "TTTTgTggggg!gggggggggg!gggTT",
   "TTTTgTgggggggggggggggggggTTT",
   "TTTTggggggggggggggWWWWWggTTT",
   "TTTTTggggggggggggWWWWWWWgTTT",
   "TTTTggggggggggTggWWWWWWWgTTT",
   "TTTTWWWWWWWgTgTggWWWWWWWgTTT",
   "TTTTWWWWWWWgggggggWWWWWgggTT",
   "TTTgWWWWWWWgggggggggggggggTT",
   "TTTggggggg*gΩgggggggggggTgTT",
   "TTTgggggggggggg*gggggggggg^T",
   "TTTgggggggggggggggRgggg*TgTT",
   "TTTgggggggTgggggggggggggggTT",
   "TTTggggTgg*gggWWWWWggggTggTT",
   "TTTgTRggggggggWWWWWgggggggTT",
   "TTTgggggggggggWWWWWggggRTgTT",
   "TTTgGGGGGgggg..gggggggggggTT",
   "TTTgggggggggg..gggggggggTgTT",
   "TTT*ggggggggg..ggggggGGGgTTT",
   "TTTggggTTgg*g..gggg^ggTggTTT",
   "TTTTT^^TTTTTT..gTTTTTTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "5,16": "polarsea:2,7",
   "11,3": "polarsea:5,8",
   "18,13": "polarsea:8,8",
   "22,3": "polarsea:10,8",
   "23,17": "polarsea:14,8"
  },
  "marks": {
   "12,11": "lm_sea_ice"
  },
  "finds": {
   "4,21": {
    "id": "sea_ps_floe",
    "item": "revives",
    "n": 1
   },
   "24,9": {
    "id": "sea_ps_lead",
    "item": "coins",
    "n": 360
   }
  },
  "exits": {
   "13,23": {
    "map": "shore",
    "x": 23,
    "y": 4
   }
  },
  "beyond": {
   "n": "W",
   "e": "W",
   "w": "W"
  },
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 10
 },
 "abyss": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTT^TTgTTTTTTTTTTTTTTTTT",
   "TTTggggggggggTgTTTgTgT^T^TTT",
   "TTTgggggggggggggggggggg!TTTT",
   "TTgggRggggggGGGggggggggTTTTT",
   "TTgg*gggggggggg*gggWWWWWTTTT",
   "TTgggWWWWWggggggggWWWWWWWTTT",
   "TTTgWWWWWWWggggggggWWWWWWTTT",
   "TTggWWWWWWWgggTgggggggggggTT",
   "TTggWWWWWWWgggggggggggTgggTT",
   "TTgTgWWWWWgggggggTggggTggTTT",
   "TTgggggggggggggggggggggggTTT",
   "TTggggggggggggggggΩggggggTTT",
   "TTggTggggg^gggggggggg*gTgTTT",
   "TTgTgggggggggggggggggggggTTT",
   "TTgggggggggg^*ggggWWWWWgggTT",
   "TTTggggggRgggggg*gWWWWWgg^TT",
   "TTTggGGGgggggggg*gWWWWWggTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTgggggggggg!..ggggggggggTTT",
   "TTTgggggg^ggg..gggggggRgTTTT",
   "TTTgggggggggg..gggTTggggTTTT",
   "TTTTTTTTTTTTg..TTTTTTTTggTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTT^TTT"
  ],
  "cast": {
   "9,16": "abyss:2,7",
   "22,20": "abyss:13,7",
   "5,4": "abyss:1,8",
   "12,19": "abyss:5,8",
   "23,3": "abyss:10,8"
  },
  "marks": {
   "18,12": "lm_hydrothermal_vent"
  },
  "finds": {
   "4,21": {
    "id": "sea_ab_floor",
    "item": "bigberries",
    "n": 1
   },
   "23,8": {
    "id": "sea_ab_dark",
    "item": "coins",
    "n": 380
   }
  },
  "exits": {
   "13,23": {
    "map": "openocean",
    "x": 23,
    "y": 11
   }
  },
  "beyond": {
   "n": "W",
   "e": "W",
   "w": "W"
  },
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 10
 }
}, inbound: [
 {
  "from": "ember",
  "tile": "7,11",
  "map": "shore",
  "x": 5,
  "y": 1
 },
 {
  "from": "aquarium",
  "tile": "7,9",
  "map": "shore",
  "x": 6,
  "y": 22
 }
] });
