// ---------- Part 78: WHO HAS BEEN DRAWN ----------
// GENERATED by design/tools/make_people_part.py. Do not hand-edit: re-run it.
//
// The people are being drawn through the same pipeline as the 1183 animals -
// same model, same style string, same background removal - because the thing
// that was wrong with them was that they did not match. Ayr, 2026-09-03: the
// vector people next to the rendered animals were two art languages on one
// screen.
//
// They land one at a time, so this is a manifest rather than a switch. A person
// listed here renders from art/; a person not listed keeps the drawn SVG from
// part56 exactly as before. The cast can therefore be finished in any order,
// over any number of sessions, and the game is never half-broken.
//
// THE AVATAR IS ALL-OR-NOTHING, and that is deliberate. Mixing a rendered front
// view with a drawn side view would change who she is as she turns, which is
// worse than either on its own. She only switches over once all five exist.

const PEOPLE_ART = {
"npc_teacher_dark_t5_long": 1,
"npc_walker_dark": 1,
"ranger_down": 1,
"ranger_left": 1,
"ranger_right": 1,
"ranger_swim": 1,
"ranger_up": 1
};

const RANGER_ART_READY = true;

// Build the art key from the person part56 already decoded. Same fields, fixed
// order - so this cannot drift from the filenames unless the generator changes.
const personArtKey = (p) => {
  if (!p) return null;
  const bits = [p.role, p.hair];
  const tone = ["#f4d9c0", "#e8c39a", "#c98f5f", "#9c6438", "#6f4a2e"].indexOf(p.skin);
  if (tone >= 0) bits.push("t" + (tone + 1));
  ["elder", "beard", "child", "long"].forEach((f) => { if (p[f]) bits.push(f); });
  if (p.covered) bits.push(p.covered);
  return "npc_" + bits.join("_");
};

const personArtUrl = (p) => {
  const k = personArtKey(p);
  return k && PEOPLE_ART[k] ? 'url("art/' + k + '.png")' : null;
};

console.log("[part78] people drawn: " + Object.keys(PEOPLE_ART).filter((k) => k.indexOf("npc_") === 0).length
  + " of the cast | ranger: " + (RANGER_ART_READY ? "all five facings" : "still on the drawn sprite"));
