// ---------- CHAPTER XXIX — THE GUARDIANS ----------
// The 16 legendaries are the only creatures in the Wildlands with no field
// note, and they are the only ones that couldn't have a factual one — they are
// invented. But each was built around a real idea: the ecological role, or the
// restraint, that its living counterparts embody. Their altar inscriptions
// (part12) speak in riddles; the Field Guide entry says plainly what each one
// is FOR. Twelve of them stand for something true about real animals, and the
// note ends on that truth, so the myth points back at the world.
//
// These carry the MYTH badge, like the folklore creatures — they belong to the
// same category of "real thing wearing a story."

const gnote = (k, d, f) => { if (DEX[k]) INFO[k] = { d, h: "The altar at the end of its shrine", s: "MYTH", f }; };

gnote("qilin", "It is said to eat nothing at all, and to tread so lightly it bends no grass",
  "The guardian of the first cave, and the gentlest of them — in the old telling a qilin will not step on a living insect or crush a blade of grass, and appears only in an age worth appearing in. It is a made creature, but the idea underneath is real: the largest and calmest herbivores shape whole landscapes simply by where they walk and what they eat, and they do it without malice. Power and gentleness are not opposites. The biggest animals that ever lived were nearly all grazers.");
gnote("thunderbird", "It hunts the storm itself, and feeds on the charge in the air",
  "Guardian of the high air, and it borrows its name from the thunderbirds of many Indigenous North American nations, who described a being whose wingbeat was thunder and whose eyes threw lightning. The idea it stands for is genuine: the great soaring birds — condors, albatrosses, eagles — ride the invisible architecture of the sky, thermals and pressure fronts and the leading edges of storms, reading weather as terrain. They do not fight the air. They spend almost no effort at all, and go further than anything that flaps.");
gnote("phoenix", "It burns, and what is left of it begins again",
  "The guardian of fire and rebirth, and the only guardian whose whole meaning is a cycle rather than a creature. The phoenix is universal — Egypt, Greece, Persia, China all had one — and the thing it points at is true of fire itself: many landscapes do not merely survive burning, they require it. Some pine cones open only in a fire's heat; some seeds germinate only in ash. The phoenix is what a fire-adapted forest looks like when you tell its story as an animal instead of a system.");
gnote("sarkoth", "The oldest hunter, from before hunger was ever called cruelty",
  "Guardian of the savanna's edge, and its altar says it remembers the first hunt — 'before hunger was cruelty, when killing was only eating.' That is the real idea underneath every apex predator: a lion or a wolf is not evil, it is hungry, and the fear it spreads through a landscape is what keeps that landscape healthy. Wolves changed the course of rivers in Yellowstone by frightening the elk. Sarkoth is the predator seen honestly — necessary, not wicked.");
gnote("nycterion", "It sails the one hour that belongs to neither day nor night",
  "Guardian of the twilight air, named for nykteris, the Greek for bat. It stands for the crepuscular animals — the ones that own dusk and dawn, the hours when the day-hunters have gone to roost and the night-hunters have not yet woken, and a whole shift of life moves in the gap. Bats, nightjars, swifts feeding on the last insects in the last light. It is never seen arriving because that hour is exactly when we stop watching.");
gnote("cetarch", "It sings the map of the world; every ocean is one ocean to it",
  "Guardian of the deep water, its name built from cetus, the ancient word for whale. Its altar note moves through your ribs instead of your ears, which is the true thing it carries: the great whales navigate and speak across entire oceans in frequencies below human hearing, and a fin whale's call can cross a sea. Before we filled the water with engine noise, a whale on one side of an ocean could hear one on the other. Cetarch is that severed conversation, given a body.");
gnote("bathynax", "It turns the earth so that the earth can breathe",
  "Guardian of the underground, and its altar says everything green is standing on its work. That is not mysticism — it is soil. The animals that dig, the earthworms and the moles and the naked mole-rats and the ants, turn and aerate and drain the ground, and without them soil compacts and dies and nothing grows. Darwin's last book was about earthworms, because he had worked out that they had ploughed the whole of England, slowly, over millions of years. Bathynax is the quiet engine under everything.");
gnote("solenn", "It carries the oldest venom of the warm-blooded, and has never used it first",
  "Guardian of the venomous, and its name nods to Solenodon — a real, obscure, venomous mammal, one of the very few, and a living fossil that survived the asteroid. Its whole meaning is restraint: venom is expensive to make and almost every venomous animal on earth would far rather warn you than spend it, because a bite used in defence is a bite not used on dinner. The rattle, the hood, the bright colour — these exist so the animal never has to strike. Solenn's hush 'is not peace, it is restraint,' and that is the truest thing anyone can say about venom.");
gnote("glyptor", "It wears the whole armoury and has never struck a blow",
  "Guardian of the armoured, its name from Glyptodon, the car-sized armadillo of the ice age. It stands for defence as a way of life: the animals that solved survival not by fighting but by becoming impossible to eat — the tortoise, the armadillo, the pangolin, the ankylosaur. 'It cannot be broken, and so it is never fought.' The strategy is ancient and it works, and it is the reason a tortoise can outlive every predator that ever considered it and simply die of old age.");
gnote("velissa", "It is the blink; nothing that runs has outrun the idea of running",
  "Guardian of speed, and pure kinetic idea. It stands for every animal that bet its life on velocity — the cheetah, the pronghorn, the peregrine — and for the strange fact that speed is often a memory: the pronghorn runs from a cheetah that has been extinct for 12,000 years, and the swiftness remains because nothing selected it away. Velissa 'crosses the horizon twice before you finish the thought,' which is roughly what a peregrine's stoop actually does to a moment.");
gnote("bramwold", "The herd remembering itself; it grieved every plain we ploughed and kept walking",
  "Guardian of the great herds, and the most sorrowful of them. It stands for migration — the wildebeest, the bison, the caribou, the springbok — the animals that move in millions along routes older than any border, and for what we did to them. The American bison went from tens of millions to a few hundred; the springbok migrations of millions were seen for the last time in the 1890s and simply stopped. 'It grieved every plain we ploughed and it kept walking.' Bramwold is the herd that used to shake the ground.");
gnote("pyrelynx", "It sets the fires that forests need; we called it destroyer, and the seeds knew better",
  "Guardian of fire's other face — not rebirth, but the deliberate, ecological use of burning. Its altar is the clearest statement in the game of a hard idea: fire is not the enemy of a wild landscape, it is part of its maintenance, and a century of suppressing every flame is exactly what built the catastrophic megafires we have now. Indigenous fire management understood this for tens of thousands of years. 'We called it destroyer for a century. The seeds knew better.' Pyrelynx is the fire we should have kept lighting.");
gnote("rimehorn", "It walked out of the ice we thought had taken it, carrying winter like a sleeping child",
  "Guardian of the cold, and an elegy for the ice age megafauna — the mammoth, the woolly rhino, the muskox that alone made it through. It stands for cold not as cruelty but as a world of its own, one that had its own giants and lost nearly all of them when the ice withdrew. 'It carries winter the way a mother carries a sleeping child. The cold here is not cruel. It is careful.' Rimehorn is what the tundra remembers, and it is the guardian most tied to the animals in the Vigil.");
gnote("myrmedon", "It eats the multitude and never empties a single nest",
  "Guardian of the small and the swarming, its name from myrmex, the Greek for ant. It stands for the anteaters and pangolins and all the animals that live on the most numerous creatures on earth — and for the restraint that makes that living sustainable. A giant anteater takes only a few hundred insects from each colony and moves on, so the colony survives and it can return: it farms rather than harvests. 'Restraint, at the scale of millions.' The whole living world runs on the insects, and the animals that eat them have learned not to finish them.");
gnote("nyxfang", "It is what the dark is doing when you are not looking",
  "Guardian of the night, from Nyx, the Greek goddess of night herself. It stands for the nocturnal majority — most mammals are night animals, and always have been, because the age of dinosaurs pushed our ancestors into the dark and we have carried the equipment ever since. The night is not empty; it is the busier shift, and it is the one we evolved to be blind in. 'It has been beside you for some time.' Nyxfang is everything that has been living the other half of every day, unwatched.");
gnote("verdanmane", "It moves so slowly the forest grew around it and called it home",
  "Guardian of the canopy, and the stillest of them all. It stands for the sloth and every animal that made slowness a strategy — that decided a leaf is worth so little energy that the correct response is to almost never move, and grow a garden of algae in your own fur while you think about it. 'It has not touched the ground in nine hundred years.' In a guide full of the fastest and the fiercest, Verdanmane is the argument that doing almost nothing, very carefully, is also a way to win — and it is the way the single slowest mammals on earth have quietly outlasted animals far grander than themselves.");
