// ---------- Part 78: WHO HAS BEEN DRAWN ----------
// GENERATED by design/tools/make_people_part.py. Do not hand-edit: re-run it.
//
// The people are being drawn through the same pipeline as the 1183 animals -
// same model, same style string, same background removal - because the thing
// that was wrong with them was that they did not match. Ayr, 2026-09-03: the
// vector people next to the rendered animals were two art languages on one
// screen.
//
// They land one at a time, so this is a manifest rather than a switch. A person
// listed here renders from art/; a person not listed keeps the drawn SVG from
// part56 exactly as before. The cast can therefore be finished in any order,
// over any number of sessions, and the game is never half-broken.
//
// THE AVATAR IS ALL-OR-NOTHING, and that is deliberate. Mixing a rendered front
// view with a drawn side view would change who she is as she turns, which is
// worse than either on its own. She only switches over once all five exist.

const PEOPLE_ART = {
"npc_climber_dark": 1,
"npc_climber_dark_t3": 1,
"npc_farmer_dark": 1,
"npc_farmer_dark_t1": 1,
"npc_farmer_dark_t1_long": 1,
"npc_farmer_dark_t2": 1,
"npc_farmer_dark_t2_long": 1,
"npc_farmer_dark_t3": 1,
"npc_farmer_dark_t4_long": 1,
"npc_farmer_dark_t5": 1,
"npc_farmer_dark_t5_long": 1,
"npc_guard_dark": 1,
"npc_night_dark": 1,
"npc_night_dark_t1": 1,
"npc_pilot_dark_t1": 1,
"npc_pilot_dark_t2": 1,
"npc_pilot_dark_t3": 1,
"npc_plain_curly_t1": 1,
"npc_plain_curly_t3": 1,
"npc_plain_curly_t3_long": 1,
"npc_plain_curly_t4_long": 1,
"npc_plain_dark": 1,
"npc_plain_dark_beard": 1,
"npc_plain_dark_child": 1,
"npc_plain_dark_long": 1,
"npc_plain_dark_scarf": 1,
"npc_plain_dark_t1": 1,
"npc_plain_dark_t1_beard": 1,
"npc_plain_dark_t1_long": 1,
"npc_plain_dark_t2": 1,
"npc_plain_dark_t2_beard": 1,
"npc_plain_dark_t2_long": 1,
"npc_plain_dark_t3": 1,
"npc_plain_dark_t3_beard": 1,
"npc_plain_dark_t3_child": 1,
"npc_plain_dark_t3_long": 1,
"npc_plain_dark_t3_scarf": 1,
"npc_plain_dark_t4": 1,
"npc_plain_dark_t4_beard": 1,
"npc_plain_dark_t4_scarf": 1,
"npc_plain_dark_t4_turban": 1,
"npc_plain_dark_t5": 1,
"npc_plain_dark_t5_long": 1,
"npc_plain_dark_turban": 1,
"npc_plain_grey_elder": 1,
"npc_plain_grey_elder_beard": 1,
"npc_plain_grey_elder_long": 1,
"npc_plain_grey_t1_elder": 1,
"npc_plain_grey_t1_elder_long": 1,
"npc_plain_grey_t2_elder": 1,
"npc_plain_grey_t2_elder_long": 1,
"npc_plain_grey_t3_elder": 1,
"npc_plain_grey_t5_elder": 1,
"npc_plain_red_t1_beard": 1,
"npc_plain_red_t1_long": 1,
"npc_plain_red_t2": 1,
"npc_plain_white_t1": 1,
"npc_plain_white_t1_long": 1,
"npc_plain_white_t2": 1,
"npc_plain_white_t2_long": 1,
"npc_plain_white_t3": 1,
"npc_scientist_dark_t1": 1,
"npc_scientist_dark_t1_long": 1,
"npc_scientist_dark_t2": 1,
"npc_scientist_dark_t2_long": 1,
"npc_scientist_dark_t3": 1,
"npc_scientist_dark_t3_long": 1,
"npc_scientist_dark_t4": 1,
"npc_teacher_dark_t1_long": 1,
"npc_teacher_dark_t2": 1,
"npc_teacher_dark_t2_long": 1,
"npc_teacher_dark_t4": 1,
"npc_teacher_dark_t5_long": 1,
"npc_walker_dark": 1,
"npc_walker_dark_t1": 1,
"ranger_down": 1,
"ranger_left": 1,
"ranger_right": 1,
"ranger_swim": 1,
"ranger_up": 1
};

const RANGER_ART_READY = true;

// Build the art key from the person part56 already decoded. Same fields, fixed
// order - so this cannot drift from the filenames unless the generator changes.
const personArtKey = (p) => {
  if (!p) return null;
  const bits = [p.role, p.hair];
  const tone = ["#f4d9c0", "#e8c39a", "#c98f5f", "#9c6438", "#6f4a2e"].indexOf(p.skin);
  if (tone >= 0) bits.push("t" + (tone + 1));
  ["elder", "beard", "child", "long"].forEach((f) => { if (p[f]) bits.push(f); });
  if (p.covered) bits.push(p.covered);
  return "npc_" + bits.join("_");
};

// Anyone the game asks for and cannot find is reported once, by key. That is
// the list of who still has to be drawn, and it comes from the running game
// rather than from a scan of the source - which is the only way to be sure the
// cast list matches the people actually standing on the maps.
const PEOPLE_MISSING = {};
const personArtUrl = (p) => {
  const k = personArtKey(p);
  if (!k) return null;
  if (PEOPLE_ART[k]) return 'url("art/' + k + '.png")';
  if (!PEOPLE_MISSING[k]) {
    PEOPLE_MISSING[k] = 1;
    console.warn("[part78] no drawing for " + k);
  }
  return null;
};

console.log("[part78] people drawn: " + Object.keys(PEOPLE_ART).filter((k) => k.indexOf("npc_") === 0).length
  + " of the cast | ranger: " + (RANGER_ART_READY ? "all five facings" : "still on the drawn sprite"));
