// GENERATED by design/tools/forge_vigil.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "vigil", maps: {
 "vigil": {
  "rows": [
   "TTTTTTTTnTTTTTTTTTTnTTTTTTTT",
   "TTTggggT..TTTTTTTTT..TTTTTTT",
   "TTTggggg..TTTTTTTTT..T^TTTTT",
   "TTTTgggg.............!TTgTTT",
   "TTTTggg!.............gTggTTT",
   "TTTggTggggggg..gggggggggTTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgTWWWggggg..gggggWWWTgTTT",
   "TTTgggggggggg..gΩggggggggTTT",
   "TTgggggggg!gg..gggggggggggTT",
   "TTTggggggg*gg..g!gggggggggTT",
   "TTT!ggggggggg..ggggggggg!gTT",
   "e..........................e",
   "T..........................T",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTTgggggg!gg..g!ggggggggTTT",
   "TTTggggCggggg..gggggMgggg^TT",
   "TTTggTggggggg..gg*gg*ggggTTT",
   "TTTgggggggggg..gg*ggggTgTgTT",
   "TTgTggggggggg..gggggggggggTT",
   "TTggggggggggg..gggggggggggTT",
   "TTgTTggggggTT..TTTTTTTgggTTT",
   "TTTTTTTgTTTTT..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "10,9": "vigil:4,1",
   "16,10": "vigil:11,1",
   "10,15": "vigil:4,7",
   "16,15": "vigil:11,7",
   "3,11": "vigil:west",
   "24,11": "vigil:east",
   "7,4": "vigil:nw",
   "21,3": "vigil:ne"
  },
  "marks": {
   "16,8": "lm_vigil_candles"
  },
  "finds": {
   "3,20": {
    "id": "vig_gate_pool",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "0,12": {
    "map": "vig1",
    "x": 13,
    "y": 22
   },
   "27,12": {
    "map": "vig4",
    "x": 13,
    "y": 22
   },
   "8,0": {
    "map": "vig6",
    "x": 13,
    "y": 22
   },
   "19,0": {
    "map": "vig8",
    "x": 13,
    "y": 22
   },
   "13,23": {
    "map": "town9",
    "x": 1,
    "y": 16
   }
  },
  "beyond": {},
  "land": [
   13,
   20
  ],
  "links": {},
  "gen": 13
 },
 "vig1": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggTgggTTTT",
   "TTTTTgggggggg..gggggGGGggTTT",
   "TTTgggggggggg..ggggggg*TgTTT",
   "TTTTggggg*ggg..ggggggggggTTT",
   "TTgTggggggggg..ggggggTgggTTT",
   "TTggggggg!ggg..ggggggggggTTT",
   "TTTggggggggg*..gggΩgggTgTTTT",
   "TTgTggggggggg..gggggggggTTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgTgggggggg..*gggggggTgTTT",
   "TTTTgggggRggg..ggggggggggTTT",
   "TTTTggggggggg..gg!gggggTgTTT",
   "TTTTgTggggggg..gggggggggTTTT",
   "TTTgTgggggggg..ggggWWWggTTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgGGGGGgggg..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgTggggTggT..gggggggggTTTT",
   "TTTTTTTTTTTTT..TgTTTggTggTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "9,8": "vig1:7,3",
   "17,15": "vig1:7,7",
   "9,14": "vig1:10,3"
  },
  "marks": {
   "18,9": "lm_thylacine_film"
  },
  "finds": {
   "4,3": {
    "id": "vig_v1_corner",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "13,23": {
    "map": "vigil",
    "x": 1,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "vig2",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig2": {
  "rows": [
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTT*ggggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggTgggTTT",
   "TTTTggggggg..gggggggGGGTgTTT",
   "TTTgggggggg..ggg*gggggggTTTT",
   "TTTgggggggg..ggggggggggTTTTT",
   "TTTgggTg*gg..gggggggggggTTTT",
   "TTTggggg!gg..gggggΩggggTTTTT",
   "TTTTggggggg..gggggggggggTTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTggggggggg..*gggggggggggTTT",
   "TTTgggggggg....ggggggRggTTTT",
   "TTTgggRgggg....gggggggggTTTT",
   "TTTgTgggggggg..gggggggggTTTT",
   "TTTgggggggggg..g!ggggggTgTTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTgWWWggggg..ggggggggggTTT",
   "TTTTGGGGGgggg..ggRgggggggTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "8,8": "vig2:7,3",
   "16,15": "vig2:7,7",
   "6,13": "vig2:3,3",
   "17,19": "vig2:6,8",
   "21,12": "vig2:14,8"
  },
  "marks": {
   "18,8": "lm_tiger_census"
  },
  "finds": {
   "23,20": {
    "id": "vig_v2_hollow",
    "item": "coins",
    "n": 450
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "vig1",
    "off": 0
   },
   "n": {
    "map": "vig3",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig3": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTgTT^T^T^TTgTTTTTTT",
   "TTTTgggggggggggggggggggTTTTT",
   "TTTggggTggggggggggggTTggggTT",
   "TTTTggggggggggggggggGGGgggTT",
   "TTTgTgggggggggggggggggggggTT",
   "TTTgggggggggggggggggggggggTT",
   "TTTggggggggggggggggggggggTTT",
   "TTTggggggggggggggΩggggTgTTTT",
   "TTTggggg!ggggggggggggggggTTT",
   "TTTgTgggg*gggggggggggggggTTT",
   "TTTggggggggggggggggggg*ggTTT",
   "TTggggggggg..gggggggRgggTTTT",
   "TTTgTgggggg..ggggggggg*ggTTT",
   "TTTgggggggg..ggg!ggggggggTTT",
   "TTTTggggggg..gggggggggggTT^T",
   "TTTTgggRggg..gggggWWWWWggTTT",
   "TTTTggggggg..gggggWWWWWggTTT",
   "TTTgggggggg..gggggWWWWWggTTT",
   "TT^gGGGGGgg..gggggggggggTTTT",
   "TTTgggggggg..gggggggggggTTTT",
   "TTTgggggggg..g*gggggggggTTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "8,9": "vig3:7,3",
   "16,14": "vig3:7,7",
   "20,12": "vig3:9,1",
   "7,16": "vig3:1,8"
  },
  "marks": {
   "17,8": "lm_mammoth_steppe"
  },
  "finds": {
   "4,3": {
    "id": "vig_v3_ice",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   11,
   21
  ],
  "links": {
   "s": {
    "map": "vig2",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig4": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTggTTggggg*g..ggggggggggTTT",
   "TTTgggggggggg..gggggTggggTTT",
   "TTTgggggggggg..gggggGGGgggTT",
   "TTggggggggggg..ggggggTggggTT",
   "TTggggggggg*g..gggggggggggTT",
   "TTgTggggggggg..gggggggggggTT",
   "TTggggggg!ggg..ggggggggTgTTT",
   "TTTgT*ggggggg..gggΩggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggg*ggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gg!gggggggTTT",
   "TTTgWWWWWgggg..gggggggggTTTT",
   "TTTgWWWWWgggg..ggggggggTgTTT",
   "TTTgWWWWWgggg..ggggggggTgTTT",
   "TTTgTGGGGgggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTg^ggggggg..gggggTTgTgTTT",
   "TTTTTTTTTTTgg..TTTgTTTTT^TTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "9,8": "vig4:7,3",
   "17,15": "vig4:7,7"
  },
  "marks": {
   "18,9": "lm_dodo"
  },
  "finds": {
   "24,21": {
    "id": "vig_v4_isle",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "13,23": {
    "map": "vigil",
    "x": 26,
    "y": 12
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "vig5",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig5": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTT^TTTTTTTTTTTTTTTTTTTT",
   "TTgggggggggTTTTggTgggggTTTTT",
   "TTTgTggggggggggggggggggggTTT",
   "TTTggggTggggggggggggGGGTgTTT",
   "TTTTgggggggggggggggggggggTTT",
   "TTTTgTggggggggggggggggggg^TT",
   "TTTggggggggggggggggggggggTTT",
   "TT^ggggggggggg*gggΩggggggTTT",
   "TTTTggggg!gggggggggggggggTTT",
   "TTTTggggggggggggggggggggggTT",
   "TTTTggggggggggggggggggggTgTT",
   "TTTTgTgggggg*..gggggggggggTT",
   "TTTgggggggggg..ggg*ggggggTTT",
   "TTTgggggggggg..gg!gggggggTTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTggWWWggggg..gggggggggggTT",
   "TTTgggggggggg..gg*ggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgGGGGGgggg..ggggggTggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "9,9": "vig5:7,3",
   "17,14": "vig5:7,7"
  },
  "marks": {
   "18,8": "lm_martha"
  },
  "finds": {
   "3,2": {
    "id": "vig_v5_sky",
    "item": "coins",
    "n": 460
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "vig4",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig6": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTggggggggggg..ggggggggggTTT",
   "TTTggTggggggg..ggggggTggggTT",
   "TTTgTgggggggg..ggg*gGGGggTTT",
   "TTTgggggggggg..ggggggTgggTTT",
   "TTTggggTggggg..gggggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgTgggg!ggg..gggggggggggTT",
   "TTTgggggggggg..*ggΩgggggggTT",
   "TT^gggggggggg..gggg*ggggggTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTgTgggggggg..gggggggggggTT",
   "TT^gggggggggg..gggggggggggTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTggggggggggg..gg!gggggggTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTggWWWgg*gg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTGGGGGgggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTTggggggggg..ggggggggTggTT",
   "TTTTTTTTTTTgT..ggTTTTTTTTTTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "9,8": "vig6:7,3",
   "17,15": "vig6:7,7"
  },
  "marks": {
   "18,9": "lm_mosquito"
  },
  "finds": {
   "24,21": {
    "id": "vig_v6_song",
    "item": "berries",
    "n": 3
   }
  },
  "exits": {
   "13,23": {
    "map": "vigil",
    "x": 8,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "vig7",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig7": {
  "rows": [
   "TTT^TTTTTTTTTTTTTTTTTTTTTTTT",
   "TT^ggTTTTTTTgTTggggTTggTTTTT",
   "TTTTgggTTggggggggggg*ggggTTT",
   "TTTTggggggggggggggggTggggTTT",
   "TTTgggggggggggggggggGGGggTTT",
   "TTTTgggggggggggggggggggTgTTT",
   "TTTTgggggggggggggggggTgTgTTT",
   "TTTgTggggggggggggggggggggTTT",
   "TTTgggggΩgggggggggggggggTTTT",
   "TTTgTggggggggggg!ggggggggTTT",
   "TTgggggggggggggggWWWWWgggTTT",
   "TTTgggggg*ggggggWWWWWWWggTTT",
   "TTTggggggggg*..gWWWWWWWgggTT",
   "TTTgggggggg*g..gWWWWWWWggTTT",
   "TTTgTgggggggg..ggWWWWWggggTT",
   "TTTgTgggg!ggg..gggggggggggTT",
   "TTTgggggggggg..gggggggggTgTT",
   "TTTTTgggggggg..gggggggggggTT",
   "TTTTgTggggggg..gggggggggggTT",
   "TTTTGGGGGgggg..gggggggggTgTT",
   "TTTTggggggggg..gggggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "16,9": "vig7:7,3",
   "9,15": "vig7:7,7"
  },
  "marks": {
   "8,8": "lm_river_dolphin"
  },
  "finds": {
   "4,3": {
    "id": "vig_v7_river",
    "item": "antidote",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "vig6",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig8": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTggTggggggg..gggggggggggTT",
   "TTTgggTgggggg..gggggGGGgggTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggTgggTT",
   "TTTgggggggggg..*gggggggTggTT",
   "TTTTggggg!ggg..gggggggggggTT",
   "TTTgggggggggg..gggΩgggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggggTT",
   "TTTTggggggggg..gg!ggggggg^TT",
   "TTTTgTgggggg*..ggggggggTgTTT",
   "TTTTgWWWggggg..ggggggggTgTTT",
   "TTTTgTggggggg..gggggggg*ggTT",
   "TTTTGGGGGgggg..ggggggggggTTT",
   "TTTTggg*ggggg..ggggggggggTTT",
   "TTTTggggTTT^g..ggggggggggTTT",
   "TTTTTTTTTTTTT..TTTTTTg^T^TTT",
   "TTTTTTTTTTTTTs.TTTTTTTTTTTTT"
  ],
  "cast": {
   "9,8": "vig8:7,3",
   "17,15": "vig8:7,7"
  },
  "marks": {
   "18,9": "lm_frozen_zoo"
  },
  "finds": {
   "4,3": {
    "id": "vig_v8_edge",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "13,23": {
    "map": "vigil",
    "x": 19,
    "y": 1
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "vig9",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig9": {
  "rows": [
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg..gggggggggggggTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgTgggggg..gggggggGGGggTTT",
   "TTTTggggggg..gggggggggTgggTT",
   "TTTTTgggggg..gggggggggggTgTT",
   "TTTgggTgggg..ggggggggggggTTT",
   "TTTgTggg!gg..gggggΩggggggTTT",
   "TTgg*gggggg..ggggggggg*ggTTT",
   "TTTgTgggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg....ggWWWWWgggTTT",
   "TTTgTgggggg....ggWWWWWgTgTTT",
   "TTTgggggggggg..ggWWWWWggTgTT",
   "TTTgggggggggg..g!gggggggggTT",
   "TTTgTgggggggg..ggggggggggTTT",
   "TTTgTWWWggggg..ggggggggggTTT",
   "TTTgT*ggggggg..gggggggg*gTTT",
   "TTTgGGGGGgggg..ggggggggggTTT",
   "TTTTggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "8,8": "vig9:7,3",
   "16,15": "vig9:7,7"
  },
  "marks": {
   "18,8": "lm_chinampas"
  },
  "finds": {
   "24,21": {
    "id": "vig_v9_ark",
    "item": "coins",
    "n": 480
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "vig8",
    "off": 0
   },
   "n": {
    "map": "vig10",
    "off": 0
   }
  },
  "gen": 13
 },
 "vig10": {
  "rows": [
   "TTTTTTTTTTTTTTTTTTTTTTTTTTTT",
   "TTTTTTTTTTTTTTTggTTTTTTggTTT",
   "TTTTTTTTTTgTTggggggggggTgTTT",
   "TTTggggggggggggggggggggggTTT",
   "TTTTggggggggggggggggGGGgg^TT",
   "TTTgggTTgggggggggggggggggTTT",
   "TTTggggggggggggggggggggTgTTT",
   "TTTgggggggggggggggggggggTTTT",
   "TTTggggggggggggggΩgggggggTTT",
   "TTTggggg!ggggggggggggggggTTT",
   "TTTgggggggggggg*ggggggggg^TT",
   "TTTTgggggggggggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg..gggggggggggggTT",
   "TTggggggggg..ggg!gggggggTgTT",
   "TTTgggggggg..gggggggggggggTT",
   "TTTggggggg*..gggggggggggTgTT",
   "TTgTgggggg*..ggggggWWWggggTT",
   "TTggggggggg..gggggggggggggTT",
   "TTTgGGGGGgg..gggggggggggggTT",
   "TTggggggggg..gggggggggggggTT",
   "TTggggggggg..*ggggggggggggTT",
   "TTTgggggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "8,9": "vig10:7,3",
   "16,14": "vig10:7,7"
  },
  "marks": {
   "17,8": "lm_arabian_oryx"
  },
  "finds": {
   "4,3": {
    "id": "vig_v10_kept",
    "item": "bigberries",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   11,
   21
  ],
  "links": {
   "s": {
    "map": "vig9",
    "off": 0
   }
  },
  "gen": 13
 }
}, inbound: [
 {
  "from": "town9",
  "tile": "0,16",
  "map": "vigil",
  "x": 13,
  "y": 22
 }
] });
