// GENERATED by design/tools/forge_highveld.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "highveld", maps: {
 "route5": {
  "rows": [
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTTgg^g^ggg..ggGGGGGgggggTT",
   "TTTTgggggggg..gggggggg*ggTTT",
   "TTTTggTTTgTT.TTgggTgggTTgTTT",
   "TTTT^TTT^TTTVTTT^TTT^TTT^TTT",
   "TTTTGGGGGggg..gggggggggggTTT",
   "TTTgGGGGGgg*..gggTgGGGGGGTTT",
   "TTTTGGGGGggg..ggg*GGGGGTGTTT",
   "TTT*gggRgg*g..ggTggGGGGTGTTT",
   "TTT!gggggg*g..ggggggggggTTTT",
   "e.............ggggggRggggTTT",
   "T.............ggggggggggTT^T",
   "TTTTgggggggg..gggggggggggTTT",
   "TTTgggggg¡g*..gggg*ggTgggTTT",
   "TTTgGGGGGggg...ggg*Ω*gTTgTTT",
   "TTTgGGGGGggg...ggggggTgggTTT",
   "TT^gGGGGGgggg..g⁂ggggggggTTT",
   "TTTggggggRggg..ggggggggggTTT",
   "TTggggggggggg..gggggg*gggTTT",
   "T^ggTgggggggg..ggggGGGGGg^TT",
   "TTTgT*ggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggggggggg^TT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "12,5": "route5:7,1",
   "3,10": "route5:gate",
   "7,9": "route5:4,4",
   "20,11": "route5:11,10",
   "9,18": "route5:9,12"
  },
  "marks": {
   "19,15": "lm_grass_roots"
  },
  "finds": {
   "23,18": {
    "id": "hv_r5_step",
    "item": "berries",
    "n": 3
   },
   "4,2": {
    "id": "hv_r5_top",
    "item": "coins",
    "n": 180
   }
  },
  "exits": {
   "0,11": {
    "map": "savanna",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "seg_s1",
    "off": 0
   },
   "s": {
    "map": "town5",
    "off": 0
   }
  },
  "gen": 6
 },
 "seg_s1": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggg*g..ggggggggggTT",
   "TT^gGGGGGggggg..Tggggg*gggTT",
   "TTTgGGGGGg*ggg..gggGGGGGggTT",
   "TTT⁅GGGGGggggg..ggTGGGGGggTT",
   "TTTTgggggg⁂ggg..gggGGGGGgTTT",
   "TTTTggggggg*gg..ggggg*ggggTT",
   "TTTggRgggggggg..ggRgggggggTT",
   "TTTgTggggggggg..ggggggggggTT",
   "TTTgTgg*Ωggggg..gT*ggTggTgTT",
   "TTTgTggggggWgg..g*gWggggggTT",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "WWWWWWWWWWWWWW..WWWWWWWWWWWW",
   "WTTggggggWgggg..*ggggWgggTWT",
   "TTTggggggggggg..gggggggggTTT",
   "TTTggggRgggg....ggggggR*gTTT",
   "TTTggggggggg....gggggggggTTT",
   "TTTTGTGGGgTg..ggRgGGGGGgggTT",
   "TT^gGGGGGg*g..ggg*GGGGGgggTT",
   "TTTgGGGGGggg..ggggGGGGGgggTT",
   "TTTgggggTggg..ggg¡ggggg^^TTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "5,8": "seg_s1:1,2",
   "16,18": "seg_s1:6,8",
   "18,8": "seg_s1:10,9",
   "7,16": "seg_s1:3,10",
   "22,16": "seg_s1:11,10"
  },
  "marks": {
   "8,10": "lm_whistling_thorn"
  },
  "finds": {
   "3,2": {
    "id": "hv_s1_corner",
    "item": "treats",
    "n": 2
   },
   "24,9": {
    "id": "hv_s1_spruit",
    "item": "wakeberry",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "route5",
    "off": 0
   },
   "n": {
    "map": "seg_s2",
    "off": 0
   }
  },
  "gen": 6
 },
 "seg_s2": {
  "rows": [
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTTgggggggg..gggg*gggggggg^T",
   "TTTgGGGGGgg..ggTgggTggggggTT",
   "TTTgTGGGGgg..ggg*ggGGGGGggTT",
   "TT^gGGGGG⁌g..gggRggGGGGGTgTT",
   "TTTgggggggg..ggggggGGGGGggTT",
   "TTT!ggggggg..gg*ggggg*ggggTT",
   "e............g*ggggggggg*gTT",
   "T............g*gg*ggggggggTT",
   "TTggggggggg..gggggggggRggTTT",
   "TTg^ggggRgg..gggg⁂ggggggggTT",
   "TTgg.....gg..gggggggΩgggggTT",
   "T^g*.WWW.gg..gggggg...ggggTT",
   "TTgg.WWW.gg.....ggggggggTgTT",
   "TTTg.....gg.....ggggggTgggTT",
   "TTTgggggg**ggg..ggggg*gTggTT",
   "TTTggRgggTgggg..ggggggggggTT",
   "TTTggggggggggg..gRgGGGGGggTT",
   "TTTgggggTggggg..gggGGGGGgg^T",
   "TTTgGGGGGggggg..gggGGGGGggTT",
   "TTT^¡ggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "3,7": "seg_s2:gate",
   "16,5": "seg_s2:6,1",
   "5,17": "seg_s2:1,5",
   "22,10": "seg_s2:13,5",
   "17,18": "seg_s2:6,7",
   "8,11": "seg_s2:4,10"
  },
  "marks": {
   "20,12": "lm_aardvark_burrow"
  },
  "finds": {
   "24,12": {
    "id": "hv_s2_mound",
    "item": "antidote",
    "n": 1
   },
   "4,3": {
    "id": "hv_s2_rocks",
    "item": "coins",
    "n": 190
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_sarkoth",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_s1",
    "off": 0
   },
   "n": {
    "map": "seg_s3",
    "off": 0
   }
  },
  "gen": 6
 },
 "seg_s3": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTggg*gggggg..ggg*ggTgggTTT",
   "TTTgGGGGGgggg..ggggggggggTTT",
   "TTggGGGGGgggg..gRgggggTgTTTT",
   "TTTgGGGGGgggg..ggg*ggggggTTT",
   "TTTgggggggggg..ggggggg*TgTTT",
   "TTTgggggRgggg..gggg*gggggTTT",
   "TTTgggggggggg..gWWWWWgggg^TT",
   "TTTgg¡ggggggg..WWWWWWWggg^TT",
   "TTTggggg*gggg..WWWWWWWgggTTT",
   "TTTTGGGGGgggg..WWWWWWWggggTT",
   "TTTTGGGGGgggg..⁂WWWWWggTg^TT",
   "TTTgGGGGGgggg..gggggggRggTTT",
   "TT^ggggggg*....gggggggggg^TT",
   "TTTg*ggRggg........ΩgggTgTTT",
   "TTTgTgggggg..ggggggggggggTTT",
   "TTTgggggggg..ggggg*g⁂ggTgTTT",
   "TTTgggggTgg..gg*Rggggg^^gTTT",
   "TTTg*gggggT..ggggggggggggTTT",
   "TTggGGGGGgg..ggggggGGGGGgTTT",
   "TTgggggg*gg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "8,7": "seg_s3:4,3",
   "22,13": "seg_s3:9,4",
   "7,15": "seg_s3:5,7",
   "16,18": "seg_s3:7,7",
   "16,4": "seg_s3:9,7"
  },
  "marks": {
   "19,15": "lm_dung_beetle"
  },
  "finds": {
   "24,8": {
    "id": "hv_s3_water",
    "item": "berries",
    "n": 3
   },
   "4,21": {
    "id": "hv_s3_south",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "seg_s2",
    "off": 0
   },
   "n": {
    "map": "seg_s4",
    "off": 0
   }
  },
  "gen": 6
 },
 "seg_s4": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTggg^gggggg..ggRgggggggTTT",
   "TTTg^gggggggg..ggggg^^^gg^TT",
   "TTggggggggggg..ggggggggggTTT",
   "TTgTgggggg⁂gg..ggggggΩggg^TT",
   "TTgTGGGGGgggg..ggggggggggTTT",
   "TTggggg*ggggg...ggggTggggTTT",
   "TTg!ggggggggg...ggTgggggg^TT",
   "e...............ggTgggggggTT",
   "T.....⁅.........gggggggTggTT",
   "TTgggggg*ggggg..gggggggTgTTT",
   "TTggggggTRgggg..ggggggggTgTT",
   "TTgggggggggggg..gggGGG*Tgg^T",
   "TTTgggggggggg...gggggggggg^T",
   "TTgggggTggggg...ggggggggggTT",
   "TT^ggg*Tggggg..ggggRggg^gTTT",
   "TT^gTgggggggg..gggggg^gggTTT",
   "TTTT*gggggg*g..gggggg^g*gTTT",
   "TTTTgGGGGGggg..gg¡gggggggTTT",
   "TTTgggggggggg..*ggggggggggTT",
   "TTTgggggggggg..gggggggggg^TT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "3,9": "seg_s4:gate",
   "17,3": "seg_s4:14,1",
   "9,13": "seg_s4:3,4",
   "19,17": "seg_s4:11,4"
  },
  "marks": {
   "21,6": "lm_bone_anvil"
  },
  "finds": {
   "24,8": {
    "id": "hv_s4_crag",
    "item": "bigberries",
    "n": 1
   },
   "4,21": {
    "id": "hv_s4_south",
    "item": "coins",
    "n": 200
   }
  },
  "exits": {
   "0,10": {
    "map": "shrine_velissa",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_s3",
    "off": 0
   },
   "n": {
    "map": "town6",
    "off": 0
   }
  },
  "gen": 6
 },
 "town6": {
  "rows": [
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTTgggggggggg..!ggggggggTTTT",
   "TTgTgTggggggg..gggggggggg^TT",
   "TTggT*gggCggg..gggYggggH*TTT",
   "TTTggTggggggg..g*ggggggTgTTT",
   "TTTgggg¦............¦ggggTTT",
   "TTTg*Ωg..............gΩgg^TT",
   "TTTgggg...Ω.....Ω....g*TgTTT",
   "TTTgggg.....Ω........*ggTTTT",
   "TTTgggg..R...........ggHgTTT",
   "TTT*Hgg...Ω......Ω...ggggTTT",
   "TTTgggg¦............¦ggggTTT",
   "TTggggΩgggggg..ggggggggggTTT",
   "TTTg*gggggggg..ggggggggg^TTT",
   "T^gg.....................TTT",
   "TTgg.....................TTT",
   "TTTg!gggΩΩg¦g..g¦ΩgggggTgTTT",
   "T^ggggggggggg..ggggMgggggTTT",
   "TTgggΩggHgggg..ggVgggggggTTT",
   "TTgg*ggggggg!..ΩgggΩgggHg^TT",
   "TTTgggggggggg..gggggggggg^TT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "15,3": "town6:gate",
   "12,21": "town6:9,3",
   "4,18": "town6:8,12",
   "9,11": "town6:3,8",
   "17,20": "town6:9,10"
  },
  "marks": {
   "5,8": "lm_rock_art",
   "15,21": "decor:goats",
   "19,21": "decor:goats",
   "5,20": "decor:goats",
   "10,9": "decor:cairn",
   "17,12": "decor:cairn",
   "22,8": "decor:cairn",
   "16,9": "decor:stall",
   "10,12": "decor:stall",
   "17,18": "decor:well",
   "12,10": "decor:bench",
   "6,14": "decor:crates",
   "8,18": "decor:garden",
   "9,18": "decor:garden"
  },
  "finds": {
   "24,13": {
    "id": "hv_t6_crag",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_s4",
    "off": 0
   },
   "n": {
    "map": "route6",
    "off": 0,
    "fallback": {
     "tile": "13,0",
     "ch": "n",
     "map": "route6",
     "x": 7,
     "y": 14
    }
   }
  },
  "gen": 6
 }
}, inbound: [
 {
  "from": "savanna",
  "tile": "7,9",
  "map": "route5",
  "x": 1,
  "y": 11
 },
 {
  "from": "shrine_sarkoth",
  "tile": "7,9",
  "map": "seg_s2",
  "x": 1,
  "y": 8
 },
 {
  "from": "shrine_velissa",
  "tile": "7,9",
  "map": "seg_s4",
  "x": 1,
  "y": 10
 },
 {
  "from": "route6",
  "tile": "7,15",
  "map": "town6",
  "x": 13,
  "y": 1
 }
] });
