// GENERATED by design/tools/forge_volcanic.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "volcanic", maps: {
 "route7": {
  "rows": [
   "TTTggggggggg..gggggggggggTTT",
   "TT^ggggggggg..gggggggggggTTT",
   "TTTggggggggg..ggGGGGGggggTTT",
   "TTTTgg^g^ggg..ggggggg⁌gggTTT",
   "TTT^^gg^T^gg.T^gg^^ggg^ggTTT",
   "TTTT^TTT^TTTVTTT^TTT^TTT^TTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggRgggg..ggggggRggggTTT",
   "TTTgTGGGGggg..gggg.....ggTTT",
   "TTTgTGGGGggg..gggg.....ggg^T",
   "TTTgGGGGGggg..ggggg...gTgTTT",
   "TTTggggggggg..ggggggggggg^TT",
   "TTTTgggggggg..gggggΩgTgggTTT",
   "TTTg^ggggggg..gggggggggggTTT",
   "TTgg^gggg¡gg..*gggggggggTTTT",
   "TTTggggggggg...ggggGGGGGgTTT",
   "TTTg.....ggg...ggggGGGGGgTTT",
   "TTTg.....gggg..g⁂ggGGGGGgTTT",
   "TTTTg....gggg..g*gggggggg^TT",
   "TTTggggggRggg..ggg...ggTgTTT",
   "TTTTggggggggg..ggggggggg*TTT",
   "TTTggGGGggggg..gggggggggTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "12,5": "route7:7,1",
   "7,7": "route7:4,4",
   "20,7": "route7:11,10",
   "9,19": "route7:2,13"
  },
  "marks": {
   "19,12": "lm_first_plants"
  },
  "finds": {
   "23,18": {
    "id": "vol_r7_ash",
    "item": "berries",
    "n": 3
   },
   "4,2": {
    "id": "vol_r7_top",
    "item": "coins",
    "n": 230
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "seg_v1",
    "off": 0
   },
   "s": {
    "map": "town7",
    "off": 0
   }
  },
  "gen": 18
 },
 "seg_v1": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TT^ggggggggggg..ggggggggggTT",
   "TTTggggggggggg..RgggggggggTT",
   "TTTgGGGGGgg*gg..ggggggRggTTT",
   "TTTgGGGG¡ggg*g..gg...ggTgTTT",
   "TTTgTGGGGggggg.........gTTTT",
   "TTTggggggggggg.........ggTTT",
   "TTTgTggggggggg..g.....ggggTT",
   "TTTT^ggggRgggg..g..Ω..ggggTT",
   "TTT^gggggggggg..ggggggggggTT",
   "TTT^gggggggggg..ggggggggggTT",
   "TTTTgGGGgggggg..g⁂ggggg^ggTT",
   "TTTggggggggggg..gggggggTgTTT",
   "TTTggggggggg....gggggg^ggTTT",
   "TTTggRgggggg....ggggRggggTTT",
   "TTTggg*ggggg..ggggggggggggTT",
   "TTTT....gggg..gggggGGGGGgg^T",
   "TTTg.....ggg..gggggGGGGGggTT",
   "TTTgg....ggg..gggggGGGGGggTT",
   "TTTggggggTgg..ggggggggggg^TT",
   "TT^gggggggTg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "16,3": "seg_v1:6,1",
   "22,4": "seg_v1:9,1",
   "5,15": "seg_v1:1,5",
   "20,15": "seg_v1:13,5",
   "9,9": "seg_v1:6,7"
  },
  "marks": {
   "19,9": "lm_gopher_mounds"
  },
  "finds": {
   "23,9": {
    "id": "vol_v1_mounds",
    "item": "treats",
    "n": 2
   },
   "4,21": {
    "id": "vol_v1_south",
    "item": "wakeberry",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "route7",
    "off": 0
   },
   "n": {
    "map": "seg_v2",
    "off": 0
   }
  },
  "gen": 18
 },
 "seg_v2": {
  "rows": [
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..*gRggggggggTTTT",
   "TTggggggg⁂g..ggg^gggggggTTTT",
   "TTTgGGGGGgg..ggg^ggg^ggg^TTT",
   "TTggGGGGGgg..ggg^.....ggTTTT",
   "TTTgGGGGGgg..ggg.......ggTTT",
   "TTTgggggggg..gg*.......ggTTT",
   "TTTgggggRgg..ggg....Ω..ggTTT",
   "TTTgggggggg..gggg.....^^ggTT",
   "TTTgTgggggg..ggggRggg^ggggTT",
   "TTTgggGGGgg..gggggggggggTgTT",
   "TTTgggggggg.....ggggggggTgTT",
   "TTTgTgggggg.....ggg*gggggTTT",
   "TTTg....gggggg..gggggggggTTT",
   "TTTg.....ggggg..ggggggggggTT",
   "TTgg.....Rgggg..ggRggggggTTT",
   "TTTg.....ggggg..gggGGGGGgTTT",
   "TT^g^....ggggg..gggGGGGGggTT",
   "TTTgT^^ggggggg..gggGGGGGggTT",
   "TTTgggTggggggg..g¡gggTgggggT",
   "TT^ggggggggggg..ggggggggTgg^",
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "8,8": "seg_v2:3,2",
   "17,10": "seg_v2:4,3",
   "15,2": "seg_v2:9,4",
   "9,16": "seg_v2:5,7",
   "18,16": "seg_v2:9,7"
  },
  "marks": {
   "20,8": "lm_obsidian"
  },
  "finds": {
   "23,5": {
    "id": "vol_v2_glass",
    "item": "antidote",
    "n": 1
   },
   "4,12": {
    "id": "vol_v2_west",
    "item": "coins",
    "n": 240
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_v1",
    "off": 0
   },
   "n": {
    "map": "seg_v3",
    "off": 0
   }
  },
  "gen": 18
 },
 "seg_v3": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..g^g^gggggggTT",
   "TTTTGGGGGgggg..ggggggggggTTT",
   "TTTTGGGGGgggg..ggggGGGGGg^TT",
   "TTTgGGGGG⁌ggg..ggRgGGGGGTTTT",
   "TTT*ggggggggg..ggggGGGGGTTTT",
   "TTT!ggggggggg..gggggggggTTTT",
   "e..............gggggggg^TTTT",
   "T..............ggggg*gg^TTTT",
   "TggggggRgTggg..gg....ggggTTT",
   "T^ggggggggggg..g⁂.WW...gTTTT",
   "TTggggggTgggg..gg.......gTTT",
   "TTTgggggggggg..gg.....T.TTTT",
   "TTTgggggggg....gg...Ω...TTTT",
   "TTggggggggg....gggg...WWTTTT",
   "TTggggggggg..gggggggg...TTTT",
   "TTggGGGGGgg..gggRggggggggTTT",
   "TTgTGGGGGgg..ggggggggggTg^TT",
   "TTggGGGGGgg..gggggggg*gggTTT",
   "T^ggg¡ggggg..gggggggggggTTTT",
   "TTTgggggggg..gggggggGGGgTTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "3,7": "seg_v3:gate",
   "7,10": "seg_v3:3,4",
   "17,5": "seg_v3:11,4",
   "16,17": "seg_v3:9,5"
  },
  "marks": {
   "20,14": "lm_hot_vent"
  },
  "finds": {
   "24,12": {
    "id": "vol_v3_vents",
    "item": "bigberries",
    "n": 1
   },
   "4,3": {
    "id": "vol_v3_corner",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_pyrelynx",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "seg_v2",
    "off": 0
   },
   "n": {
    "map": "seg_v4",
    "off": 0
   }
  },
  "gen": 18
 },
 "seg_v4": {
  "rows": [
   "TTgggggggggg..gggggggggggTTT",
   "TTgggggggggg..gggggggggggTTT",
   "TTgggggggggg..ggggggggggTTTT",
   "TTgggggggg⁂g..ggggGGGGGggTTT",
   "TTggGGGGGggg..ggRgGGGGGggTTT",
   "TTggGGGGGggg..ggggGGGGGggTTT",
   "TTggGGGGGggg..gggggggggggTTT",
   "TTgTgggggggg..ggggggggggTTTT",
   "TgggggggRggg..ggggggggggg^TT",
   "Tggggggggggg..g^^^^^Ω^^^^^TT",
   "Tggggggggggg..gggggg.ggggTTT",
   "T^gTgGGGgggg..ggggggggRgg^TT",
   "TTTggggggggg..ggggggggTggTTT",
   "TTTggggggggg..ggggggggggg^TT",
   "TTTTgggg*ggg..ggg¡gggggTTTTT",
   "TTTgg^ggRggg..gggggggggggTTT",
   "TTgT....gggg...gggg....g^TTT",
   "TTgg.....ggg...ggg.....ggTTT",
   "TTgT.....gggg..ggg.....g^TTT",
   "TTTgggggggTgg..gggRgggg*^TTT",
   "TTTggggggTggg..gggggggggTTTT",
   "TTT^ggggggggg..gggggGGGgg^TT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "16,4": "seg_v4:6,2",
   "8,8": "seg_v4:1,4",
   "22,11": "seg_v4:6,4",
   "8,15": "seg_v4:14,4",
   "18,19": "seg_v4:6,6"
  },
  "marks": {
   "20,9": "lm_lava_tube"
  },
  "finds": {
   "24,11": {
    "id": "vol_v4_tube",
    "item": "revives",
    "n": 1
   },
   "4,21": {
    "id": "vol_v4_south",
    "item": "coins",
    "n": 250
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_v3",
    "off": 0
   },
   "n": {
    "map": "seg_v5",
    "off": 0
   }
  },
  "gen": 18
 },
 "seg_v5": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TT^gggggggggg..ggg^ggggggTTT",
   "TTTgGGGGG⁌ggg..ggggg*ggggTTT",
   "TTTgGGGGGggg*..ggggGGGTGTTTT",
   "TTTgGGGGGgggg..ggRgGGGGGgTTT",
   "TTTTggggggggg..ggggGGGGTgTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTggg....gggg..ggggggggggTTT",
   "TTgT*.WW.gggg..ggggggggggTTT",
   "TTggg....gggg..ggggggggTgTTT",
   "T^ggggggggggg..ggg.....gTgTT",
   "T^gggggggRggg..ggg..Ω..gggTT",
   "TTgT^g^gggggg..ggg.....ggg^T",
   "TTgggggggggg...ggggggggggTTT",
   "TTgggggggggg...ggRggggTggTTT",
   "TTgggggggggg..ggggggggTggTTT",
   "TgggGGGGGggg..gggggggggggTTT",
   "TTggGGGGGggg..gggggggggggTTT",
   "T^gTGGGGGggg..gg⁂ggggggggTTT",
   "TTgggggggggg..ggggggGGGggTTT",
   "TTTgg¡gggggg..ggggggggggTTTT",
   "TTgggggggggg..gggggggggggTTT",
   "TTgggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "9,12": "seg_v5:5,8",
   "17,15": "seg_v5:6,8",
   "17,5": "seg_v5:11,8"
  },
  "marks": {
   "20,12": "lm_maleo"
  },
  "finds": {
   "23,11": {
    "id": "vol_v5_warm",
    "item": "berries",
    "n": 3
   },
   "4,3": {
    "id": "vol_v5_corner",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "seg_v4",
    "off": 0
   },
   "n": {
    "map": "town8",
    "off": 0
   }
  },
  "gen": 18
 },
 "town8": {
  "rows": [
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTTgggggggggg..!gggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgHggggCggg..gggYggggHgTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTT*ggg¦............¦ggggTTT",
   "TTTTggg..............gggTTTT",
   "TTTggΩg...WW...Ω.Ω...g¦g!ΩgT",
   "TTTgggg....................T",
   "TTTgggg.Ω..................e",
   "TT^gHgg..R.................T",
   "TTTgggg¦........Ω...¦g¦g¦ΩgT",
   "TTTgggggggggg..ggVgggggHTTTT",
   "TTggggggggggg..gggggggggTTTT",
   "TTTg.....................TTT",
   "TT^Ω.....................TTT",
   "TTTg!Ωggggg¦g..g¦ggggΩgggTTT",
   "TTTgΩgg*ggggg..ggggMgggggTTT",
   "TTTgggΩgggHgg..!*ggggggggTTT",
   "TTTgggΩΩgggg!..ggggggggHTTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "15,3": "town8:gate",
   "24,9": "town8:gate2",
   "15,20": "town8:next",
   "12,21": "town8:9,3",
   "4,18": "town8:8,12",
   "9,12": "town8:3,8",
   "17,14": "town8:9,10"
  },
  "marks": {
   "6,20": "lm_volcanic_soil",
   "3,17": "decor:garden",
   "5,18": "decor:garden",
   "4,19": "decor:garden",
   "6,21": "decor:garden",
   "7,21": "decor:garden",
   "16,13": "decor:forge",
   "17,9": "decor:stall",
   "15,9": "decor:stall",
   "8,11": "decor:bench",
   "21,18": "decor:crates",
   "5,9": "decor:woodpile",
   "25,9": "decor:seabanner",
   "25,13": "decor:seabanner"
  },
  "finds": {
   "24,19": {
    "id": "vol_t8_gardens",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {
   "27,11": {
    "map": "shore",
    "x": 1,
    "y": 11
   }
  },
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_v5",
    "off": 0
   },
   "n": {
    "map": "route8",
    "off": 0,
    "fallback": {
     "tile": "13,0",
     "ch": "n",
     "map": "route8",
     "x": 7,
     "y": 14
    }
   }
  },
  "gen": 18
 }
}, inbound: [
 {
  "from": "shrine_pyrelynx",
  "tile": "7,9",
  "map": "seg_v3",
  "x": 1,
  "y": 8
 },
 {
  "from": "route8",
  "tile": "7,15",
  "map": "town8",
  "x": 13,
  "y": 1
 }
] });
