// ---------- Part 69: THE APPROVED SIXTY-SIX ----------
// Generated by design/tools/build_part69.js from the reviewed field-guide source.
// Change that source or its small game-metadata table, then run the builder.
//
// This part loads late, after the game's maps and field-guide structures exist,
// but before part63 snapshots the Breeding Centre and Vigil achievement groups.

const P69_SPECIES = [
  {
    "k": "adeliepenguin",
    "n": "Adélie Penguin",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 42,
      "a": 48,
      "d": 40,
      "s": 54
    },
    "c": 0.38,
    "group": "polar",
    "d": "fish and krill",
    "h": "Antarctic coasts and the shifting pack ice",
    "taxon": "Pygoscelis adeliae · one of 3 living species currently placed in Pygoscelis",
    "f": "Adélies are the brisk, quarrelsome pebble-builders of the Antarctic coast. A pair raises its nest just high enough to keep meltwater from soaking the egg, and a particularly fine stone may be courted, guarded, or stolen from next door. Once breeding is over, these penguins follow the pack ice rather than remaining at the colony. They hunt fish and krill from the water, then may save energy on land by lying on their bellies and pushing themselves over the snow. Their formal black-and-white dress is real; so is the muddy, noisy neighborhood hidden behind it."
  },
  {
    "k": "antarcticicefish",
    "n": "Antarctic Icefish",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 38,
      "a": 44,
      "d": 34,
      "s": 42
    },
    "c": 0.42,
    "group": "polar",
    "d": "fish and krill",
    "h": "cold water over the Antarctic continental shelf",
    "taxon": "Pagetodes antarcticus · also called the Long-fingered Icefish, one of 3 living Pagetodes species",
    "f": "Like every white-blooded icefish, this species carries one of the Floe’s strangest adaptations: its adult blood contains no haemoglobin, so oxygen travels dissolved in plasma rather than bound to red pigment. Cold, oxygen-rich water makes that possible, helped by the enlarged circulation shared across the family. It lives roughly 90 to 600 metres deep around the Antarctic continental shelf, feeding on fish and krill; its larvae spend a long late-winter phase in open water. Older guides call it Cryodraco antarcticus, while current fish lists place it in Pagetodes."
  },
  {
    "k": "antarcticseaspider",
    "n": "Antarctic Sea Spider",
    "t": [
      "Aquatic",
      "Armor"
    ],
    "b": {
      "h": 34,
      "a": 46,
      "d": 40,
      "s": 30
    },
    "c": 0.42,
    "group": "polar",
    "d": "soft-bodied seafloor animals",
    "h": "the cold Antarctic seafloor",
    "taxon": "Colossendeis megalonyx · one of 74 accepted species currently listed in Colossendeis by WoRMS, but probably a complex of several lineages",
    "f": "An Antarctic sea spider is neither a true spider nor built like most animals you know. Its body is so slight that much of its gut extends into its long legs, and oxygen passes across the outer surface instead of through gills or lungs. Colossendeis megalonyx prowls the seafloor and can seize surprisingly mobile prey, including the swimming sea angel Clione antarctica. Yet the familiar name may hide more than one species: genetic work has uncovered several distinct, sometimes hybridising lineages beneath the single label. On the Floe, meeting one is also meeting a taxonomic mystery still in motion."
  },
  {
    "k": "antarctictoothfish",
    "n": "Antarctic Toothfish",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 72,
      "a": 68,
      "d": 58,
      "s": 48
    },
    "c": 0.22,
    "group": "polar",
    "d": "fish and squid",
    "h": "cold, deep water around Antarctica",
    "taxon": "Dissostichus mawsoni · one of 2 living species currently placed in Dissostichus",
    "f": "The Antarctic toothfish is a patient giant of cold, deep water. Antifreeze glycoproteins keep ice crystals from growing in its body fluids, while stored lipids and lightly mineralised bones help it hover without the gas-filled swim bladder used by many fishes. That near-neutral buoyancy lets a heavy predator move through the water column for fish and squid with little wasted effort. It grows slowly, matures late, and produces relatively few young, so a lost adult is not quickly replaced. Beneath the plain, dark silhouette is a carefully balanced solution to life below freezing."
  },
  {
    "k": "arcticchar",
    "n": "Arctic Char",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 48,
      "a": 52,
      "d": 42,
      "s": 58
    },
    "c": 0.34,
    "group": "polar",
    "d": "insects, crustaceans, and fish",
    "h": "Arctic lakes, rivers, and coastal seas",
    "taxon": "Salvelinus alpinus · one of 51 species currently listed in Salvelinus by FishBase; species boundaries within the char complex remain difficult",
    "f": "Arctic char refuse to live only one kind of life. Some remain in a lake from hatching to old age; others travel to the sea each summer, feed hard for a few short weeks, then return to fresh water before winter. Sea-run char must make that return because the coldest marine water can become lethal, while lakes and rivers offer a safer refuge beneath the ice. Isolated waters can also produce strikingly different sizes, colours, diets, and breeding forms. Scientists still debate where variation ends and separate char species begin, making Salvelinus alpinus both a survivor and a living lesson in evolution."
  },
  {
    "k": "arcticcod",
    "n": "Arctic Cod",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 36,
      "a": 42,
      "d": 34,
      "s": 58
    },
    "c": 0.44,
    "group": "polar",
    "d": "zooplankton and small fish",
    "h": "Arctic seas, especially beneath sea ice",
    "taxon": "Boreogadus saida · the only living species currently placed in Boreogadus",
    "f": "Arctic cod are small enough to disappear beneath the ice, yet much of the Arctic food web depends on them. Seabirds, seals, whales, and larger fishes all turn their stored energy into lives of their own. The cod can remain active in seawater below the usual freezing point of fish blood because antifreeze glycoproteins block dangerous ice growth. Remarkably, that molecular trick evolved independently from the similar protection found in Antarctic fishes. Young cod often shelter and feed around sea ice, making this unassuming silver fish a moving bridge between plankton below and predators above."
  },
  {
    "k": "arctictern",
    "n": "Arctic Tern",
    "t": [
      "Aerial",
      "Swift"
    ],
    "b": {
      "h": 34,
      "a": 38,
      "d": 30,
      "s": 82
    },
    "c": 0.34,
    "group": "polar",
    "d": "small fish and marine invertebrates",
    "h": "polar coasts and oceans at both ends of its migration",
    "taxon": "Sterna paradisaea · one of 13 living species currently placed in Sterna by AviList",
    "f": "Arctic terns stitch the planet’s polar summers together. Tiny tracking devices have recorded individuals covering more than 80,000 kilometres in a year, leaving northern breeding grounds for productive waters near Antarctic pack ice and returning by a different, wind-assisted route. They do not simply fly straight south: broad loops help them find food and favourable air currents over several oceans. At the nest, the same elegant bird becomes a fierce defender, diving at intruders with its sharp bill. Its journey is not one heroic dash but thousands of precise choices about wind, water, and season."
  },
  {
    "k": "arcticwolf",
    "n": "Arctic Wolf",
    "t": [
      "Ice",
      "Predator"
    ],
    "b": {
      "h": 64,
      "a": 70,
      "d": 54,
      "s": 60
    },
    "c": 0.24,
    "group": "polar",
    "d": "muskoxen, caribou, hares, and other prey",
    "h": "the open tundra of the High Arctic",
    "taxon": "Canis lupus arctos · a widely used subspecific name within the gray wolf; Canis currently contains 8 living species in the Mammal Diversity Database",
    "f": "The Arctic wolf is a gray wolf shaped by open tundra, long darkness, and prey scattered over enormous distances. On Ellesmere Island, one GPS-collared male and its pack ranged across roughly 6,640 square kilometres, hunting muskoxen, Peary caribou, and Arctic hares. Pale fur helps against a snowy background, but cooperation matters more than colour: a pack can search widely, test large prey, and share an unpredictable landscape. The name arctos is commonly used for the high-Arctic form, although subspecies boundaries in gray wolves depend on the authority and remain less settled than the species itself."
  },
  {
    "k": "capelin",
    "n": "Capelin",
    "t": [
      "Aquatic",
      "Swift"
    ],
    "b": {
      "h": 30,
      "a": 32,
      "d": 28,
      "s": 66
    },
    "c": 0.5,
    "group": "polar",
    "d": "plankton and tiny crustaceans",
    "h": "cold North Atlantic and Arctic seas",
    "taxon": "Mallotus villosus · Atlantic Capelin, one of 2 accepted named Mallotus species; a third Atlantic lineage remains unnamed",
    "f": "Capelin turn an ordinary beach into a silver tide. In summer, some populations surge into shallow water and roll onto sand or fine gravel to spawn, often at night and near high tide. The eggs stick to the substrate instead of drifting away, while many exhausted adults, especially males, die after the event. Offshore, this little smelt is a keystone forage fish: cod, seabirds, seals, and whales all follow its abundance. A capelin run therefore feeds two worlds at once, planting the next generation in the shore and carrying ocean energy into a crowd of waiting hunters."
  },
  {
    "k": "collaredlemming",
    "n": "Collared Lemming",
    "t": [
      "Ice",
      "Burrow"
    ],
    "b": {
      "h": 28,
      "a": 30,
      "d": 32,
      "s": 52
    },
    "c": 0.52,
    "group": "polar",
    "d": "tundra grasses, sedges, and willow",
    "h": "Arctic tundra, including winter tunnels beneath snow",
    "taxon": "Dicrostonyx groenlandicus · one of 7 living species currently recognised in Dicrostonyx by the Mammal Diversity Database; some population boundaries remain unresolved",
    "f": "The collared lemming performs a winter transformation no other rodent genus completes in quite the same way. Shortening days trigger brown summer fur to become white, while the front claws broaden into paired, shovel-like tips for digging through hard snow. Beneath that cover it searches for stems and buds, hidden from wind and many predators. Not every island population changes equally, a clue that local winters have shaped the response. Even its map is unfinished: the current species treatment tentatively absorbs at least one named form that still lacks decisive molecular study."
  },
  {
    "k": "gentoopenguin",
    "n": "Gentoo Penguin",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 46,
      "a": 50,
      "d": 42,
      "s": 68
    },
    "c": 0.34,
    "group": "polar",
    "d": "krill, fish, and squid",
    "h": "subantarctic islands and the Antarctic Peninsula",
    "taxon": "Pygoscelis papua · treated by AviList v2025b as one of 3 living Pygoscelis species, while recent studies propose splitting gentoo lineages into 4 species",
    "f": "Gentoos approach Antarctic family life with unusual flexibility. A pair builds a low nest from pebbles, grass, or whatever the colony offers, then guards the small territory around it with great seriousness. Two eggs are usual, and older chicks gather into crèches while both parents forage. Breeding dates and diets vary markedly from one island group to another, matching local seasons rather than one rigid calendar. Those differences run deeper than behaviour: genetic and anatomical studies, including a 2026 revision, argue that “gentoo” contains four species. The latest released global checklist has not yet adopted that split."
  },
  {
    "k": "greenlandhalibut",
    "n": "Greenland Halibut",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 58,
      "a": 62,
      "d": 52,
      "s": 42
    },
    "c": 0.28,
    "group": "polar",
    "d": "fish, squid, and crustaceans",
    "h": "cold, deep North Atlantic and Arctic water",
    "taxon": "Reinhardtius hippoglossoides · the only living species currently placed in Reinhardtius",
    "f": "Greenland halibut begin life upright and symmetrical. As a larva settles, one eye travels toward the upper side, the skull twists, and the young fish becomes a dark, diamond-shaped flatfish. Its migrating eye does not move quite as far as in many relatives, leaving unusually broad vision around the body. Nor is this halibut glued to the seabed: tagged fish make daily vertical journeys and may spend about a quarter of their time in the water column. In cold northern depths, it is both bottom-dweller and roaming hunter, built to watch more than one direction."
  },
  {
    "k": "ivorygull",
    "n": "Ivory Gull",
    "t": [
      "Ice",
      "Aerial"
    ],
    "b": {
      "h": 36,
      "a": 40,
      "d": 34,
      "s": 66
    },
    "c": 0.4,
    "group": "polar",
    "d": "fish, marine invertebrates, and carrion",
    "h": "High-Arctic sea ice and remote breeding cliffs",
    "taxon": "Pagophila eburnea · the only living species currently placed in Pagophila",
    "f": "An adult ivory gull is almost entirely white, a bright bird against blue ice and dark leads. It remains tied to the Arctic ice through every season, feeding along cracks and polynyas where fish and invertebrates approach the surface. It is also an expert scavenger, arriving at seal remains left by polar bears or hunters and turning scraps into flight. Satellite-tagged Canadian birds spent about 90 percent of winter over sea ice, including long periods above dense pack. That dependence makes the gull a beautiful specialist, but also leaves it with few substitutes when ice conditions change."
  },
  {
    "k": "kingpenguin",
    "n": "King Penguin",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 56,
      "a": 52,
      "d": 48,
      "s": 52
    },
    "c": 0.3,
    "group": "polar",
    "d": "fish and squid",
    "h": "subantarctic islands and surrounding ocean",
    "taxon": "Aptenodytes patagonicus · one of 2 living species currently placed in Aptenodytes",
    "f": "King penguins raise a chick on a calendar longer than an Antarctic year. Courtship, a single egg, incubation, winter fasting, and chick growth can occupy 13 to 16 months, so successful parents often cannot repeat the feat the next season. There is no nest: the adult balances the egg on its feet beneath a warm fold of skin, trading duty with its partner. Chicks later stand together in dense groups while adults travel for lanternfish and squid. A king colony looks crowded and chaotic, but every returning bird must find one partner or chick by voice."
  },
  {
    "k": "littleauk",
    "n": "Little Auk",
    "t": [
      "Aquatic",
      "Aerial"
    ],
    "b": {
      "h": 30,
      "a": 34,
      "d": 28,
      "s": 68
    },
    "c": 0.46,
    "group": "polar",
    "d": "zooplankton and tiny fish",
    "h": "Arctic seas and crowded coastal colonies",
    "taxon": "Alle alle · the only living species currently placed in Alle",
    "f": "The little auk is a pocket-sized seabird with an ecosystem-sized effect. It gathers fat-rich copepods from cold Arctic water in a throat pouch, then carries them to a single chick hidden among scree and rock crevices. Millions breed in noisy colonies, and their guano moves marine nutrients uphill into tundra plants, insects, and streams. At one Svalbard colony of 50,000 pairs, researchers estimated roughly 100 tonnes of droppings reached the surrounding land in a breeding season. A warmer ocean can replace large Arctic copepods with smaller prey, forcing this tiny courier to work harder for every meal."
  },
  {
    "k": "longtailedduck",
    "n": "Long-tailed Duck",
    "t": [
      "Aquatic",
      "Aerial"
    ],
    "b": {
      "h": 36,
      "a": 40,
      "d": 34,
      "s": 66
    },
    "c": 0.42,
    "group": "polar",
    "d": "molluscs, crustaceans, and aquatic insects",
    "h": "Arctic breeding waters and cold northern coasts",
    "taxon": "Clangula hyemalis · the only living species currently placed in Clangula",
    "f": "The long-tailed duck seems determined never to wear the same outfit for long. Males reverse much of their dark-and-light pattern between summer and winter, with overlapping moults creating more seasonal plumages than most ducks. The narrow central tail feathers remain a flourish, but the real performance happens underwater. These sea ducks propel themselves with their wings and have been recorded foraging near 60 metres deep; during a feeding bout they can spend three or four times as long submerged as at the surface. They breed beside tundra pools, then gather on coasts where their yodelling calls travel over winter water."
  },
  {
    "k": "ringedseal",
    "n": "Ringed Seal",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 58,
      "a": 50,
      "d": 54,
      "s": 48
    },
    "c": 0.3,
    "group": "polar",
    "d": "fish and crustaceans",
    "h": "Arctic sea ice, where it keeps breathing holes open",
    "taxon": "Pusa hispida · one of 4 living species currently recognised in Pusa by the Mammal Diversity Database",
    "f": "Ringed seals manufacture openings in a world trying to freeze shut. Thick foreflipper claws scrape and maintain breathing holes through ice that can exceed 1.8 metres, and drifting snow above a hole becomes material for a hidden lair. A mother gives birth and nurses inside that snow cave, where the pup gains shelter from cold and from watchful predators. Polar bears, however, learn to search the same ice for those chambers, making each lair both nursery and risk. Recent taxonomy raised the isolated Saimaa seal from a ringed-seal subspecies to a separate species, bringing the current Pusa count to four."
  },
  {
    "k": "rockptarmigan",
    "n": "Rock Ptarmigan",
    "t": [
      "Ice",
      "Aerial"
    ],
    "b": {
      "h": 42,
      "a": 44,
      "d": 42,
      "s": 54
    },
    "c": 0.42,
    "group": "polar",
    "d": "buds, leaves, berries, and seeds",
    "h": "rocky Arctic tundra and high mountains",
    "taxon": "Lagopus muta · one of 3 living species currently placed in Lagopus",
    "f": "Rock ptarmigan change with the ground beneath them. Mottled brown feathers blend into summer tundra, while a mostly white winter coat erases the bird against snow; males retain a crisp black eye-stripe that can betray them at close range. Their legs and toes are densely feathered for warmth and support, and long claws can excavate a snow burrow within seconds. Inside, the air is calmer and warmer than the exposed ridge, allowing a bird to wait out wind for hours or even days. What looks like disappearance is an active routine of moulting, digging, and choosing shelter."
  },
  {
    "k": "rossgull",
    "n": "Ross's Gull",
    "t": [
      "Ice",
      "Aerial"
    ],
    "b": {
      "h": 32,
      "a": 36,
      "d": 30,
      "s": 70
    },
    "c": 0.4,
    "group": "polar",
    "d": "small fish and marine invertebrates",
    "h": "High-Arctic seas and little-known tundra breeding grounds",
    "taxon": "Rhodostethia rosea · the only living species currently placed in Rhodostethia",
    "f": "Ross’s gull seems to migrate the wrong way at first: after nesting on tundra wetlands, many birds head north into broken sea ice in the central Arctic Ocean. A small satellite study followed two Siberian breeders; one travelled at least 8,254 kilometres, lingering between 80 and 85 degrees north before crossing toward Alaska and Chukotka. Canadian birds may instead winter in the Northwest Atlantic, so there is no single route for the whole species. In breeding dress, a soft pink wash and fine black collar give this slight gull an almost delicate look, concealing a life spent over remote, restless water."
  },
  {
    "k": "snowpetrel",
    "n": "Snow Petrel",
    "t": [
      "Ice",
      "Aerial"
    ],
    "b": {
      "h": 32,
      "a": 36,
      "d": 30,
      "s": 72
    },
    "c": 0.4,
    "group": "polar",
    "d": "krill, fish, squid, and carrion",
    "h": "Antarctic pack ice and ice-free nesting rock",
    "taxon": "Pagodroma nivea · the sole living species currently placed in Pagodroma; 2 size-based subspecies are widely recognised",
    "f": "Snow petrels carry Antarctic whiteness into the air: white wings and body, black eyes and bill, all skimming above pack ice. They lay one egg in a protected rock crevice, sometimes far beyond any ordinary idea of a seabird colony. In the Prince Charles Mountains, nests occur as far as about 440 kilometres inland, requiring immense commutes to marine feeding grounds. Two size forms, usually treated as subspecies, overlap and can form mixed pairs, so their exact taxonomic meaning remains debated. Even fossilised nest deposits preserve a long record of where ice-free rock and reachable ocean once met."
  },
  {
    "k": "southpolarskua",
    "n": "South Polar Skua",
    "t": [
      "Aerial",
      "Predator"
    ],
    "b": {
      "h": 46,
      "a": 56,
      "d": 42,
      "s": 68
    },
    "c": 0.34,
    "group": "polar",
    "d": "fish, eggs, chicks, and carrion",
    "h": "Antarctic coasts and the Southern Ocean",
    "taxon": "Stercorarius maccormicki · one of 7 living species currently placed in Stercorarius by AviList",
    "f": "South polar skuas are adaptable hunters with two very different Antarctic lives. Near penguin colonies, some pairs take eggs and unattended chicks; elsewhere, birds depend chiefly on fish and krill brought from the sea. They nest in a shallow scrape on exposed ground and defend it with fearless, low attacks. When the brief breeding season ends, the map opens dramatically. Tracking and sightings show individuals ranging into the North Atlantic and North Pacific, crossing much of the planet before returning south. The older genus name Catharacta still appears in some Antarctic sources, but current AviList places all seven skuas and jaegers in Stercorarius."
  },
  {
    "k": "alpinechamois",
    "n": "Alpine Chamois",
    "t": [
      "Armor",
      "Swift"
    ],
    "b": {
      "h": 54,
      "a": 52,
      "d": 50,
      "s": 72
    },
    "c": 0.34,
    "group": "alpine",
    "d": "grasses, herbs, buds, and shoots",
    "h": "steep European mountain slopes and alpine meadows",
    "taxon": "Rupicapra rupicapra · one of 2 living Rupicapra species",
    "f": "One of two living Rupicapra chamois, it crosses broken Alpine ground on hooves whose hard rims bite into rock while softer centres grip uneven surfaces. Winter is met partly by turning the body down: field studies recorded lower heart rate, body temperature and activity as food became scarce. Not every chamois follows the same seasonal route, either. Some descend or shelter in forest while others remain high, making this less a simple tale of an animal that always climbs than one that balances snow, forage, disturbance and the energy left in its body."
  },
  {
    "k": "alpinechough",
    "n": "Alpine Chough",
    "t": [
      "Aerial",
      "Swift"
    ],
    "b": {
      "h": 34,
      "a": 38,
      "d": 32,
      "s": 68
    },
    "c": 0.42,
    "group": "alpine",
    "d": "invertebrates, berries, and scraps",
    "h": "high European and Asian mountains",
    "taxon": "Pyrrhocorax graculus · one of 2 living Pyrrhocorax choughs",
    "f": "One of two living Pyrrhocorax choughs, it keeps to high mountains with red legs, a curved yellow bill and a talent for finding food in company. Flocks feed together through winter rather than abandoning the heights altogether. Ski stations and mountain restaurants have added a new kind of patch to that map: recent tracking shows that predictable human food can reshape where these birds spend their day. The chough circling a summit café is therefore not merely a comic thief. It is a social alpine forager rapidly learning how a human season has rearranged its mountain."
  },
  {
    "k": "alpinesalamander",
    "n": "Alpine Salamander",
    "t": [
      "Ice",
      "Venom"
    ],
    "b": {
      "h": 36,
      "a": 38,
      "d": 40,
      "s": 28
    },
    "c": 0.46,
    "group": "alpine",
    "d": "small invertebrates",
    "h": "cool, damp ground in the European Alps",
    "taxon": "Salamandra atra · one of 6 living Salamandra species",
    "f": "One of six living Salamandra salamanders, this glossy black mountaineer can complete reproduction without a pond. Instead of laying eggs into water, a female carries developing young through a prolonged pregnancy and usually gives birth on land to two fully formed salamanders. Embryos first consume their own yolk and then receive further nourishment within the mother's oviduct. That slow, costly route bypasses the free-swimming larval stage that defines many amphibian lives, turning a damp crevice in an Alpine slope into habitat for an animal whose young arrive ready for land."
  },
  {
    "k": "apollobutterfly",
    "n": "Apollo Butterfly",
    "t": [
      "Bug",
      "Aerial"
    ],
    "b": {
      "h": 26,
      "a": 32,
      "d": 24,
      "s": 62
    },
    "c": 0.5,
    "group": "alpine",
    "d": "flower nectar; the caterpillar eats stonecrop",
    "h": "sunny mountain meadows and rocky slopes",
    "taxon": "Parnassius apollo · one of about 50 Parnassius species; exact limits remain disputed",
    "f": "One of about fifty Parnassius butterflies, the Apollo carries red eyespots across pale wings whose sparse scales can make their edges seem translucent. Its caterpillars depend chiefly on stonecrops growing in warm, open and rocky places. That makes an old grazing landscape unexpectedly important: when pastures are abandoned, shrubs and trees can close the sunny gaps on which the larvae rely. More than two hundred Apollo subspecies have been proposed, many on uncertain boundaries, so both its name-map and its habitat-map are works in progress. Protecting it often means preserving openness rather than leaving a slope entirely untouched."
  },
  {
    "k": "argali",
    "n": "Argali",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 68,
      "a": 64,
      "d": 62,
      "s": 48
    },
    "c": 0.26,
    "group": "alpine",
    "d": "grasses and other mountain plants",
    "h": "open mountains and plateaus across Central Asia",
    "taxon": "Ovis ammon · one of 7 living Ovis sheep in the Mammal Diversity Database",
    "f": "One of seven living Ovis sheep in the current Mammal Diversity Database, the argali is the largest wild sheep. Mature rams carry immense corkscrewing horns and meet rivals in head-on clashes whose sound carries across open mountain country. Those horns are spectacular but expensive: growing and carrying them demands resources in a landscape where forage is seasonal and thin. Argali range across separated highlands in Central Asia, and the named regional forms do not all have equally settled boundaries. The familiar silhouette therefore covers a wide and varied species, not one uniform mountain population."
  },
  {
    "k": "barheadedgoose",
    "n": "Bar-headed Goose",
    "t": [
      "Aerial",
      "Ice"
    ],
    "b": {
      "h": 46,
      "a": 48,
      "d": 42,
      "s": 70
    },
    "c": 0.34,
    "group": "alpine",
    "d": "grasses, grains, and wetland plants",
    "h": "Central Asian lakes and high Himalayan migration routes",
    "taxon": "Anser indicus · one of 11 living Anser geese in AviList",
    "f": "One of eleven living Anser geese in AviList, it migrates across the Himalaya where cold air carries only a fraction of the oxygen available at sea level. Its solution is not one miraculous organ: high-affinity haemoglobin and changes through the lungs, circulation and flight muscles help the whole oxygen pathway work at altitude. Tracking also corrected the heroic picture of a single flat flight above every summit. Birds often follow a roller-coaster route, losing height after crossings and climbing steeply when the terrain demands it. The journey remains extraordinary precisely because it is an exercise in careful energy use, not effortless flight."
  },
  {
    "k": "himalayanjumpingspider",
    "n": "Himalayan Jumping Spider",
    "t": [
      "Bug",
      "Ice"
    ],
    "b": {
      "h": 22,
      "a": 38,
      "d": 24,
      "s": 66
    },
    "c": 0.52,
    "group": "alpine",
    "d": "springtails and other tiny arthropods",
    "h": "rock and snow margins high in the Himalaya",
    "taxon": "Euophrys omnisuperstes · one of 100 accepted Euophrys species in the World Spider Catalog",
    "f": "One of one hundred accepted Euophrys jumping spiders, this tiny hunter was confirmed from adults collected near 5,900 metres on Everest. Immature spiders probably belonging to the same species were found still higher, at about 6,700 metres, but could not be identified with equal certainty. It does not spin a web to catch prey. Instead it stalks and pounces on minute springtails and flies carried uphill by the wind. Its name means roughly “standing above all”: an apt label for a predator supported by an aerial trickle of life far above the last plants."
  },
  {
    "k": "kiang",
    "n": "Kiang",
    "t": [
      "Swift",
      "Wild"
    ],
    "b": {
      "h": 64,
      "a": 58,
      "d": 52,
      "s": 72
    },
    "c": 0.3,
    "group": "alpine",
    "d": "grasses and sedges",
    "h": "the high, cold Tibetan Plateau",
    "taxon": "Equus kiang · one of 9 living Equus species in the Mammal Diversity Database, including 2 domestic forms",
    "f": "One of nine living Equus species in the current Mammal Diversity Database, the kiang is the largest wild ass. It lives on the Tibetan Plateau in loose, shifting groups, travelling between grassland, steppe and water as local conditions change. Those movements are real but do not fit one universal long-distance migration: studies and regional accounts describe flexible seasonal responses rather than a single route followed by every population. Its chestnut summer coat grows dark and woolly for winter, while a white belly and muzzle remain sharply marked against the high, open ground."
  },
  {
    "k": "lammergeier",
    "n": "Lammergeier",
    "t": [
      "Aerial",
      "Armor"
    ],
    "b": {
      "h": 60,
      "a": 68,
      "d": 54,
      "s": 66
    },
    "c": 0.26,
    "group": "alpine",
    "d": "bones and carrion",
    "h": "mountain cliffs across southern Europe, Africa, and Asia",
    "taxon": "Gypaetus barbatus · the only living species in Gypaetus",
    "f": "The only living species in Gypaetus is a vulture built around what other scavengers leave behind. It swallows smaller bones and carries larger ones into the air, dropping them on favoured rocky “ossuaries” until useful pieces break free. Bone is not empty packaging: marrow and fat make it a concentrated food that can remain available after softer flesh has gone. Adults also seek iron-rich mud and water that stain their naturally pale feathers rusty orange. The colour is applied, not grown, so the famous mountain beard and ochre breast are partly the bird's own work."
  },
  {
    "k": "mountaingoat",
    "n": "Mountain Goat",
    "t": [
      "Armor",
      "Ice"
    ],
    "b": {
      "h": 62,
      "a": 58,
      "d": 66,
      "s": 54
    },
    "c": 0.3,
    "group": "alpine",
    "d": "grasses, sedges, shrubs, and lichens",
    "h": "cliffs and alpine slopes of northwestern North America",
    "taxon": "Oreamnos americanus · the only living species in Oreamnos",
    "f": "The only living species in Oreamnos is called a goat but belongs to the goat-antelope branch rather than the genus of true goats. Its two hoof toes can spread and move independently; hard outer edges catch tiny ledges while softer pads mould against stone. Powerful shoulders then haul the body upward, making steep cliffs both feeding ground and refuge from predators. Kids enter that vertical world quickly, following their mothers over terrain where a misplaced step matters. What looks like impossible balance is a combination of foot structure, strength and a lifetime of choosing footholds."
  },
  {
    "k": "rockhyrax",
    "n": "Rock Hyrax",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 38,
      "a": 36,
      "d": 46,
      "s": 48
    },
    "c": 0.44,
    "group": "alpine",
    "d": "grasses, leaves, and shoots",
    "h": "rocky outcrops and cliffs in Africa and the Middle East",
    "taxon": "Procavia capensis · the only living species in Procavia",
    "f": "The only living species in Procavia resembles a blunt, tailless rabbit, but its deeper family tree lies with elephants and sea cows in the Afrotherian branch of mammals. Broad, rubbery foot pads help it cling to rock; moisture from specialised glands increases their grip. Its temperature control is less exact than that of many similarly sized mammals, so a colony makes the landscape do part of the work, crowding into shelter at night and basking together after sunrise. The pile of warm bodies on a boulder is therefore not idleness but social thermoregulation."
  },
  {
    "k": "tibetanantelope",
    "n": "Tibetan Antelope",
    "t": [
      "Swift",
      "Ice"
    ],
    "b": {
      "h": 52,
      "a": 50,
      "d": 44,
      "s": 84
    },
    "c": 0.26,
    "group": "alpine",
    "d": "grasses, sedges, and forbs",
    "h": "high, cold steppe on the Tibetan Plateau",
    "taxon": "Pantholops hodgsonii · the only living species in Pantholops",
    "f": "The only living species in Pantholops, the Tibetan antelope or chiru carries an undercoat so fine that it is woven into shahtoosh. The fibre cannot be harvested like sheep's wool: obtaining it has meant killing and skinning the animal, which drove heavy poaching. Females also make long seasonal journeys to traditional calving grounds, sometimes moving towards land with poorer forage before returning with young. That apparent puzzle suggests that safety, tradition or other benefits matter more than the richest immediate meal. A soft shawl and a distant nursery have both shaped this high-plateau species' fate."
  },
  {
    "k": "wallcreeper",
    "n": "Wallcreeper",
    "t": [
      "Aerial",
      "Bug"
    ],
    "b": {
      "h": 28,
      "a": 34,
      "d": 28,
      "s": 68
    },
    "c": 0.46,
    "group": "alpine",
    "d": "insects and spiders picked from rock",
    "h": "sheer mountain cliffs across Eurasia",
    "taxon": "Tichodroma muraria · the only living species in Tichodroma and Tichodromidae",
    "f": "The only living species in both Tichodroma and its family moves over sheer cliffs like a bird-sized moth. Grey plumage disappears against stone until the wings open and reveal crimson panels dotted with white. It hops, flutters and probes into cracks for insects and spiders, using rock faces as another bird might use tree bark. In winter many descend to lower cliffs, quarries and old walls. The name describes the performance exactly: a wall-creeper turns bare vertical ground into a searchable surface, flashing colour only when it shifts to the next patch."
  },
  {
    "k": "whiterumpedvulture",
    "n": "White-rumped Vulture",
    "t": [
      "Aerial",
      "Wild"
    ],
    "b": {
      "h": 58,
      "a": 56,
      "d": 48,
      "s": 62
    },
    "c": 0.26,
    "group": "alpine",
    "d": "carrion",
    "h": "open country and cliffs in South Asia",
    "taxon": "Gyps bengalensis · one of 8 living Gyps vultures in AviList",
    "f": "One of eight living Gyps vultures, it shows how a medicine can pass through a food web. Veterinary diclofenac relieved pain in cattle but residues in their carcasses caused fatal kidney failure in vultures arriving to clean them up. South Asian populations fell by more than 99 percent in little more than a decade. Restrictions on the drug and conservation breeding have slowed parts of the decline, but recovery begins from a tiny remnant. A scavenger once so common that it was almost background became Critically Endangered because the last meal had been treated before the animal died."
  },
  {
    "k": "woollyflyingsquirrel",
    "n": "Woolly Flying Squirrel",
    "t": [
      "Canopy",
      "Ice"
    ],
    "b": {
      "h": 38,
      "a": 40,
      "d": 34,
      "s": 72
    },
    "c": 0.32,
    "group": "alpine",
    "d": "leaves, fruit, buds, and nuts",
    "h": "high Himalayan conifer forest and rocky cliffs",
    "taxon": "Eupetaurus cinereus · Western Woolly Flying Squirrel, one of 3 living Eupetaurus species",
    "f": "One of three living Eupetaurus woolly flying squirrels, this is the western species left after a 2021 revision separated Himalayan and Tibetan populations. It is among the largest gliding mammals, stretching a skin membrane between its limbs to cross darkness rather than using powered flight. Its high-crowned teeth suit an abrasive diet, and analysed droppings consisted overwhelmingly of pine needles—an austere food for such a large animal. Long known from very few specimens, it shows how a familiar name can hide several mountain lineages until museum material, field evidence and DNA are considered together."
  },
  {
    "k": "gemsbok",
    "n": "Gemsbok",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 66,
      "a": 64,
      "d": 62,
      "s": 58
    },
    "c": 0.28,
    "group": "savanna",
    "d": "grasses, leaves, and moisture-rich desert plants",
    "h": "dry savanna and desert across southern Africa",
    "taxon": "Oryx gazella · one of 4 living Oryx species",
    "f": "One of four living Oryx antelopes, the gemsbok can range far from surface water in the Kalahari; biologged animals were often more than twenty kilometres from a possible source. In hot seasons they move more activity into the night and choose shade during the day, conserving water through behaviour as well as physiology. Both females and males carry long, nearly straight horns, so the armed silhouette does not identify the sex. The animal's desert reputation is not a claim that it never drinks, but a capacity to keep functioning when the next drink is distant and uncertain."
  },
  {
    "k": "iberianlynx",
    "n": "Iberian Lynx",
    "t": [
      "Predator",
      "Swift"
    ],
    "b": {
      "h": 56,
      "a": 68,
      "d": 48,
      "s": 72
    },
    "c": 0.24,
    "group": "forest",
    "d": "European rabbits and other small prey",
    "h": "Mediterranean scrub and open woodland in Iberia",
    "taxon": "Lynx pardinus · one of 4 living Lynx species",
    "f": "One of four living Lynx cats, the Iberian lynx is unusually dependent on one prey: the European rabbit. When rabbit disease and habitat loss struck, only 62 mature lynx were estimated in 2001. Protected scrubland, restored prey, breeding, translocation and reintroduction helped the total population pass 2,000, and the IUCN moved the species from Endangered to Vulnerable in 2024. That is a remarkable recovery, not a finished rescue. Rabbit outbreaks, roads, disease and low genetic diversity still matter, making this a case where success means continuing the work that made success possible."
  },
  {
    "k": "woodfrog",
    "n": "Wood Frog",
    "t": [
      "Ice",
      "Aquatic"
    ],
    "b": {
      "h": 34,
      "a": 36,
      "d": 34,
      "s": 42
    },
    "c": 0.46,
    "group": "forest",
    "d": "insects and other small invertebrates",
    "h": "northern forest floors and temporary woodland pools",
    "taxon": "Lithobates sylvaticus · one of 45 living Lithobates species in ASW; also treated as Rana sylvatica",
    "f": "One of forty-five Lithobates frogs in Amphibian Species of the World, it can survive winter with much of its body water frozen outside the cells. Ice on the skin triggers the liver to release a flood of glucose, while urea accumulated before winter adds protection; both limit cellular damage as circulation and breathing stop. Northern Alaskan frogs have survived laboratory freezing to minus 16 degrees Celsius, a capacity stronger than in many southern populations. Some taxonomies return it to Rana, so the name is unsettled even though the frozen frog's return to activity after thawing is well demonstrated."
  },
  {
    "k": "mexicanredknee",
    "n": "Mexican Redknee",
    "t": [
      "Bug",
      "Venom"
    ],
    "b": {
      "h": 44,
      "a": 50,
      "d": 52,
      "s": 30
    },
    "c": 0.36,
    "group": "desert",
    "d": "insects and other small animals",
    "h": "dry scrub and burrows on Mexico's Pacific side",
    "taxon": "Brachypelma hamorii · one of 8 accepted Brachypelma species in the World Spider Catalog",
    "f": "One of eight accepted Brachypelma tarantulas, this orange-kneed burrower has often reached captivity under the wrong name. A 2017 revision showed that many spiders long called B. smithi were actually B. hamorii, while retaining a separate true B. smithi. When threatened, it can rake barbed urticating hairs from its abdomen into the air instead of relying on a bite; the hairs irritate skin and eyes and leave a temporary bald patch. International trade protection covers the genus, so a famous pet also carries a lesson in identification: conservation counts depend on knowing which animal was moved."
  },
  {
    "k": "littlebluepenguin",
    "n": "Little Blue Penguin",
    "t": [
      "Aquatic",
      "Swift"
    ],
    "b": {
      "h": 36,
      "a": 38,
      "d": 34,
      "s": 60
    },
    "c": 0.42,
    "group": "coast",
    "d": "small fish, squid, and crustaceans",
    "h": "southern Australian and New Zealand coasts",
    "taxon": "Eudyptula minor · the only living Eudyptula in AviList; Australian birds are sometimes split",
    "f": "The only living Eudyptula species in AviList is also the smallest living penguin, standing roughly thirty centimetres tall. It hunts small fish and squid at sea by day, then usually returns after dusk to a burrow, crevice or sheltered nest on land. Its upper feathers are slate blue rather than the black worn by most penguins, giving the familiar Little Blue name. Genetic differences between Australian and New Zealand lineages have led some authorities to split the Australian Little Penguin as Eudyptula novaehollandiae; AviList currently keeps those birds within this one species."
  },
  {
    "k": "anatolianshepherd",
    "n": "Anatolian Shepherd",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 64,
      "a": 58,
      "d": 62,
      "s": 44
    },
    "c": 0.32,
    "group": "breeding",
    "d": "a balanced domestic dog diet",
    "h": "homes and working farms with people",
    "taxon": "Canis familiaris · a domestic breed of Canis lupus; one of 8 living Canis taxa in the Mammal Diversity Database",
    "f": "This is a livestock guardian, not a separate species and not quite the same kind of worker as a herding dog. Anatolian Shepherds were selected to stay with flocks, notice trouble and make decisions at a distance from a handler. Size, speed and a calm willingness to stand their ground can deter a predator before a fight begins. That independence was useful on open country; in a household it also means that early socialisation, secure boundaries and thoughtful handling matter. Beneath the specialised working build is the same domestic animal as every village dog and lapdog: a human-shaped form of the gray wolf."
  },
  {
    "k": "angorarabbit",
    "n": "Angora Rabbit",
    "t": [
      "Swift",
      "Wild"
    ],
    "b": {
      "h": 34,
      "a": 32,
      "d": 34,
      "s": 56
    },
    "c": 0.48,
    "group": "breeding",
    "d": "hay, grasses, and leafy plants",
    "h": "human care as a domestic rabbit breed",
    "taxon": "Oryctolagus cuniculus · a domestic wool-breed group; one of 2 living Oryctolagus species",
    "f": "“Angora rabbit” is not one wild species, and even among breeders it is not one universal breed. The American Rabbit Breeders Association recognises English, French, Giant and Satin Angoras separately, all descended from the European rabbit. Their unusually long, fine fibre is gathered by combing, plucking loose wool or shearing, depending on breed and husbandry. The cloudlike coat is a human-selected production trait with a cost: without regular grooming it can mat, and swallowed fibre can accumulate when gut movement falters. What looks like ornament is therefore living husbandry — generations of selection that must be matched by generations of care."
  },
  {
    "k": "ballpythonmorph",
    "n": "Ball Python Morph",
    "t": [
      "Predator",
      "Armor"
    ],
    "b": {
      "h": 50,
      "a": 56,
      "d": 54,
      "s": 28
    },
    "c": 0.38,
    "group": "breeding",
    "d": "appropriately sized animal prey",
    "h": "human care as a selectively bred colour morph",
    "taxon": "Python regius · a captive-bred colour or pattern form, not a species; one of 10 living Python species",
    "f": "A morph is a heritable version of a ball python's colour or pattern, not a new kind of snake. Breeders have preserved rare variants and combined them into “designer” animals; research using harmless samples of shed skin has begun to identify the machinery beneath the names. Albino, Lavender Albino and Ultramel morphs are associated with variants in TYR, OCA2 and TYRP1, while a studied Piebald line carries a disruptive tfec variant. The palette may be extraordinary, but every one remains Python regius, with the same species- level needs and the same defensive habit of coiling around its head that gave the ball python its familiar name."
  },
  {
    "k": "bredaxolotl",
    "n": "Bred Axolotl",
    "t": [
      "Aquatic",
      "Swift"
    ],
    "b": {
      "h": 36,
      "a": 36,
      "d": 34,
      "s": 38
    },
    "c": 0.46,
    "group": "breeding",
    "d": "worms and small aquatic animals",
    "h": "cool freshwater aquariums under human care",
    "taxon": "Ambystoma mexicanum · a captive-bred form of one of 26 living Ambystoma species",
    "f": "Captive breeding has produced white, golden, dark and mottled axolotls, but the colours do not make separate species. An axolotl normally keeps larval features through adulthood: feathery external gills remain, and the animal breeds while still fully aquatic. It can regrow a lost limb and repair several other tissues without the heavy scarring familiar in mammals, which is why laboratory lines have become so valuable. That abundance can conceal the other half of its story. Wild A. mexicanum survives only in the altered waterways of Xochimilco and is Critically Endangered; a tank full of descendants is not a restored lake, nor a substitute for its wild population."
  },
  {
    "k": "bullterrier",
    "n": "Bull Terrier",
    "t": [
      "Armor",
      "Predator"
    ],
    "b": {
      "h": 52,
      "a": 58,
      "d": 50,
      "s": 44
    },
    "c": 0.36,
    "group": "breeding",
    "d": "a balanced domestic dog diet",
    "h": "homes with people as a domestic dog breed",
    "taxon": "Canis familiaris · a domestic breed of Canis lupus; one of 8 living Canis taxa in the Mammal Diversity Database",
    "f": "The Bull Terrier's long, convex “egg-shaped” head and small triangular eyes are not the marks of another canine species. They are an extreme, recognisable result of people choosing which domestic dogs reproduced. The breed's muscular body preserves its bull-and-terrier history, while generations of selection for companionship produced the exuberant modern house dog familiar to owners. A silhouette can tell a history of breeding, but it cannot finish the biography of the animal inside it: health, early experience, training and individual temperament still matter. The honest field-guide label is therefore breed, never species — one branch of domestic dog diversity shaped by a written standard."
  },
  {
    "k": "burmese",
    "n": "Burmese",
    "t": [
      "Swift",
      "Night"
    ],
    "b": {
      "h": 44,
      "a": 50,
      "d": 40,
      "s": 62
    },
    "c": 0.4,
    "group": "breeding",
    "d": "a balanced domestic cat diet",
    "h": "homes with people as a domestic cat breed",
    "taxon": "Felis catus · a domestic breed derived from Felis lybica; one of 7 living Felis taxa in the Mammal Diversity Database",
    "f": "The modern American Burmese breeding programme began with Wong Mau, a small brown cat brought from Burma to the United States in 1930. Planned matings, including early crosses with Siamese cats, showed that her warm “sepia” colour could breed true and established a new registry population. Today's compact, heavy-feeling Burmese comes in several accepted colours, depending on the registry; “Burmese” and “European Burmese” are also judged as separate breeds in some systems. Those boundaries are human pedigree rules, not reproductive barriers in nature. The animal is still a domestic cat — the same parent species beneath a carefully maintained coat, body shape and family record."
  },
  {
    "k": "cornishrex",
    "n": "Cornish Rex",
    "t": [
      "Swift",
      "Night"
    ],
    "b": {
      "h": 38,
      "a": 44,
      "d": 34,
      "s": 68
    },
    "c": 0.42,
    "group": "breeding",
    "d": "a balanced domestic cat diet",
    "h": "warm homes with people as a domestic cat breed",
    "taxon": "Felis catus · a domestic breed derived from Felis lybica; one of 7 living Felis taxa in the Mammal Diversity Database",
    "f": "In Cornwall in 1950, an otherwise ordinary farm cat produced a curly-coated kitten named Kallibunker. Breeding showed that his unusual coat was inherited as a recessive trait, and that chance mutation became the foundation of the Cornish Rex. Its very soft waves are made mostly from fine undercoat rather than the usual layered coat with prominent guard hairs; even the whiskers may curl. Warm skin and a light coat can make the cat feel unusually hot to a hand, but it does not run at a different feline temperature. A single inherited variant changed the texture people see, not the species of the cat beneath it."
  },
  {
    "k": "domesticfox",
    "n": "Domestic Fox",
    "t": [
      "Swift",
      "Predator"
    ],
    "b": {
      "h": 42,
      "a": 52,
      "d": 38,
      "s": 70
    },
    "c": 0.34,
    "group": "breeding",
    "d": "a varied omnivorous diet under expert care",
    "h": "specialist human care as a domesticated fox line",
    "taxon": "Vulpes vulpes · a behaviourally selected captive red-fox line, not a separate species; one of 12 living Vulpes species",
    "f": "The famous “domesticated fox” experiment did not begin by lifting untouched wild foxes into a laboratory. In 1959, researchers founded selection lines from red foxes already bred on fur farms, then repeatedly chose animals by their response to people. Over generations the tame line approached willingly, sought contact and showed less fear; changes in development, coat and body form also appeared. The result is powerful evidence that selection on behaviour can reshape an animal, but it is not a new species and not proof that any rescued wild fox makes an easy pet. It is a particular experimental population of the red fox, with a documented breeding history."
  },
  {
    "k": "egyptianmau",
    "n": "Egyptian Mau",
    "t": [
      "Swift",
      "Predator"
    ],
    "b": {
      "h": 42,
      "a": 50,
      "d": 36,
      "s": 76
    },
    "c": 0.38,
    "group": "breeding",
    "d": "a balanced domestic cat diet",
    "h": "homes with people as a domestic cat breed",
    "taxon": "Felis catus · a domestic breed derived from Felis lybica; one of 7 living Felis taxa in the Mammal Diversity Database",
    "f": "The Egyptian Mau is a registry breed whose standard asks for distinct spots, including markings that need not follow the orderly rosettes of a wild cat. A loose fold of skin between flank and hind leg and slightly longer hind limbs help give it a long-striding outline. “Mau” and the spotted coat invite an easy story of an unbroken line from cats painted in ancient Egypt, but modern breed history and an evocative name cannot prove that pedigree across millennia. The solid claim is more interesting than the romance: selective breeding stabilised a rare domestic-cat pattern, and people agreed on the features by which that population would be recognised."
  },
  {
    "k": "fancypigeon",
    "n": "Fancy Pigeon",
    "t": [
      "Aerial",
      "Swift"
    ],
    "b": {
      "h": 34,
      "a": 36,
      "d": 32,
      "s": 64
    },
    "c": 0.44,
    "group": "breeding",
    "d": "seeds, grains, and suitable greens",
    "h": "lofts and homes under human care",
    "taxon": "Columba livia · a domestic fancy form of the Rock Pigeon; one of 32 living Columba species",
    "f": "Pouters, tumblers, fantails and many other fancy pigeons are variations of one parent species, the Rock Pigeon. Fanciers amplified small inherited differences into crests, feathered feet, inflated crops, unusual flight and tails spread like fans; Darwin used that astonishing range to explain what selection can do. The bird under every costume keeps a distinctly pigeon form of parenthood. Both sexes make “crop milk,” a nutrient-rich shedding from the crop lining, and feed it to their squabs. City pigeons, racing birds and exhibition champions can look worlds apart, yet they remain members of the same freely interbreeding domestic lineage."
  },
  {
    "k": "frenchbulldog",
    "n": "French Bulldog",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 42,
      "a": 40,
      "d": 46,
      "s": 28
    },
    "c": 0.42,
    "group": "breeding",
    "d": "a balanced domestic dog diet",
    "h": "homes with people as a domestic dog breed",
    "taxon": "Canis familiaris · a domestic breed of Canis lupus; one of 8 living Canis taxa in the Mammal Diversity Database",
    "f": "Bat ears and a short, square muzzle make the French Bulldog readable from a distance. Both are breed traits chosen by people, not signs of a distinct species. The shortened skull is also more than a look: in some dogs, crowded soft tissues and narrowed airways cause brachycephalic obstructive airway syndrome, making breathing, exercise and cooling harder. Severity varies, so the fair response is neither to romanticise the snort nor to diagnose an animal from its photograph. Breeding away from exaggeration, health screening and veterinary assessment can protect the companion behind the silhouette. A fashionable outline carries a real human responsibility."
  },
  {
    "k": "manx",
    "n": "Manx",
    "t": [
      "Swift",
      "Wild"
    ],
    "b": {
      "h": 42,
      "a": 46,
      "d": 40,
      "s": 58
    },
    "c": 0.4,
    "group": "breeding",
    "d": "a balanced domestic cat diet",
    "h": "homes with people as a domestic cat breed",
    "taxon": "Felis catus · a domestic breed derived from Felis lybica; one of 7 living Felis taxa in the Mammal Diversity Database",
    "f": "Not every Manx is completely tailless. Breeders describe a continuum from “rumpy” cats with no visible tail through risers and stumpies to fully tailed “longies.” The inherited Manx variant is incompletely dominant; embryos with two copies generally do not survive, and one copy can alter the final vertebrae by very different amounts. In some kittens the same developmental change also brings spinal, bowel or bladder problems, so a missing tail must never be treated as harmless decoration by default. Tailed cats remain part of Manx breeding programmes. The breed is one domestic-cat population organised around a variable mutation, not a naturally tailless species."
  },
  {
    "k": "munchkin",
    "n": "Munchkin",
    "t": [
      "Wild",
      "Armor"
    ],
    "b": {
      "h": 40,
      "a": 40,
      "d": 42,
      "s": 42
    },
    "c": 0.42,
    "group": "breeding",
    "d": "a balanced domestic cat diet",
    "h": "homes with people as a domestic cat breed",
    "taxon": "Felis catus · a short-legged domestic form derived from Felis lybica; one of 7 living Felis taxa in the Mammal Diversity Database",
    "f": "The Munchkin's short limbs come from a dominant inherited change affecting long- bone growth. Its body, head and coat can otherwise take many ordinary domestic- cat forms because early programmes deliberately outcrossed short-legged cats to the wider cat population. Registry status is not universal: TICA recognises the breed, while other major registries do not, and welfare debate continues around selecting a skeletal difference for appearance. That uncertainty belongs in the guide. “Munchkin” identifies a human-maintained trait and pedigree system, not a new species, and the charm of a low stance does not remove the obligation to follow mobility and health evidence as it develops."
  },
  {
    "k": "silkworm",
    "n": "Silkworm",
    "t": [
      "Bug",
      "Canopy"
    ],
    "b": {
      "h": 24,
      "a": 20,
      "d": 28,
      "s": 12
    },
    "c": 0.56,
    "group": "breeding",
    "d": "mulberry leaves",
    "h": "human-managed trays and mulberry farms",
    "taxon": "Bombyx mori · a domesticated moth, one of 12 currently accepted Bombyx species in Catalogue of Life",
    "f": "The silkworm is the caterpillar of a moth domesticated from the wild Bombyx mandarina lineage more than five thousand years ago. People repeatedly chose larvae that grew well and spun useful cocoons, eventually producing an animal that depends heavily on human care; the adult domestic moth has lost effective flight. A cocoon is built from a long fibroin filament bonded with sericin, so the shelter made for metamorphosis can be softened and reeled into thread. “Silkworm breeds” differ in colour, development and cocoon properties, but they are lines within B. mori. This is domestication written into an insect's whole life cycle, not a separate species for every silk."
  },
  {
    "k": "mutt",
    "n": "Mutt",
    "t": [
      "Wild",
      "Swift"
    ],
    "b": {
      "h": 48,
      "a": 50,
      "d": 44,
      "s": 58
    },
    "c": 0.46,
    "group": "kept",
    "d": "a balanced domestic dog diet",
    "h": "homes and communities with people",
    "taxon": "Canis familiaris · a mixed-ancestry domestic dog derived from Canis lupus; one of 8 living Canis taxa in the Mammal Diversity Database",
    "f": "“Mutt” is an ancestry description, not a breed and certainly not a species. Many are not tidy first-generation crosses between two named breeds: in one large genomic study, most mutts carried meaningful ancestry from four or more breeds, and no single breed dominated many of them. Their bodies and behaviour are therefore mosaics, but even a DNA percentage is not a personality test. Another broad study found breed ancestry explained only a modest share of behavioural variation among individual dogs. Meet the animal in front of you — its health, learning and lived experience — before inventing a character from an uncertain family tree."
  },
  {
    "k": "pitbull",
    "n": "Pit Bull",
    "t": [
      "Armor",
      "Predator"
    ],
    "b": {
      "h": 54,
      "a": 60,
      "d": 52,
      "s": 48
    },
    "c": 0.38,
    "group": "kept",
    "d": "a balanced domestic dog diet",
    "h": "homes with people as a domestic dog type",
    "taxon": "Canis familiaris · a domestic dog type label, not one species or universally defined breed; one of 8 living Canis taxa in the Mammal Diversity Database",
    "f": "“Pit bull” changes meaning with speaker and registry. It may indicate the American Pit Bull Terrier, group several bull-and-terrier breeds together, or be applied to a mixed dog with a broad head and muscular build. That looseness has consequences: shelter studies found that observers often disagreed over which dogs were pit-bull type, and visual labels did not consistently match tested ancestry. History can shape tendencies in a breeding population, but a type name cannot safely predict one companion's behaviour. Humane training, socialisation, supervision and assessment of the individual matter for every dog. The photograph records a dog; the contested label should not be allowed to write its fate."
  },
  {
    "k": "cornsnake",
    "n": "Corn Snake",
    "t": [
      "Swift",
      "Predator"
    ],
    "b": {
      "h": 40,
      "a": 48,
      "d": 38,
      "s": 58
    },
    "c": 0.42,
    "group": "kept",
    "d": "appropriately sized animal prey",
    "h": "temperate North America and, as a companion, human care",
    "taxon": "Pantherophis guttatus · one of 9 living Pantherophis species",
    "f": "One of nine living Pantherophis snakes, the Corn Snake is a nonvenomous constrictor native to the southeastern United States. Its common name may come from finding it around corn stores rich in mice, or from the maize-like black- and-white checks across its belly; the origin is not settled. The wild animal's orange saddles break up its outline through leaf litter, while captive breeders have produced many colour and pattern morphs. Those morphs remain this species. Its reputation as a manageable companion should not erase the animal behind it: a climbing, hiding, heat-dependent predator whose long-term care must be built around snake biology rather than convenience."
  },
  {
    "k": "beardeddragon",
    "n": "Bearded Dragon",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 44,
      "a": 46,
      "d": 48,
      "s": 36
    },
    "c": 0.42,
    "group": "kept",
    "d": "insects and leafy plants",
    "h": "dry Australian habitats and, as a companion, human care",
    "taxon": "Pogona vitticeps · Central Bearded Dragon, one of 6 living Pogona species",
    "f": "One of six living Pogona species, the Central Bearded Dragon communicates with a body that can look almost theatrical. It expands and darkens the spiny skin beneath its throat, bobs its head and may wave one forelimb in social displays. Temperature reaches deeper than basking behaviour. In this species, high incubation temperatures can override the usual ZZ genetic pathway and produce functional females from genetically male embryos — a striking link between climate and development. Captive colours and a calm-looking pose do not make it a domestic breed. It remains an Australian lizard requiring ultraviolet light, heat gradients and room to perform the behaviours its signals evolved to serve."
  },
  {
    "k": "russiantortoise",
    "n": "Russian Tortoise",
    "t": [
      "Armor",
      "Wild"
    ],
    "b": {
      "h": 48,
      "a": 34,
      "d": 62,
      "s": 22
    },
    "c": 0.4,
    "group": "kept",
    "d": "grasses, leaves, and flowers",
    "h": "dry Central Asian country and, as a companion, human care",
    "taxon": "Testudo horsfieldii · Central Asian or four-toed tortoise, one of 5 living Testudo species",
    "f": "One of five living Testudo species, this tortoise ranges across Central Asia; the pet-trade name “Russian” tells only part of its geography. Four toes on each forefoot give it another common name, while strong limbs make it an exceptional digger. In the continental wild it escapes punishing heat and cold underground and may fit much of its feeding and breeding into a brief active season. A small shell therefore does not mean a small spatial life. It can tunnel under a carelessly built boundary and may live for decades, turning an impulse purchase into a commitment that outlasts homes, jobs and sometimes the person who first carried it home."
  },
  {
    "k": "leopardgecko",
    "n": "Leopard Gecko",
    "t": [
      "Night",
      "Swift"
    ],
    "b": {
      "h": 34,
      "a": 42,
      "d": 34,
      "s": 58
    },
    "c": 0.44,
    "group": "kept",
    "d": "insects and other small invertebrates",
    "h": "dry South Asian ground and, as a companion, human care",
    "taxon": "Eublepharis macularius · one of 8 living Eublepharis species",
    "f": "One of eight living Eublepharis species, the Leopard Gecko keeps features that many familiar wall geckos have lost: movable eyelids and toes without adhesive climbing pads. It walks rather than sticking to glass. Its thick tail stores fat and can be shed at a fracture plane during danger; a replacement grows, but it is not an exact copy and the escape spends valuable reserves. Captive breeders have produced pale, orange and patternless morphs, all still E. macularius. Gentle handling can make an individual seem domesticated, yet its nocturnal rhythm, thermal choices and need for secure retreats remain those of a small ground-dwelling predator."
  },
  {
    "k": "alaotragrebe",
    "n": "Alaotra Grebe",
    "t": [
      "Aquatic",
      "Aerial"
    ],
    "b": {
      "h": 36,
      "a": 38,
      "d": 32,
      "s": 52
    },
    "c": 0.5,
    "group": "vigil",
    "d": "small fish and aquatic invertebrates",
    "h": "Lake Alaotra in Madagascar",
    "status": "EX",
    "org": "† 1985",
    "taxon": "Tachybaptus rufolavatus · an extinct sixth member beside 5 living Tachybaptus species",
    "f": "This small grebe lived only around Lake Alaotra in Madagascar. Short wings limited its power to abandon a failing wetland, while introduced predatory fish, monofilament gillnets and heavy change to the lake pressed on the population together. The last generally accepted records came in the 1980s; after repeated searches failed, it was declared extinct in 2010. No single final bird or final cause can be named with confidence. That is the warning in the Vigil: an animal can disappear through several ordinary pressures, each survivable in isolation, until an endemic species with nowhere else to go is represented only by skins, notes and disputed sightings."
  },
  {
    "k": "bachmanswarbler",
    "n": "Bachman's Warbler",
    "t": [
      "Aerial",
      "Bug"
    ],
    "b": {
      "h": 28,
      "a": 34,
      "d": 26,
      "s": 64
    },
    "c": 0.52,
    "group": "vigil",
    "d": "insects and spiders",
    "h": "swamp forest of the southeastern United States and Cuba",
    "status": "CR",
    "org": "CR (Possibly Extinct); U.S. FWS declared extinct in 2021",
    "taxon": "Vermivora bachmanii · declared extinct by the U.S. in 2023; AviList retains it as Critically Endangered (Possibly Extinct) beside 2 living Vermivora species",
    "f": "Bachman's Warbler migrated between swampy forests and cane-rich understory in the southeastern United States and winter habitat in Cuba. Clearing those bottomland woods removed a specialised breeding landscape over a huge area. Reports continued after the last widely accepted United States record in 1962, and possible Cuban observations reached the 1980s, but none produced the evidence needed to demonstrate survival. The U.S. Fish and Wildlife Service removed it from Endangered Species Act protection as extinct in 2023. Its silence is not proof that migration failed in one dramatic moment; it is the end point of lost habitat at both ends of a journey and decades without a verifiable return. AviList and the IUCN still retain it as Critically Endangered (Possibly Extinct), preserving an honest disagreement between authorities."
  },
  {
    "k": "christmasislandforestskink",
    "n": "Christmas Island Forest Skink",
    "t": [
      "Canopy",
      "Swift"
    ],
    "b": {
      "h": 30,
      "a": 36,
      "d": 32,
      "s": 56
    },
    "c": 0.5,
    "group": "vigil",
    "d": "insects and other small invertebrates",
    "h": "forest floor on Christmas Island",
    "status": "EX",
    "org": "† 2014",
    "taxon": "Emoia nativitatis · one of 78 Emoia species returned by the Reptile Database; extinct",
    "f": "This small skink existed only on Christmas Island. It was still described as common in the late twentieth century, then collapsed so quickly that the last wild record came in 2010. A captive-rescue attempt began with only a few animals; the final known individual, nicknamed Gump, died in 2014, making this Australia's first recorded reptile extinction since European colonisation. The proximate cause remains unresolved. Introduced predators, including the wolf snake and giant centipede, and disease have all been investigated, but certainty arrived too late for the animal. The honest memorial preserves that uncertainty: knowing a loss occurred is not the same as knowing which pressure dealt the last blow."
  },
  {
    "k": "roundislandburrowingboa",
    "n": "Round Island Burrowing Boa",
    "t": [
      "Predator",
      "Burrow"
    ],
    "b": {
      "h": 46,
      "a": 52,
      "d": 44,
      "s": 40
    },
    "c": 0.46,
    "group": "vigil",
    "d": "lizards and other small prey",
    "h": "Round Island, Mauritius",
    "status": "EX",
    "org": "† 1975",
    "taxon": "Bolyeria multocarinata · the only named species in Bolyeria; extinct",
    "f": "The only species placed in Bolyeria survived on tiny Round Island off Mauritius after vanishing from the larger islands. It belonged to a singular boa family whose upper jaw contains an extra joint, a feeding mechanism shared today only by the surviving Round Island keel-scaled boa. Goats and rabbits stripped vegetation and accelerated erosion; introduced predators may have added pressure. The last confirmed burrowing boa was found in 1975. Round Island's habitat has since been restored with remarkable success, but this lineage cannot return with the plants. Recovery can rescue a community while still arriving one species too late."
  },
  {
    "k": "tecopapupfish",
    "n": "Tecopa Pupfish",
    "t": [
      "Aquatic",
      "Swift"
    ],
    "b": {
      "h": 26,
      "a": 32,
      "d": 24,
      "s": 60
    },
    "c": 0.54,
    "group": "vigil",
    "d": "algae and tiny aquatic invertebrates",
    "h": "warm desert springs near Tecopa, California",
    "status": "EX",
    "org": "† 1970",
    "taxon": "Cyprinodon nevadensis calidae · an extinct subspecies of the Amargosa Pupfish, within a genus of 49 FishBase-listed species",
    "f": "The Tecopa Pupfish was a subspecies, not a separate species: a tiny local form of Cyprinodon nevadensis adapted to the hot, salty outflows of springs at Tecopa, California. Fish and Wildlife Service records describe animals enduring water near 43 °C. Bathhouse development joined spring channels and altered their flow, while introduced fishes and hybridisation further erased the isolated population. Surveys failed to find it, and in 1981 it became the first animal removed from the U.S. endangered list because it was judged extinct. Its loss shows why rank is no measure of value: a subspecies can carry an adaptation found nowhere else."
  }
];
const P69 = P69_SPECIES.map((species) => species.k);

P69_SPECIES.forEach((species) => {
  const special = species.group === "breeding"
    ? { breed: true, org: species.org || "selectively bred form" }
    : species.group === "kept"
      ? { dom: true, org: species.org || "companion animal" }
      : species.group === "vigil"
        ? { mem: true, org: species.org || species.status || "The Vigil" }
        : {};
  DEX[species.k] = {
    n: species.n, art: species.k, t: species.t.slice(), b: { ...species.b },
    m: [], l: [], c: species.c, ...special,
  };
  INFO[species.k] = {
    taxon: species.taxon, d: species.d, h: species.h, f: species.f,
    ...(species.status ? { s: species.status } : {}),
  };
});

Object.assign(PHOTO_ART, Object.fromEntries(P69.map((key) => [key, true])));

{
  let built = 0;
  const thin = [];
  P69.forEach((key) => {
    const learned = buildLearnset(key);
    if (!learned || !learned.start || !learned.start.length) {
      thin.push(key);
      DEX[key].m = ["tackle"];
      DEX[key].l = [];
      return;
    }
    DEX[key].m = learned.start.slice(0, 3);
    DEX[key].l = (learned.learn || []).filter(([, move]) => !DEX[key].m.includes(move));
    built++;
  });

  const placements = [
    { map: "polarsea", pool: "poolWater", list: [
      "antarcticicefish", "antarcticseaspider", "antarctictoothfish", "arcticchar",
      "arcticcod", "capelin", "greenlandhalibut",
    ] },
    { map: "polarsea", pool: "pool", list: [
      "adeliepenguin", "arctictern", "gentoopenguin", "ivorygull", "kingpenguin",
      "littleauk", "longtailedduck", "ringedseal", "rossgull", "snowpetrel",
      "southpolarskua",
    ] },
    { map: "tundra", pool: "pool", list: [
      "arctictern", "arcticwolf", "collaredlemming", "ivorygull", "rockptarmigan",
      "rossgull",
    ] },
    { zone: "alpine", pool: "pool", list: [
      "alpinechamois", "alpinechough", "alpinesalamander", "apollobutterfly",
      "argali", "barheadedgoose", "himalayanjumpingspider", "kiang", "lammergeier",
      "mountaingoat", "rockhyrax", "tibetanantelope", "wallcreeper",
      "whiterumpedvulture", "woollyflyingsquirrel",
    ] },
    { map: "savanna", pool: "pool", list: ["gemsbok"] },
    { map: "thicket", pool: "pool", list: ["iberianlynx", "woodfrog"] },
    { map: "route2", pool: "pool", list: ["woodfrog"] },
    { zone: "desert", pool: "pool", list: ["mexicanredknee"] },
    { map: "outback", pool: "pool", list: ["mexicanredknee"] },
    { map: "shore", pool: "pool", list: ["littlebluepenguin"] },

    { map: "route1", pool: "pool", list: ["mutt", "pitbull"] },
    { map: "route4", pool: "pool", list: [
      "beardeddragon", "cornsnake", "leopardgecko", "russiantortoise",
    ] },
    { map: "rescue", pool: "pool", list: [
      "mutt", "pitbull", "beardeddragon", "cornsnake", "leopardgecko",
      "russiantortoise", "angorarabbit", "ballpythonmorph", "bredaxolotl",
      "fancypigeon", "silkworm",
    ] },
    { map: "kennel1", pool: "pool", list: ["frenchbulldog"] },
    { map: "kennel2", pool: "pool", list: ["anatolianshepherd", "bullterrier"] },
    { map: "kennel4", pool: "pool", list: ["domesticfox"] },
    { map: "cattery1", pool: "pool", list: ["manx", "munchkin"] },
    { map: "cattery4", pool: "pool", list: ["burmese", "cornishrex", "egyptianmau"] },

    { map: "vig4", pool: "pool", list: [
      "christmasislandforestskink", "roundislandburrowingboa",
    ] },
    { map: "vig6", pool: "pool", list: ["bachmanswarbler"] },
    { map: "vig7", pool: "pool", list: ["alaotragrebe", "tecopapupfish"] },
  ];

  const placed = new Set();
  let added = 0;
  const usable = (mapKey, pool) => MAPS[mapKey] && Array.isArray(MAPS[mapKey][pool])
    && MAPS[mapKey][pool].length;
  const drop = (mapKey, pool, key) => {
    if (!usable(mapKey, pool)) return;
    if (!MAPS[mapKey][pool].some(([species]) => species === key)) {
      MAPS[mapKey][pool] = [...MAPS[mapKey][pool], [key, 3]];
      added++;
    }
    const places = WHERE[key] || (WHERE[key] = []);
    if (!places.some((place) => place.k === mapKey)) {
      places.push({
        k: mapKey, n: MAPS[mapKey].name, z: MAPS[mapKey].zone,
        lvl: pool === "poolWater" ? (MAPS[mapKey].lvlWater || MAPS[mapKey].lvl) : MAPS[mapKey].lvl,
      });
    }
    placed.add(key);
  };

  placements.forEach(({ map, zone, pool, list }) => {
    const maps = map ? [map] : Object.keys(MAPS).filter((key) => MAPS[key].zone === zone);
    list.forEach((key) => maps.forEach((mapKey) => drop(mapKey, pool, key)));
  });

  const homeless = P69.filter((key) => !placed.has(key));
  const hiddenFromGuide = P69.filter((key) => !(WHERE[key] || []).length);
  console.log("[part69] approved sixty-six: " + P69.length + " species | learnsets: " + built
    + " | pool entries added: " + added + " | reachable: " + placed.size + "/" + P69.length
    + " | guide locations: " + (P69.length - hiddenFromGuide.length) + "/" + P69.length
    + (thin.length ? " | FALLBACK MOVES: " + thin.join(", ") : "")
    + (homeless.length ? " | NOWHERE TO LIVE: " + homeless.join(", ") : "")
    + (hiddenFromGuide.length ? " | HIDDEN FROM GUIDE: " + hiddenFromGuide.join(", ") : ""));
}
