// GENERATED by design/tools/forge_alpine.py - edit the design there and re-run it,
// never by hand here. mapforge refuses to write a map it can prove is
// broken, and part103 checks it again against the live game on load.
REBUILT_REGIONS.push({ name: "alpine", maps: {
 "route6": {
  "rows": [
   "TTTggggggggg..gggggggggggTTT",
   "TTTggggggggg..gggggggggggTTT",
   "TTTggg*gggg*..gggggggggggTTT",
   "TTTgg^ggg*gg..ggg¡ggGGGggTTT",
   "TTTTg^gggggg..ggggggggggTTTT",
   "TTTgGGGGGggg..ggggggggTg^TTT",
   "TTTgGGGGGggg..ggTggΩggg^TTTT",
   "TTTgGGGGGggg..ggggggg*g^TTTT",
   "TT^gTgggRggg..ggggggggggTTTT",
   "TT^ggggggggg..ggTgggggT!TTTT",
   "TTT!Tggggggg..g**gggggggTTTT",
   "e..........................e",
   "T..........................T",
   "TTTTgggggggg..ggggggRgggTTTT",
   "TTTTgGGGgggg..gggggggggTTTTT",
   "TTT^gggggggg...ggggGGGGGTTTT",
   "TTTTgggggggg...ggggGGGGGgTTT",
   "TTTTgggggRggg..g⁂ggGGGGGgTTT",
   "TTTggWWWggggg..gggggggggg^TT",
   "TTTTggggggggg..gg*ggggTggTTT",
   "TTTggggTggggg..ggggggTgg*^TT",
   "TT^ggggggTggg..gggggTggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT"
  ],
  "cast": {
   "3,10": "route6:gate",
   "23,9": "route6:gate2",
   "8,8": "route6:4,4",
   "20,13": "route6:11,10",
   "9,17": "route6:6,12"
  },
  "marks": {
   "19,6": "lm_krummholz"
  },
  "finds": {
   "23,4": {
    "id": "alp_r6_trees",
    "item": "berries",
    "n": 3
   },
   "4,20": {
    "id": "alp_r6_tarn",
    "item": "coins",
    "n": 210
   }
  },
  "exits": {
   "0,11": {
    "map": "tundra",
    "x": 7,
    "y": 8
   },
   "27,11": {
    "map": "peak",
    "x": 7,
    "y": 14
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "n": {
    "map": "seg_a1",
    "off": 0
   },
   "s": {
    "map": "town6",
    "off": 0
   }
  },
  "gen": 7
 },
 "seg_a1": {
  "rows": [
   "TTTggggggggggg..ggggggggggTT",
   "TTTggggggggggg..ggggggggggTT",
   "TTgggggggggggg..Rgg^ggggggTT",
   "TT^ggggggggggg..g^g^gggg^gTT",
   "TTTg^ggggRgggg..g......g^ggT",
   "T^gg^ggggggggg..g.......^ggT",
   "T^gTgggggg⁌ggg..gg..Ω...ggTT",
   "TTT!gggggggggg..ggggg*gggggT",
   "e...............gggggggggggT",
   "T...............ggggggRgTgTT",
   "TTggggRggggggg..gggTgggggggT",
   "TTgggggggggggg..gggggggggggT",
   "TTTgTGGGGgggg*..ggggg^ggggTT",
   "TTT*TGGGGggggg..Tgg*ggg^ggTT",
   "TTggGGGGGggg....ggggggggggTT",
   "T^gggg*ggggg....ggggggggggTT",
   "TTggggggRggg..gg⁂ggggggTgTTT",
   "TTTgg¡gggggT..ggggGGGGGggTTT",
   "TTgggggggTgg..ggggGGGGGgTTTT",
   "TTTggggggggg..gggRGGGGGgggTT",
   "TT^ggGGGgggg..ggg*gggggg*TTT",
   "TTTgggg*gggg..ggggggggTgTTTT",
   "TT^ggggggggg..ggggggggggg^TT",
   "TTTggggggggg..gggggggggggTTT"
  ],
  "cast": {
   "3,7": "seg_a1:gate",
   "6,10": "seg_a1:1,1",
   "9,4": "seg_a1:3,1",
   "16,2": "seg_a1:11,1",
   "8,16": "seg_a1:3,3",
   "22,9": "seg_a1:11,3",
   "17,19": "seg_a1:8,7"
  },
  "marks": {
   "20,6": "lm_pika"
  },
  "finds": {
   "24,8": {
    "id": "alp_a1_scree",
    "item": "wakeberry",
    "n": 1
   },
   "4,21": {
    "id": "alp_a1_south",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_nycterion",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   13,
   21
  ],
  "links": {
   "s": {
    "map": "route6",
    "off": 0
   },
   "n": {
    "map": "seg_a2",
    "off": 0
   }
  },
  "gen": 7
 },
 "seg_a2": {
  "rows": [
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..g^ggggggggggTTT",
   "TTggggggg⁂g..gg^g^gggggggTTT",
   "TTTgGGGGGgg..gggg^gg^g^*^TTT",
   "TTTgGGGGGgg..ggggggg^ggggTTT",
   "TTgTGGGGGgg..gggggggggg^gTTT",
   "TTggggggggg..gggg*gggggggTTT",
   "T^ggggggRgg..ggggWWWWWWgggTT",
   "TTTg*gggggg..gggWWWWWWWgggTT",
   "TTggTgggggg..gggWWWWWWWgTgTT",
   "TTggggTgggg..gg*ggggggggggTT",
   "T^gg*ggTggg..ggggggggWWgggTT",
   "TTggggggggg..ggggΩgggWWgRTTT",
   "TTTgTgRgggg..ggggggggWWgg^TT",
   "TTggggggggg.....gggggWWggTTT",
   "TTT*GGGGGgg.....ggg*gWWTggTT",
   "TTTgTGGGGggggg..g¡gggWWggTTT",
   "TTTTGGGGGggggg..gRgggWWgggTT",
   "TTTTgggggRgggg..gggggWWgggTT",
   "TTTgggggTgTggg..g¡gggWWTggTT",
   "TTTggggggggg*g..gGGGgWWgggTT",
   "TTTggggggggggg..gggggWWgggTT",
   "TTTggggggggggg..ggggggggggTT"
  ],
  "cast": {
   "24,13": "seg_a2:12,1",
   "8,8": "seg_a2:6,8",
   "6,14": "seg_a2:1,10",
   "9,19": "seg_a2:3,10",
   "17,18": "seg_a2:11,10"
  },
  "marks": {
   "17,13": "lm_glacier_posts"
  },
  "finds": {
   "24,9": {
    "id": "alp_a2_lake",
    "item": "antidote",
    "n": 1
   },
   "4,3": {
    "id": "alp_a2_corner",
    "item": "coins",
    "n": 220
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   15,
   21
  ],
  "links": {
   "s": {
    "map": "seg_a1",
    "off": 0
   },
   "n": {
    "map": "seg_a3",
    "off": 0
   }
  },
  "gen": 7
 },
 "seg_a3": {
  "rows": [
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..gggTgggggg^TT",
   "TT^gGGGGGgggg..Tggggggg*gTTT",
   "TTTgGGGGGgggg..gRggGGGGGgTTT",
   "TTTTGGGGG⁌ggg..ggggGGGGGgTTT",
   "TT^gggggggggg..ggggGGGGGgTTT",
   "TTT!ggggggggg..gggggg*TgTTTT",
   "e..............gggggggRggTTT",
   "T..............gggggggggTTTT",
   "TTTggggTgTTgg..ggg*ggggggTTT",
   "TT^*gRggggggg..gggRggggggTTT",
   "TTggggggggggg..gggggggTgTTTT",
   "TTggggggggggg..gggggggggTTTT",
   "TTgTggggggg....gggggΩggggTTT",
   "TTggggggggg....ggggggg*^gTTT",
   "TTgTggggggg..ggg⁂gggggg^gTTT",
   "TTgTgGGGggg..g*ggggggggggTTT",
   "TTggggggggg..gggggGGGGGggTTT",
   "TTgggTgRggg..gggggGGGGGgg^TT",
   "Tgggggggggg..*ggg¡GGGGGggTTT",
   "TggggggTggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT",
   "TTggggggggg..ggggggggggggTTT"
  ],
  "cast": {
   "3,7": "seg_a3:gate",
   "16,4": "seg_a3:6,1",
   "5,11": "seg_a3:1,5",
   "18,11": "seg_a3:6,5",
   "22,8": "seg_a3:13,5",
   "7,19": "seg_a3:6,7"
  },
  "marks": {
   "20,14": "lm_under_snow"
  },
  "finds": {
   "22,14": {
    "id": "alp_a3_drift",
    "item": "bigberries",
    "n": 1
   },
   "4,3": {
    "id": "alp_a3_firs",
    "item": "treats",
    "n": 2
   }
  },
  "exits": {
   "0,8": {
    "map": "shrine_rimehorn",
    "x": 7,
    "y": 8
   }
  },
  "beyond": {},
  "land": [
   12,
   21
  ],
  "links": {
   "s": {
    "map": "seg_a2",
    "off": 0
   },
   "n": {
    "map": "town7",
    "off": 0
   }
  },
  "gen": 7
 },
 "town7": {
  "rows": [
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTgg..TTTTTTTTTTTTT",
   "TTTTTTTTTTTTTXTTTTTTTTTTTTTT",
   "TTggggggggggg..!gggggggggTTT",
   "TTTgTgggggggg..ggggggggTgTTT",
   "TTTgHgggCgggg..gggYggggHgTTT",
   "TTTgggggggggg..gggggggggTTTT",
   "TTTggΩg¦............¦gΩggTTT",
   "TTTgTgg..Ω.....Ω..Ω..gTggTTT",
   "TTTgggg........WWWWW.gTgTTTT",
   "TTTgggg..R.....WWWWW.ggTTTTT",
   "TTTgggg........WWWWW.ggggTTT",
   "TTTgHgg...Ω.....Ω....ggHgTTT",
   "TTTgggg¦............¦ggggTTT",
   "TTTggΩgg*gggg..ggVggggΩggTTT",
   "T^gTgg*gggggg..gggggggggggTT",
   "TTgg.....................TTT",
   "TTgg.....................gTT",
   "TTgg!gΩgggg¦g..g¦gggΩggggTTT",
   "TTTgT*ggggggg..g*ggMgg*gggTT",
   "TTggggggHgggg..ggggggggggTTT",
   "TTTTggggggΩg!..gggg*gggHggTT",
   "TTTgggggggggg..ggggggggggTTT",
   "TTTgggggggggg..ggggggggggTTT"
  ],
  "cast": {
   "15,3": "town7:gate",
   "12,21": "town7:9,3",
   "4,18": "town7:8,12",
   "9,10": "town7:3,8",
   "17,14": "town7:9,10"
  },
  "marks": {
   "16,12": "lm_hot_spring",
   "5,7": "decor:woodpile",
   "22,7": "decor:woodpile",
   "5,14": "decor:woodpile",
   "22,14": "decor:woodpile",
   "10,21": "decor:woodpile",
   "9,8": "decor:sled",
   "20,18": "decor:sled",
   "10,12": "decor:stall",
   "15,8": "decor:bench",
   "18,8": "decor:bench",
   "6,18": "decor:crates"
  },
  "finds": {
   "24,15": {
    "id": "alp_t7_firs",
    "item": "revives",
    "n": 1
   }
  },
  "exits": {},
  "beyond": {},
  "land": [
   14,
   21
  ],
  "links": {
   "s": {
    "map": "seg_a3",
    "off": 0
   },
   "n": {
    "map": "route7",
    "off": 0,
    "fallback": {
     "tile": "13,0",
     "ch": "n",
     "map": "route7",
     "x": 7,
     "y": 14
    }
   }
  },
  "gen": 7
 }
}, inbound: [
 {
  "from": "tundra",
  "tile": "7,9",
  "map": "route6",
  "x": 1,
  "y": 11
 },
 {
  "from": "peak",
  "tile": "7,15",
  "map": "route6",
  "x": 26,
  "y": 11
 },
 {
  "from": "shrine_nycterion",
  "tile": "7,9",
  "map": "seg_a1",
  "x": 1,
  "y": 8
 },
 {
  "from": "shrine_rimehorn",
  "tile": "7,9",
  "map": "seg_a3",
  "x": 1,
  "y": 8
 },
 {
  "from": "route7",
  "tile": "7,15",
  "map": "town7",
  "x": 13,
  "y": 1
 }
] });
