"""Every living animal, by biome. Re-runnable; nothing is typed by hand.

IMPORTANT: biome_assign.js holds FOUR assignment blocks plus dot-assignments,
applied in file order with later winning:

    var BIOME_BY_HAND = {...}   hand assignments for species with no habitat text
    var BIOME_FIX     = {...}   corrections where the habitat RULES misfired
    var BIOME_MOVE    = {...}   Ayr's redistribution pass, 2026-08-24
    var FR            = {...}   Ayr's forest/rainforest review, 2026-08-25
    BIOME_BY_HAND.x = "y";      later one-offs

Earlier versions of this tool read only the first block, which silently threw
away every correction Ayr had made. Do not narrow this again.
"""
import io, re, glob, os
from collections import defaultdict

os.chdir("C:/Claude/wildlands")
src = ''.join(io.open(f, encoding='utf-8', errors='replace').read()
              for f in sorted(glob.glob('game.part*.jsx')))
BS = chr(92)


def args_at(s, i):
    depth, j, instr, esc = 0, i, None, False
    while j < len(s):
        c = s[j]
        if instr is not None:
            if esc:
                esc = False
            elif c == BS:
                esc = True
            elif c == instr:
                instr = None
        else:
            if c in ('"', "'"):
                instr = c
            elif c == '(':
                depth += 1
            elif c == ')':
                depth -= 1
                if depth == 0:
                    return s[i + 1:j]
        j += 1
    return ''


STR = re.compile('"([^"]*)"')
hab, disp, ctor = {}, {}, {}
for m in re.finditer(r'\b(note2?|fnote)\s*\(', src):
    a = STR.findall(args_at(src, m.end() - 1))
    if len(a) >= 3:
        hab.setdefault(a[0], a[2])
for m in re.finditer(r'([a-z0-9_]+):\s*\{', src):
    seg = src[m.end() - 1:m.end() + 800]
    hh = re.search(r'\bh:\s*"([^"]*)"', seg)
    if hh:
        hab.setdefault(m.group(1), hh.group(1))
for m in re.finditer(r'([a-z0-9_]+):\s*([A-Z]{1,2})\("([^"]*)"', src):
    ctor.setdefault(m.group(1), m.group(2))
    disp.setdefault(m.group(1), m.group(3))
for m in re.finditer(r'([a-z0-9_]+):\s*([A-Z]{1,2})\(', src):
    ctor.setdefault(m.group(1), m.group(2))

d = io.open('design/biomes.js', encoding='utf-8').read()
rules = [(m.group(1), m.group(2)) for m in re.finditer(r'\["([a-z]+)",\s*/(.+?)/i\]', d)]
merge = dict(re.findall(r'(\w+):\s*"(\w+)"', d[d.index('BIOME_MERGE'):]))

h = io.open('design/biome_assign.js', encoding='utf-8').read()
VALID = {"forest", "rainforest", "savanna", "wetland", "coast", "desert", "reef",
         "polar", "opensea", "alpine", "farmland", "deepsea", "cave", "taiga",
         "kelp", "polarsea", "tundra"}

# every var NAME = { ... }; block, in file order, later winning
hand, blocks = {}, []
for m in re.finditer(r'var\s+(\w+)\s*=\s*\{', h):
    body = h[m.end() - 1:]
    body = body[:body.index('};')]
    pairs = [(k, v) for k, v in re.findall(r'([a-z0-9_]+)\s*:\s*"(\w+)"', body)
             if v in VALID]
    if pairs:
        blocks.append((m.group(1), len(pairs)))
        hand.update(pairs)
for k, v in re.findall(r'BIOME_BY_HAND\.(\w+)\s*=\s*"(\w+)"', h):
    hand[k] = v

nots = set(re.findall('"([a-z0-9_]+)"',
                      h[h.index('NOT_A_SPECIES'):h.index('BIOME_BY_HAND')]))
for m in re.finditer(r'NOT_A_SPECIES\.push\(([^)]*)\)', h):
    nots.update(re.findall('"([a-z0-9_]+)"', m.group(1)))
for m in re.finditer(r'\[([^\]]*)\]\.forEach\(function \(k\) \{ NOT_A_SPECIES\.push', h):
    nots.update(re.findall('"([a-z0-9_]+)"', m.group(1)))

NOT_LIVING = {"mammoth": "extinct - belongs in The Record",
              "alpaca": "domesticated - belongs in The Kept",
              "llama": "domesticated - belongs in The Kept"}
living = sorted(k for k, c in ctor.items() if c in ('A', 'E'))


def classify(sp):
    if sp in hand:
        return hand[sp]
    t = hab.get(sp, '')
    for name, pat in rules:
        if re.search(pat, t, re.I):
            return name
    return None


NICE = {"alpine": "MOUNTAINS (The Divide)", "coast": "COAST (The Strand)",
        "deepsea": "DEEP SEA (The Dark)", "desert": "DESERT (The Dry)",
        "farmland": "FARMLAND (The Furrows)", "forest": "FOREST (The Weald)",
        "opensea": "OPEN OCEAN (The Blue)", "polar": "POLAR (The Floe)",
        "rainforest": "RAINFOREST (The Canopy)", "reef": "REEF (The Garden)",
        "savanna": "SAVANNA (The Long Grass)", "wetland": "WETLANDS (The Fens)"}

by = defaultdict(list)
stages, excluded, unplaced = [], [], []
for sp in living:
    if sp in nots or re.search(r'_(j|c|f|p|j2|i)$', sp):
        stages.append(sp)
        continue
    if sp in NOT_LIVING:
        excluded.append(sp)
        continue
    b = classify(sp)
    if b is None:
        unplaced.append(sp)
        continue
    by[merge.get(b, b)].append(sp)

placed = sum(len(v) for v in by.values())
o = ["# EVERY LIVING ANIMAL, BY BIOME", "",
     "Generated by `design/tools/biome_listing.py`, 2026-08-26. Re-runnable.", "",
     "Assignment blocks applied in file order, later winning: " +
     " -> ".join("**%s** (%d)" % b for b in blocks) + ", then one-off dot-assignments.",
     "", "## The count", "", "| | |", "|---|---|",
     "| Living roster (`A` + `E`) | **%d** |" % len(living),
     "| less life stages | -%d |" % len(stages),
     "| less not-living | -%d |" % len(excluded),
     "| less unplaced | -%d |" % len(unplaced),
     "| **Placed in the twelve biomes** | **%d** |" % placed, "",
     "| Biome | Count |", "|---|---|"]
for b in sorted(by, key=lambda x: -len(by[x])):
    o.append("| %s | **%d** |" % (NICE.get(b, b), len(by[b])))
o += ["| **Total** | **%d** |" % placed, "", "---"]
for b in sorted(by, key=lambda x: -len(by[x])):
    o += ["", "## %s - %d" % (NICE.get(b, b), len(by[b])), ""]
    names = sorted(disp.get(s, s) for s in by[b])
    for i in range(0, len(names), 4):
        o.append("- " + " - ".join(names[i:i + 4]))
o += ["", "---", "", "## Excluded, and why", "",
      "**Life stages (%d)** - these follow their adult:" % len(stages), "",
      "- " + " - ".join(sorted(disp.get(s, s) for s in stages)), "",
      "**Not living animals of any biome (%d):**" % len(excluded), ""]
for s in sorted(excluded):
    o.append("- **%s** - %s" % (disp.get(s, s), NOT_LIVING[s]))
if unplaced:
    o += ["", "**Still unplaced (%d):** %s" % (len(unplaced), ", ".join(unplaced))]
io.open('design/BIOME_LISTING.md', 'w', encoding='utf-8').write("\n".join(o) + "\n")

print("assignment blocks read:", blocks)
print("living %d = placed %d + stages %d + not-living %d + unplaced %d"
      % (len(living), placed, len(stages), len(excluded), len(unplaced)))
print("check:", placed + len(stages) + len(excluded) + len(unplaced) == len(living))
print()
for b in sorted(by, key=lambda x: -len(by[x])):
    print("  %-26s %d" % (NICE.get(b, b), len(by[b])))
