"""FIELD GUIDE EXPORT RECEIVER - run this, then paste read_field_guide.js in the gallery.

The field-guide text is ~325KB. It must come out of the RUNNING GAME rather than out
of the .jsx files - the same rule as GROUND_TRUTH.txt, and for the same reason - but
it is far too big to carry back through a browser console by hand.

So the page POSTs it here and this writes the file. No parsing, no chunking, no
copy-paste, and the export is repeatable next time the entries change.

    1.  python -m http.server 8009              (serve the repo)
    2.  python design/tools/fg_export_server.py (this, on 8010)
    3.  open http://localhost:8009/gallery.html and wait for it to finish loading
    4.  paste design/tools/read_field_guide.js into the console
    5.  both servers can be killed once design/FIELD_GUIDE.txt exists
"""
import io, os, sys
from http.server import BaseHTTPRequestHandler, HTTPServer

os.chdir("C:/Claude/wildlands")
OUT = 'design/FIELD_GUIDE.txt'
PORT = 8010

HEADER = """! THE FIELD GUIDE ENTRIES, read from the running game.
!
! Format: Name :: IUCN status :: the entry text
!
! DO NOT EDIT THIS FILE BY HAND and do not regex-parse the .jsx files to rebuild it.
! Regenerate it: see design/tools/fg_export_server.py and read_field_guide.js.
! The DEX exists in two shapes and every regex attempt at it has been wrong.
!
! Read by design/tools/the_librarian.py, which treats every sentence in here as a
! claim about the world that somebody has to check.
"""


class Receiver(BaseHTTPRequestHandler):
    def do_POST(self):
        n = int(self.headers.get('Content-Length', 0))
        body = self.rfile.read(n).decode('utf-8')
        io.open(OUT, 'w', encoding='utf-8', newline='\n').write(HEADER + body + '\n')
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Content-Type', 'text/plain')
        self.end_headers()
        rows = body.count('\n') + 1
        self.wfile.write(('wrote %s - %d rows, %d chars' % (OUT, rows, len(body))).encode())
        print('wrote %s - %d rows, %d chars' % (OUT, rows, len(body)))
        sys.stdout.flush()

    def log_message(self, *a):
        pass


if __name__ == '__main__':
    print('field-guide receiver listening on http://localhost:%d' % PORT)
    sys.stdout.flush()
    HTTPServer(('127.0.0.1', PORT), Receiver).serve_forever()
