"""Build game.part77.jsx - the badge system - from design/BADGES.txt and
design/BADGE_CARDS.txt.

    python design/tools/make_badge_part.py

The design files are the only source, exactly as make_badge_page.py treats them
for badges.html. Run this after any edit to either, then run it by Uncle Albert.

WHY IT IS GENERATED RATHER THAN WRITTEN
---------------------------------------
431 cards is 160KB of prose that already exists, already passes Uncle Albert, and
is already being fact-checked by The Librarian. Hand-copying it into a .jsx would
create a second copy that drifts from the first, and the drift would be invisible
- which is the failure this whole toolchain exists to prevent.

THE NAME PROBLEM, WHICH IS THE REAL WORK
----------------------------------------
BADGES.txt uses TERRANE's names, after the generics audit: "Panther Chameleon",
"Stoplight Parrotfish", "Japanese Macaque". Safari Saga's DEX still holds the
names those replaced - "Chameleon", "Parrotfish", "Macaque" - because the renames
live in PENDING_MOVES.txt and have never been applied to the game data.

55 of the 324 members are affected. So the part resolves member names AT RUNTIME
against the live DEX, using the rename table as a fallback, and says out loud how
many resolved. It does NOT bake in a key list: a baked list would silently rot the
day a species is renamed in the game, and a resolver that reports its own failures
will not.
"""
import io, os, json, re

os.chdir("C:/Claude/wildlands")

OUT = 'game.part77.jsx'

# ---- the badges -------------------------------------------------------------
badges = []
for line in io.open('design/BADGES.txt', encoding='utf-8'):
    s = line.strip()
    if not s or s.startswith('!'):
        continue
    cat, name, dif, tiers, concept, mem = [x.strip() for x in s.split('::')]
    members, rules = [], []
    for m in [x.strip() for x in mem.split('|') if x.strip()]:
        if m.startswith('~'):
            rules.append(m[1:].strip())
        else:
            members.append(m.rstrip('*'))
    # BADGES.txt is written for an HTML page, so the concept line carries
    # entities and <em>. React renders those literally, so they are decoded
    # here rather than left for the UI to cope with.
    concept = (concept.replace('&mdash;', '—').replace('&amp;', '&')
                      .replace('<em>', '').replace('</em>', '')
                      .replace('<b>', '').replace('</b>', ''))
    row = {'n': name, 'c': cat, 'd': dif, 'concept': concept, 'm': members}
    if tiers:
        row['t'] = [int(x) for x in tiers.split(',')]
    if rules:
        row['rule'] = rules
    badges.append(row)

# ---- the cards --------------------------------------------------------------
# Keyed "Badge||Species", which is the membership - a species in four badges has
# four cards and they are four different arguments.
cards = {}
for line in io.open('design/BADGE_CARDS.txt', encoding='utf-8'):
    s = line.rstrip('\n')
    if not s.strip() or s.lstrip().startswith('!'):
        continue
    parts = [p.strip() for p in s.split('::')]
    if len(parts) < 3:
        continue
    cards[parts[0] + '||' + parts[1]] = '::'.join(parts[2:]).strip()

# ---- the rename table, new name -> the name the game still uses --------------
rename = {}
for line in io.open('design/PENDING_MOVES.txt', encoding='utf-8'):
    s = line.rstrip('\n')
    if not s.strip() or s.lstrip().startswith('!') or '=' not in s:
        continue
    route, names = s.split('=', 1)
    if route.strip() != 'RENAME':
        continue
    for pair in names.split('|'):
        if '::' not in pair:
            continue
        a, b = pair.split('::', 1)
        rename[b.strip()] = a.strip()

missing_cards = [b['n'] + ' :: ' + m for b in badges for m in b['m']
                 if (b['n'] + '||' + m) not in cards]

HEAD = '''// ---------- Part 77: THE BADGE BOOK ----------
// GENERATED by design/tools/make_badge_part.py from design/BADGES.txt and
// design/BADGE_CARDS.txt. Do not hand-edit: re-run the script.
//
// Fifty badges, %d memberships across %d species, and a written card for every
// one of them. Ayr, 2026-08-29: "it's not just a title with names."
//
// WHAT THIS IS, AND WHAT IT IS NOT
//
// The gym ladder is already called badges in this game - thirteen of them, 🏅,
// earned by beating a leader. These are not those, and the UI never mixes them:
// these are 🎖️ and they are earned by NOTICING something.
//
// From GDD s12, and it governs how the screen behaves:
//
//     "The badge is the reward. The concept is the payload."
//     "The concept arrives as the explanation of why those five animals belong
//      together - and it arrives AFTER they have already noticed the pattern
//      themselves, which is the only order that teaches."
//
// So the book does not open with the lesson. A badge you hold nothing from shows
// its name and nothing else. As you befriend members they appear, and the shape
// of the set becomes visible before anything explains it. The concept line
// unlocks when the badge is earned - at bronze for a tiered one - and only then
// do the member cards become readable.
//
// A member counts when it is BEFRIENDED, dex === 2, not merely seen. Seeing an
// animal is not noticing anything about it.
//
// THE NAMES. BADGES.txt is Terrane's roster, after the generics audit; this
// game's DEX still holds the names those replaced, because the renames live in
// PENDING_MOVES.txt and were never applied here. 55 of the 324 members are
// affected, so members are resolved against the live DEX at runtime with the
// rename table as a fallback, and the count is logged. Nothing is baked in: a
// baked key list would rot silently the day a species is renamed, and this
// reports its own failures instead.

const BADGE_RENAME = %s;

const BADGE_DATA = %s;

const BADGE_CARDS = %s;
'''

BODY = r'''
// Name -> DEX key, built once from the live DEX. Longest-first is irrelevant
// here because these are whole names, not substrings.
const BADGE_KEY_BY_NAME = (() => {
  const out = {};
  Object.keys(DEX).forEach((k) => { const n = DEX[k].n || k; if (!(n in out)) out[n] = k; });
  return out;
})();

const badgeResolve = (name) => BADGE_KEY_BY_NAME[name]
  || BADGE_KEY_BY_NAME[BADGE_RENAME[name]] || null;

// Every badge gets its members resolved to keys once, at load. `lost` is a
// member this game has no species for at all - it should be empty, and if it is
// not, the console says which, rather than the badge quietly becoming easier.
const BADGES_BOOK = BADGE_DATA.map((b) => {
  const keys = [], lost = [];
  b.m.forEach((n) => { const k = badgeResolve(n); if (k) keys.push([k, n]); else lost.push(n); });
  return { ...b, keys, lost };
});

// How many members are befriended, and what that earns.
const badgeHeld = (st, b) => b.keys.filter(([k]) => (st.dex || {})[k] === 2).length;
const badgeTierOf = (st, b) => {
  const got = badgeHeld(st, b);
  if (b.t) {
    if (got >= b.t[2]) return "gold";
    if (got >= b.t[1]) return "silver";
    if (got >= b.t[0]) return "bronze";
    return null;
  }
  return got >= b.keys.length && b.keys.length ? "gold" : null;
};
const badgeEarned = (st, b) => !!badgeTierOf(st, b);
const badgeGoal = (b) => (b.t ? b.t[0] : b.keys.length);

// The card for one membership, by the Terrane name the card was written under.
const badgeCardFor = (badgeName, memberName) => BADGE_CARDS[badgeName + "||" + memberName] || null;

const BADGE_CATS = ["Reproduction", "Senses", "The body", "Evolution",
  "Behaviour", "Conservation", "Extremes"];

{
  const members = BADGES_BOOK.reduce((n, b) => n + b.keys.length, 0);
  const lost = BADGES_BOOK.filter((b) => b.lost.length);
  const viaRename = BADGES_BOOK.reduce((n, b) =>
    n + b.keys.filter(([k, n2]) => (DEX[k].n || k) !== n2).length, 0);
  const noCard = BADGES_BOOK.reduce((n, b) =>
    n + b.keys.filter(([, n2]) => !badgeCardFor(b.n, n2)).length, 0);
  console.log(`[part77] the badge book: ${BADGES_BOOK.length} badges | memberships: ${members}`
    + ` | resolved under an older name: ${viaRename}`
    + ` | cards: ${members - noCard}/${members}`
    + (lost.length ? ` | NO SPECIES FOR: ${lost.map((b) => b.n + ":" + b.lost.join(",")).join(" ")}` : ""));
}
'''

src = (HEAD % (sum(len(b['m']) for b in badges),
               len({m for b in badges for m in b['m']}),
               json.dumps(rename, ensure_ascii=False, indent=0, sort_keys=True),
               json.dumps(badges, ensure_ascii=False, indent=0),
               json.dumps(cards, ensure_ascii=False, indent=0, sort_keys=True))) + BODY

io.open(OUT, 'w', encoding='utf-8', newline='\n').write(src)

print('wrote %s' % OUT)
print('   badges           %d' % len(badges))
print('   memberships      %d' % sum(len(b['m']) for b in badges))
print('   distinct species %d' % len({m for b in badges for m in b['m']}))
print('   cards            %d' % len(cards))
print('   rename rules     %d' % len(rename))
print('   size             %.0f KB' % (len(src) / 1024.0))
if missing_cards:
    print('   MEMBERSHIPS WITH NO CARD: %d' % len(missing_cards))
    for m in missing_cards[:10]:
        print('      ' + m)
else:
    print('   every membership has a card')
