"""Build game.part78.jsx - the manifest of which people have been drawn.

    python design/tools/make_people_part.py

The people are being drawn through the animals' own pipeline, one at a time, and
they land in art/ as they finish. The game cannot check whether a file exists, so
it needs a list - and a list that is hand-maintained will be wrong within a day.
This scans art/ and writes it.

RE-RUN IT AFTER ANY PEOPLE RENDER. Anything not in the manifest keeps its old
drawn-SVG appearance, which is the point: art can land in any order and the game
is never broken by a half-finished cast.

THE KEY HAS TO BE DERIVABLE FROM THE EMOJI. part56 reads a person out of an emoji
- role, skin tone, hair, age, head covering - and the art key is built from those
same fields in a fixed order, so the game can compute the filename it wants
without a lookup table that could drift from the files on disk.
"""
import io, os, re, json

os.chdir("C:/Claude/wildlands")
ART = "art"
OUT = "game.part78.jsx"

people = sorted(f[:-4] for f in os.listdir(ART)
                if f.endswith(".png") and (f.startswith("npc_") or f.startswith("ranger_")))
npc = [k for k in people if k.startswith("npc_")]
ranger = [k for k in people if k.startswith("ranger_")]
FACINGS = ["ranger_down", "ranger_up", "ranger_left", "ranger_right", "ranger_swim"]
complete = all(f in ranger for f in FACINGS)

src = '''// ---------- Part 78: WHO HAS BEEN DRAWN ----------
// GENERATED by design/tools/make_people_part.py. Do not hand-edit: re-run it.
//
// The people are being drawn through the same pipeline as the 1183 animals -
// same model, same style string, same background removal - because the thing
// that was wrong with them was that they did not match. Ayr, 2026-09-03: the
// vector people next to the rendered animals were two art languages on one
// screen.
//
// They land one at a time, so this is a manifest rather than a switch. A person
// listed here renders from art/; a person not listed keeps the drawn SVG from
// part56 exactly as before. The cast can therefore be finished in any order,
// over any number of sessions, and the game is never half-broken.
//
// THE AVATAR IS ALL-OR-NOTHING, and that is deliberate. Mixing a rendered front
// view with a drawn side view would change who she is as she turns, which is
// worse than either on its own. She only switches over once all five exist.

const PEOPLE_ART = %s;

const RANGER_ART_READY = %s;

// Build the art key from the person part56 already decoded. Same fields, fixed
// order - so this cannot drift from the filenames unless the generator changes.
const personArtKey = (p) => {
  if (!p) return null;
  const bits = [p.role, p.hair];
  const tone = ["#f4d9c0", "#e8c39a", "#c98f5f", "#9c6438", "#6f4a2e"].indexOf(p.skin);
  if (tone >= 0) bits.push("t" + (tone + 1));
  ["elder", "beard", "child", "long"].forEach((f) => { if (p[f]) bits.push(f); });
  if (p.covered) bits.push(p.covered);
  return "npc_" + bits.join("_");
};

// Anyone the game asks for and cannot find is reported once, by key. That is
// the list of who still has to be drawn, and it comes from the running game
// rather than from a scan of the source - which is the only way to be sure the
// cast list matches the people actually standing on the maps.
const PEOPLE_MISSING = {};
const personArtUrl = (p) => {
  const k = personArtKey(p);
  if (!k) return null;
  if (PEOPLE_ART[k]) return 'url("art/' + k + '.png")';
  if (!PEOPLE_MISSING[k]) {
    PEOPLE_MISSING[k] = 1;
    console.warn("[part78] no drawing for " + k);
  }
  return null;
};

console.log("[part78] people drawn: " + Object.keys(PEOPLE_ART).filter((k) => k.indexOf("npc_") === 0).length
  + " of the cast | ranger: " + (RANGER_ART_READY ? "all five facings" : "still on the drawn sprite"));
''' % (json.dumps({k: 1 for k in people}, indent=0, sort_keys=True),
       "true" if complete else "false")

io.open(OUT, "w", encoding="utf-8", newline="\n").write(src)
print("wrote %s" % OUT)
print("   cast drawn      %d" % len(npc))
print("   ranger facings  %d of 5%s" % (len(ranger), "  (complete)" if complete else ""))
